@startuml test
!define Sprites https://raw.githubusercontent.com/veljko/plantuml-sprites/main/sprites
!include Sprites/docker_logo.puml

actor alice
node "<$devops_docker_logo,color=blue>" as docker

alice -> docker

@endumls