sprite $d365_AIBuilder [96x96/16z] {
xT9RSXiX48LXe6ymUF_hpRGTKJebKjDYq9FpFoM-V9HEE_sE2fN9VxVfMclLGHQnQhBjXIpr9ydV_sMhdd6-Rmzka8J_lHjfVSxmlqgtXxz8ogtX6sgjlcIo
EX9RQm_t4T2tpa3wK26GryzGG0T_-GmuV8lvU8Ruy14VCuxf17h0XpCi3u_-mXbm-BYFILuS7lsLCnJNbtnCovolRTt7fWzes-RhXCzrds-VzlDEluts-OW_
l-B_lEsZRYgYzlmvxld8k-wfxV5HhoeZhHjyr4qWgpVyuwmDVKm3gRtf7rWREaw38ytzOuwY3_eygpE_j2DIW-7dgRxwN6C-30z11NKoroF1D9FqRrpIgAZh
KR_Q9Uu9FqPYryE-wOKz4bhW1uJulEA-7Uz4z8mv3JZ6Ft_tyVhf4ui64_TR63yxcCxu4tv_-9xiyH4VlYSx_Vxg4yjT7tNqFRxjeuw-9sftVDJH7oFPYeyw
-XYhsQBVCVJn1LlmUyZtv5yl33-Weu-ns5d01ptWuqWMy44F-FX2m0SzuED8rtvVypty1FjzGTzs-mo-VT8txnE-_TZRVMPs7zhbywFzFaErllZ9UfJtU6xF
VN6VZhxWepltjIIFwj7ZFiWp7talI-jzjw-SqwZewSPyZlcd3XKxvKl_A-XBIIzn1NlAN_l-W5B2nXccflVuJnS4CN4VXiUA7eu0wVyVNVicGvz5TlGl9w6u
hoLTn8ul-apfidpSyDDlz__xgQtx5F5rtIyHFzTLdrAeBCUINrAqOlrjdt9w8wezwACUZrl03qqJFmFwwpgU0VteDF4pe1_Hry_Gdcs1QHRBUWozQqvbw79R
npDq-_OoiNYtfy4pz4RZ8n4CloDYWj6owx-XFm
}

!define D365_AIBUILDER(_color)                                 SPRITE_PUT(                                  d365_AIBuilder, _color)
!define D365_AIBUILDER(_color, _scale)                         SPRITE_PUT(                                  d365_AIBuilder, _color, _scale)
!define D365_AIBUILDER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 AIBUILDER,         d365_AIBuilder, _color, _scale)
!define D365_AIBUILDER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 AIBUILDER,         d365_AIBuilder, _color, _scale, _shape)
!define D365_AIBUILDER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 AIBUILDER, _label, d365_AIBuilder, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 AIBUILDER>> White
