sprite $d365_AIBuilder [256x256/16z] {
xTthbh8y4ePXGtOY_ItF_sm7W_VIuXswr0vbK9xP_68sLr4LqeXuNYjxzkpPSvZYkX9tcB9yd9F7RJtIvQHBF-u3wFzr4ykFcM3TV-3kZ_lfhlpnC7dS9xI-
3oLUDhSyhk3BWQK47BTz_sYAgIIEjaN_1HzZEKmSjs7wbHzJFfRa5CCq1Opu_BWf_nwtJRz3TRpcAkjWtOxZG0uJnstKB_Io0j9VZakv72ahi3N_lUh2adfe
fRd5SPH95ehZo8RyT3IS-p04Tth1dm_BPloYfHVqOY7at0lzRyFIl9-JBpfwkGT4wokjiW6_hfVdDinFlZO4hQ_ujBIYXyRSAuSnBBH1qvjT1h_lVrFrVQ4L
lXPs0rtxVlHwH7MKvDb2s7Bhqz6gN_I7cdQ7O7x5nwRmbMFqtK3JLtoL_w1VspetT7_7JtfWG2VgF4_xMGZvgwWbF-SUle1f_iqE0VJR5N-1MiTFcjaIu_T-
r2Vq1WNWKj2AVzAR-6K5tkQVN_6nh-NNTmDlsktH-iP-Mi1yHuZyJEkZj_RB8JYRLK7UicJPC_VBtO0xMFivz_0j_FeG75Qd2pvwMx-CuPPOtjYbzOty-cx0
o2-NFNk__cUHmSddtB_PJmnQG6bz8x_zbbX-FY_qxHH03a7tKxS8zrTyz8tvgG2xWUf-kUmrvYVrFpA5VkLpxflqozq0HQZZ5yjUetwv45Rr2tshVbc12dxb
Yj-WdmhKUMv0kUBR-Ustn9nvvTQcaT_-9kdTXvcUSxybFxk1L-yCA5Vynlsq01LusI-MlOtv6OAN_9VhfojyzDlpywHPeRZd_DqbFdBoj-SdqwDs8-QfvcUx
YtwpVWfGI4_wGynRzfCSmqj-7nFyRVlJg_wyTJyDu5_o9_XRzoVyJrpyTd_Ol9yK_uXwqf-RzU_-X_-B-bRzf8wUVAPVnvFY5GT_a5_YbwlnaVwvLUc7xVjr
VSxvrudu8Bz45lkObCVyLe7FyCzz5tqYF7IxaAtvTJxVZRn6hS06_Rg-y6K5Vl67RVdrreyojC37-FNM9t88Figljxuo11ltzqhhFpe4B_jxIxy--BBrbI7O
khzN1byPWeRzfnCHVc7NzDeGjEf7JXI_ikmfGz2K_s8zAVuNbZrb2EpzADNWhz3woX0Si_7vVztV_wNrPGlG0t_pd_vkrFtOvz7q-X3ytN-QiGM_fhzNMl_5
5gZiXr_FtyF_S-lB9Au4B_gxoRzQf5zl_TU7eAp_rppe7sFYPm0gw-KGv2VyrwUTlUkwcE6lwwyx-3Af9F80G5IBSFUDvdIqzyl1hrG1-IIaxkUnF_Yc_gfw
_Ch3iFA9Jvvsjk2Vrcdz91EZV6L2YVQDvjxUJ-lNrFDV5qe5dEPtdOsUhDBwm6K9mk8GSEgTNUkJYgsVVWb3u4KBBBV-oIfAwwzR0V1thK_d6_ihw9EU-Ez2
YFzWtFe4FVpwR1cMWRaVFNmxFthyQnTW_cfX-95pRnfQ_ouhmGdR8VpbRUE5ZzxKZrvcJJu5A3cVVSdx-8d8hEZdBu9kJ6d_BiG4tzgV54qrjCnj18e_PVZc
_Z16amd-6dvEltcECNYl5o1LvBC4tFjp_qw_fmKCmnV3tCKVZs_m3mD-Al0MlpkuYz-UFmR_9SO5Y57wpVNIRzy2zdw9d_kfmEVxXmK_G_3X_c7HJmjyhX-y
z9jNmDwFNlUp7VeiFthTJmMC_TPw_0c_JGNi_UWLl-4GsFk7fU2tR05x__22dok1dTzUZz-e0lP-zBhVO0ZC_UXrlq4BsFkbNlVh5SW6VZEzz1iCWPKVVIs_
R87M_UYh-MK5yfZs_KDTlzmGDkn7NzzF2z03kL4_-lf-Ue02jEP7lvfV3i4b3VdHh-cN2s59DR-rNlVhGr3IZdymyjC2bA01FtWR_tm8yllzWwr_FWJPtY_r
jdxP0iJUZzxOBokGRx7sexVtozr09kR-WTZxQG7P0qP-zEP-VHamyQEtz-iLCF2ZRy7lmtmXjF0FbVtsBI3zrdhfDsY1clwX0R-o6LZJFpJdfm8f6VY7sdxx
0kG_-8Vs_CJ2FxJi3_6n5I3dJ_N7HneWVwm_QFvSyhf_sAoVVAaV_DVuyxqQDsd97zRraopJYBzVsv_9r_dHVv-VV8a_JC4lyWN-yDt-83BwZz_XH_ob_l25
_g2c-8yVwW-F-e-h-GTpl-Jh_load-__lj4VNa1Nyn-AFu_-uMlzBkHZc_wmbZ-bSEzFkM_4Byth-SNx3tn8nu9hu_p_oN-yHFN7uF77G_cbr_wTwvyah-ul
Fumy-ltXS7PZUFzFyRt37-pyy5t9xPUUOw80d-vFTyr_zVDJrxrb-_-ynP_WBxp_xQgqyG_6VlI5Zv-uhWp1rMdG_SKVHt-myj-z-mp_cFaR46zK6t-myQVf
v1S-UEbtjmfydf_MTml-avD3SFEkvFzPpqy1f9xMTrdwAO9y-RFmbt-hpBVnev-lUpBo9RWTGt0x_vlsorLV-cNeWH0J2s4jBFaXQ_WJ_WKzUCtVUR4Rg9YV
DVqH_rmF_p7_vN3745H23_UnyiC7h_ddhm9_U0Zm_Inc4B7nfuNMLpBV4Z_j7zhm2_tpVXR2UGlekk57Yu5VR7RFkl-NtG3BWEudx_QZ7_cAN6c1sq8eREtw
uQjNV3st8M13YArIrlANoKUlq1zR1_sq7uBVj5_SuQdYFzo6e7r_JWczyF-n2BxybvyQzqSk-G9VmzzrqyS4hSu_1M3Tg-jtPrSMmjItxG_APlUFLV2H1cZK
Bt_Vf5uOWf0h-tEiV_PNyFEZYBvnV-53_pw_h-tV_Nl_x_xTl_jt_-xV_Rj_z_zygt_tx_l_r7-f_p2c-4_VwozVbMZOxzVtXzJZhv3AVlZh-PsFN06-qzzv
9g0fF_nL_S6N3yBu4AGnFsVVEVmhNG93p3qLQCVFdN_mg_cdpy7wOMZ9hppgKBK4plcGIWiChVWz_BNzjmUZ8Xy6lzcF7lxgvxyKsar3S1eQyADVrq_ctnKO
1Wk_VUlh3yLq7KDWxfUhFdn3lplpNG5QmC9lt_hw8x9KmDxlqGkyhN-CZsm8JVriUCpziWXYDs3cv-HBkhcVbP0AlEH_hW0n2lsx_Ux-cuF3KCrlt_hskm7T
hxS-yZVw6G9s0-lvOnJwblpARa3n6rpnZOQ02jJsnpWVVEWD-SUm6rZ3Zxur__p-8DV2IluOetB5Rwe9lB_k1XxXd_eKLRrOzjhrioD-V0Y6eJycdQzSyTkh
0hU7JiFl-jCnnr6sBDz6wqk_l47sQ-_d54POn-zNBFdHRyFl3axi1fPFFc-X6IimGvFvDS-tvzU_EJZyttDVMhzpqsMJ5fW5lTBwZVgBYo6OyqVzw4961IGV
lS6gPxWR64PzQNtXOWW2UB7PHRwTtBEem6tPapTjQG5wOBRiRTX__sunNgLnpDEoD_Cp18JMtufVVvb6oJ7pvZr8inOW1d_bcldvRPhfBIpUB_YdIy4r3ltc
_USmJG5FA3WNpl_wmwq4z_Y0VxEvNz_bgPT7uIynMFVCXw0j_vuzU_Ry3m
}

!define D365_AIBUILDER(_color)                                 SPRITE_PUT(                                  d365_AIBuilder, _color)
!define D365_AIBUILDER(_color, _scale)                         SPRITE_PUT(                                  d365_AIBuilder, _color, _scale)
!define D365_AIBUILDER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 AIBUILDER,         d365_AIBuilder, _color, _scale)
!define D365_AIBUILDER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 AIBUILDER,         d365_AIBuilder, _color, _scale, _shape)
!define D365_AIBUILDER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 AIBUILDER, _label, d365_AIBuilder, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 AIBUILDER>> White
