sprite $d365_AIBuilder [256x256/16z] {
xTddkjmg38LX0K8I9lT_lITzzZePJqKsCBn_Kpy_NjgDt2pBiYpB4aNDL2BT4REQQOwJrTiVUhCiAFo-eM7LXGRQ8_Q519f3DaEPhkATtpUsP5Sa-aTK-nUF
F_mTSMSYOFGp4CHsQO3Xxv8mp_1HXk7lonCD7oKO_ZwUQFWe1hK7Q1nk-8r966hu3l8umtUI1lbary4mPq3CbOJF6pxAOmv__ZCGxIWQ9nX--MMICv0VZqPJ
d87qJ3IQu0o4vvhH-6T08FfPetysaCjxnlvi85fvqyYV3GGjRnluim4f3GpxHG6N9gm97cZuQCWl2eALLaRyea1AEzQEZ35yP2tn2CD7rbRo_uZVTRzfw7tu
o9gJpeUFp05tFNnaBbB_myV-pi-052yZ_AI0Yn_pmtqE7vcdrF7miR_NCo35MTS_BWjMHkn7eUVyOXq_02rJz0kz9fOv-YtIIsIMVg6Nb5dwRVM_8CpJ7wRg
N_shV_MNtpwmlrppAVrbt_pzvI6pzfU2zX_8ZFq5gUGVHCjLi_KNfFd2oevv-Wko36Ht1dFq5sII_qzk_VLbxFwoy-eZBJUCtBzVZyHcwxy_V2GsM__zuICT
jl_ruIETf__HUYGsLd-BuIEnaVhR31_fGFsjXezqvFxNwf5Op_tRHSDN7qbd_TjrJUkHdj-_tTLs-4ZqbFxj6H3Ve1w97TM_lMWttoIt89xzs_iywf4sxj-Q
SXa-4dkfNw7PYrSz2lIi3D6k_JwlFahqb0Jndho6ZqIUUGB1jiCKf2xnFpqy0jcsa_hDe_s20zsNjqDvllhoZqHtnBATrIy-yIZ7quUFN8OlD-JGnV2ntyGx
_luPuEqCRUlbCUdCLnyrh9V7vN_ootQEelALNppAX6mx2Sl__QnnQ4VvjEsZcB9SvH0F8drHpkkFwVKd86_8T16sqwGVMFPaaNRnY2xIgVq_iDpGgXq5cFzP
qX_tclvaG_mxOX_z5mt2nkYlNwGl-3FwA_G3dh-_efHGdhGVwx4VYKxPZ_NOZtZI_Wgm7_6C_VLEFyWwMN_TaVQ8JjHVTwLTB3f9VxqXtP15TVp-UbEwAQlg
uFtrsNuagYFtrtlIFIogEcX_lI_TnwewOd-j3VhX38pKNn-J7YFwtK3zjRRfnpCmJ7zjruzFG7M0_bfRzQEiFtNUNwj3Fpw1ZljhzUd74MYl_TMX7x7-rc5_
hQxzE0BjhRzMltua-aS__RLwz-CP-AEF_bhT-n7hNntqrqFwKTQ_JkwlzOH-U09dzjTwJZ-U0JsflzOJ-_4Cw0dzzTn-F0DwT7-jv_VZ4z03-sljeX_FW1xL
Nzj8JR1U7D9VQq_zE0B__bexwySHUFVN_lfn1BxzjSz-l09-_RNR_iG7zDUE-rF-y7vsxwzTzoVvyFxyuVri3_MlVjKf-zD3_QhwOVqO_x7z-iMa-pVin_YF
xLVmOVqAFgnVmSpz_0FqAvYvd_ymC_q1ucVintJe1pFtC_YiVWOVrSyts7SpzpDer9-6w6VmTd-WlqBt_GoQzDCNrd4_WsRzcRv8VVRpy-o7H-T_eTtryslA
W_rCo3hgP-3Id-d_j8z-1gtxCH_5Sd8_0yT-YNHLEg-VWMy_qouveP-1UtyET4EmW_kP7VhjgLSVnJ9nVw87f5dxcHuaC_RdG0yBDdQ_lJ1y5CjK_OcUnlFq
Cxr4vkZFWLuKpAVRln-7_xe8uGFs9teJRmFtCpKW0_OR3FzDeLGVtxvzy-hV6VxfP-0RSEnFr1HlRP8Fwi_KdBPgzk-NG0v2QP7itw-9dCIjGRDtFvCZnkJ-
-YMGgwtpVdhJwb_zgt_rh_xLl_fN_-fV_Qj_zQ_-rR_wLt_fkp-HC-sxFv8pxhi_aBVQTJ-vopttH_9N-krFT8IjstuwXlNPd-WegNRO7-b0N3lhJtGmxQa_
qV52wQO_41Zf38msV9JhwVs9JgNdzgT0OBWpu33yeSx0eCD7-Op-H63GC-0m_A7EWCFmXpe3OmyVvMFw4tNB_FjJe8w5pRa_4XZ-34nHZx9NVw91c4j_8337
6HZWrNVy1bdbE54zallvIjybX-4FSGPAe9z2SXX-zsTWI_HNS7ZrE_zi81E8V4tEK3yasHq-IWpo3vne0hOtV1IW_GSE1EOu0pKHW17a2uuq3Qv_wpFT41dg
9y9MlySRqnqnSSwS7EkNPLcMPVaF
}

!define D365_AIBUILDER(_color)                                 SPRITE_PUT(                                  d365_AIBuilder, _color)
!define D365_AIBUILDER(_color, _scale)                         SPRITE_PUT(                                  d365_AIBuilder, _color, _scale)
!define D365_AIBUILDER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 AIBUILDER,         d365_AIBuilder, _color, _scale)
!define D365_AIBUILDER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 AIBUILDER,         d365_AIBuilder, _color, _scale, _shape)
!define D365_AIBUILDER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 AIBUILDER, _label, d365_AIBuilder, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 AIBUILDER>> White
