sprite $d365_Dataverse [256x256/16z] {
xC610000080WXFrj5wa20000003Wzkv4ot4MXmAmqG99p_R-RpiLtsE5BaBQjb1-ge_lMMUfvHD2EAvEV2HBDvV_yl_LtfI8M8JJYx0ACr5AQKGz72KEzITY
5c7w2Zz3Qra4_kKlyMzcVU8JhNn4dn51K02K82rvgyLnTA8blUAd3zR1VkPg8YpuoivRobVo5XI26KMWgXLETThwvMdBWWLOFkz_K6fuMNFxdeAW3YAemcb_
GW79af3A7-ucna-b5P-peU-zM2bordL8uCkj3ZleDP-u2j5pjjg-2kvxp3NH7NZBxoLWOl3t-skxMAm6THj4zptifMVVtmQx_T2Rl0bpFLUYvDRs3ppW9xAM
01L8xrTjiLGdZBQH-eor14qyKOSUiIQmOVZMZw9tz8YyAC50-ly86zzMte6thO0kO1GW_QlvfH-dUaBPWQ_u_IQeUs1ewsFRvrBRlKL00UZr9gWNt-Xl8vWg
0VxEhdUcwe6UtnPVz-HR2uoXWszBFpOtD04bx0BxhTCMihNVNO5c27XR7_e2_VWAD2q0FmOk-0U2FJ3ERsiVmhTTW45O-wkTVoZO0qx_Kb_jD9qVqmCs1wih
7kWF1WNOul1lhGzzT0NmQrkCxop0sRvV-StO2wu09UCd1lzCfFfElhbdQnyVAq3rCkDawe7gddltJmLJ83LyNmESmOFlsFYU5i0L1_Y-0YIKuDoBN7NmlNl0
Bdi-tG4Rtt7ekSUW2fDZzjM7m36_e_U7je2AY9kF6NZ2x-ZzSMDmH4GufIMbT7JrHNszxo_0c0fW10hlQm4xzRs7lj-FsqF-71g10LlVTt_iatxW5snzhzxF
znV0pi0Z_XduyAC0dpi2RFBbsmJyWGMWj6RlkLV0dy5V5o3sTP2TUzFmuKS1elqF-enyT43y4U1f_dX__f2VP1B-u0A8y3l_Wc3r0pm-FmeGUGJM_DjqV1J0
xr_pna-CStz6lxy0vc_n2EvsJCd73XXp1FOt_yHy521c01XVmP_LN_AG4w2x-QVXXpN0QtzQy-3FwqS1Xco0HlzOV6B94_CHRmEyzAFvUQRD7xG31FT1s-wt
sJUzlsJ_9T3Bb_o2pH-9yVBz3T3wWqx-liFXzuz0eKTQ_udkToWSV6S321DHQVo9mG_7Myv_RIbE_x8qHp_PqHTljtI-FBG1S0NmRV79Blp2-SM24fpmknf0
fFKlwvLFi1xoNAUKKjVWrow-lm4QFsP_k3xZjwx-fBtM01NOwKTyVkp_WEl-lXqh1hdmcgqAA47rBM8R00F0_BG6mozAZuM7_7l4tZiJxRV8qv_IeWipQmdZ
bm8yzxEM03rmsvbIXlYtAvzSWlYrdZfXhjz94jm0yAVwTU-8uVTcJedftnN0tZ_tcG5W_hICUDtpfaaD_pwem942ZF0JqOW_TxnR_1w--Uzj5qGtWB2z_a7d
vI1-Rzypyd8Ne02nbm3CDFAcJxS_vGMUgLCEOY8K89Vu1gXVz-KIpw-bhH-ffq2mdv_lgs4R_j5yitVy2FP0lBz-tHl4f_Sn-wa2b5ASVlm2MYBu0luJUS2F
0WJxd-zh2EX-M_qUk8Mt1OZR029S_x4xa7zetTi2nFjn-CNn-HmV1OZpY_an_IBuv-GM-UCfwF5lXr_0yeE_1-zl03qN-5CYpgFv6FrElHKWR0FOVPyFTJ-V
Y6WfONvUesNiyeFlnri3H5q1BbzXaLm2bdypU-nMW1Y_RlUzRa73ZmbwLqGY_NZfCthusUiuqmSr0FpPuyVXFv1V57uU5OdoR_Vz8dO_M-8QmEzFYNIm_y7_
8NxSzmnOVlX75Y34p-pva-_jtVJZmVuICl-8MKVxLNXu9CYFV-qsTlcL0_mws8ylmL-z0jeVYTq0Vh-i_l67Vq0Y_28BJh_XXtz00mJvEO_T_l1Jx0Rm-_FJ
VxiDt_x44_kXXp-Hv55yfEYFySlgBm5-djAVgy3FDDoVe_pYyeFS-bddzoEYplLl_VYk3lxK_lmkvi-tqNx-GNxHmVwI9Tg_l_t_xDUVvCzz_ovmwoVLyfVv
TR-VYJIVzD_cyDidWkJ3KPz_blaFFqY7sp_bly2VJ_jJoWL-Bp_UBo5-uy_lrzppdme-LdMylmJwX_9LwFBVHjxyiFi_y_in_fSVvN_9z_ZJiXX_Vl_8vRVr
1sQG__Ft_ul3pqnf6SUF__jF6RtyNudnIypsdzOVVmAAv77B3pzH2l9daUWNVtu_FlyYm1zn2ImoUlez_4k0F-O441tU_lW0h1Z_y0QGqNmLWZ-g0IPVVkLO
lqhuuLTyxKzBb1z7OEpoW-_on-r_DC2qPpzElqW_2Z3vyZ_olnW_Ti2Smmz-IkQVl05ayF2hf__oFyVh_vW2n7U_NVp0Vulmem0oO_UZ_J_X7p42H2BuRFvI
eZO0Ta3CwhkN_mF-EmhWNlqoce-Nll5-5434D_f7Tp-cdttuToubokykW6WUpg-dt-hF9Me0sjCBPIpVl_oqc5zpt0P01vmS0kBWJ-570KvEGV1lGVoKdduD
zPyP0j07yUtI_t-8m1-s0J043bPWrGVnbLDQQdyEzXyUWuAFVehWryCVOOdsMm5KH7RWRV7lZNu4dx_xzNQFBW26m8uAhFXS0XQ_voVMyXb_sIeW_QKNwCFu
6SEVApzzmbzrhtv5je2DgAhfxyDx7scVUvD8IjW6-COlfb2hGaNFnPO-H5_VzwZzENm0G80OHItVFm8wZAzCt_rBOlZ36i3u_S3-ccybyqVbfLzZDq2VV_jp
Hk7jTVyuFxA7VmFXlVxUmLVyiPS-2Dx_6-lV2BjRe9cNCSFF_2NC3xuXoki4s-tex_WL_k45gBhVKdOaG6_Tt_WJC_pZ2r1rVnK7tjtzhTy-zpZ0Z_-neVZT
_kj-2ts5NVxxeUMtEEIEew_nuw4FKNxm-ud6rvk_v_Ty0WJollid2Bh_vVC-jm__3FANCWT_tVqzVv8Sq03JyF6FNH9ntwy-_ttgvN_xl7ltvnyYhrRVnm--
xhM82BDeYV1FmgTtVdnEeS0_hW1O_cduVJyH9Tm4ycNAuMVylZ-jOVWzcN7vzp_f7oU0AnFo5VptVhi4ycQsuGV-JZyQm9UfTZ_ulUwFUUvXmDaVEFhg8v1P
XpttS29-Y-yVWUK-8dFiVl1t-l7mCsm0Vy0lapT_v7D_P-BN-F0ZyDSaVXNq_W4_6i39VsJbpt3k7VPx6-0N_0-zwWIJ3_hzVbm4-_rPHLIdc7pctti4b9kV
B_WdRF-C7lm3UCHx4MZyUrbt7paAu5pyWyrVF_-LMChDmSVoq_P0jNzewv_msqC0SH7Ww_wqR0NGJ-kFdFh8eEUV6z-stoVtGB6Ttrdwu4FG-4LvdQJBnrl0
z1w_TS3vawywUn8HXrUW5EWzYsz-Ay3frQVAZu4YeXzhVOU_lWu-s07GWvyU-Mq_XMy2jRbdU9yVJyGuUkvZz5L-95a5WZhVZlmHVkJGCMWN_KBWF_tL71GD
FlFSVkHP0Eo1NVX7xzkVsDjweWL4DQRpXxH--okl7pYqi_KBUh_Zno0STXIKyfpvQBcn_lqjWE2Z3Xw_1ItqmdzFgC7O7gZtVRgRVsG7CDw1jorsk_30_-5M
urBl0aS9oYDcH-CtIp_IZzCR5VYUZlwjtqgWwcbxs_Lxffv_3jexKbxVvDrxqTqqWPxiUblwHXxYfsrqbqT-UqC25c974pQZiAr1UPF6JYbXveVx2KSQIg3D
EjZysUr7ql4sC3pAdKuSUgxheJNrsvRan2LtNG525poYI8Ujzfun8aVV-_n4c8S8HgFNltt3Ps7r6QWhE2NamtxmhSEhqC9qrf-IVfy7tBOOGaGrcyFzRPPE
ndpBhG3qFU1xJhhv_JOChPcionEnRCl_MV_FBF7bl_nNhbovSkNAbIjNhbovSkNAbIjNhbovSkNAbIjN_Wy
}

!define D365_DATAVERSE(_color)                                 SPRITE_PUT(                                  d365_Dataverse, _color)
!define D365_DATAVERSE(_color, _scale)                         SPRITE_PUT(                                  d365_Dataverse, _color, _scale)
!define D365_DATAVERSE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 DATAVERSE,         d365_Dataverse, _color, _scale)
!define D365_DATAVERSE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 DATAVERSE,         d365_Dataverse, _color, _scale, _shape)
!define D365_DATAVERSE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 DATAVERSE, _label, d365_Dataverse, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 DATAVERSE>> White
