sprite $d365_Dataverse [256x256/16z] {
xC610000082W_QaNgG8000000020sRklTDTr6mp38D7t_EURmiTPrP9b4RzCxvptAhSV0L8hxVY0rbdD8p-5cqflxQyF5ulS4oQzqT-eI-HHBergj9iNj-j6
E_0CMfSVNhHOx7bIQ3-zR1lwcl7RjD6pcWolFuBkMI2aOFJNdq3JB6Ezi5x_erym-bB11Pil-gaJ44TkW9x0iVGR0TTVVWBjK3fy1IGI9ZfjugVQ1uRC7ihR
uNnzJAXMZuGpkkT0Elm0ckSbU2zVdqHbDA_Yz_Fr5FZgurVWG3lw2bXUo-WJwnH1lFfuZMwwJcB4yF64XgRJEkxcu--0w3p8iuyN1ou_-WdmVANMjKIdSrha
QvdMe5CuNyp3j0G3hZvUH5GT0E2pX-Tr1z0HBnz-_7K707ZvqABo0FeRvbSUW03oiQBs01eTrdC17b_eF7wl_FZ6Btm1MwuWoW-WlMl-u5UzWB5cVvZEUj_y
uP8_0JoNxNUT96-Jxt6FmI-0BZlzmS0NW7FjViTUWBPo_c3G2n3BzmVoJo1RA1zq0_XDBZ_i1e0lFxxVKVsnVlvWc2-WWelA-Xto1Mo8RXyYXjk_dieV3741
ehuzxdEFkNu7z0iaVjlM6Vo90wpy0MZ0-6qdfZzu-GFWXVNnZ5FzOSKNWA-fTrCHPkwzCukeUKHiR3zk0O2Ftqwzgt3_XSKyFlCp3ghzjm227hufzqsidgF-
pvyuoaeVGF3mH_mkiV_MZ_7ZBm3J3uOSlai_WYt7-8-okWUW8OUl_IYsU4s_uVAL-nFOup0lws-mtNVfps6Dmye-00RA_nW-PWMiw0FGKFdIJs0s_0LW-a8n
-Nvc-8F0Bu2KVlkBylc3m2y0VP8bylcx2_iNoEVVm0y0VU1Nv_DzL_L7JecvVDuayLX1VqCy_JmPFoZo0MXqeu3jb-dumQxe1-HhGVlWk0UW4mtz-ilFn-7x
lNxyN18_ABp_qktdfpdg0y0qy7NRpsT8xBF9Vhze_7oMWVg5Xl9yBumVeFsC__Jp94Fs6tZyF4-G_UL_-6ff_E2u_bOz_k3Iza5m_LhTRyNn0wu_giSl8xwO
mRx_zUkF8AZ-dgV5NSOGg7wj7hyoX07w-zJrZ_iOGq7zDUF7zmkWln6rwdvd44m_Lw-_COZ75ftej-hr5mQn-l_yv_pr_wS_DZ2A8lhR-_GBeh-NhJ--7_5l
V-J_jj_CcCZ-Wlq_apvqegZElxxVpwGFRUBvz_Vhjv_eh-YtC-a3KNkZVZtNRvkcFd-n8Q_kzpFfWn1nTNxarN__sfdseHD9UNyeW_ZHVZke4UaRzHzPVti6
4LdvynV-edvx6X5vVNymXkJs-jiPGaHHtv-CeNVxtKxhH9I0Vhto-RFp6gO_Z26YUFn6eFu0NV_YVaNrfp20PV7wTrY_lSNwDqZ_SDdhRnC8q8_x0dWMZr-0
_S7Lf7py3TSVASkFtmZP7ykFNv3zaRhw-3ksF_3ZTvj1a_snBuqBHHPllocwl_89jFhnzuz-r054uVPdTRxHJU0MmA2FdqsH-N_SaSDk07xxhT6DuVgB3a01
ss_qFmhhZynOzF9RB_Y_FSVZ_lJv_EfFtq0VUc8F09BlDaTA-Xrp0FXyeqyDt9-nNhxI5y3z7_qPCl7o9o3VsaO_u04Ob4ynKBxILm6y07bZ_3pnt5Z-ql6J
WVjFtW5DLBxIDm9_00P_SlYmV6lqJK_u0WoXKpT_C2iVFpNu0pY4koiV8PQWuG-DVhYctmUJ0viFpLSgx4y_skytuRex-W3M3_IBNR00uHyYuluMw4SyC5-A
_ud71_lT_8l8lFq3a0THDOzCSFr0lpNy1GWpywyYyfu0rrkdEtB2qV6F0zWzWhZFtUeetHEu1VZ87_odUCIjLAl_kOiZyxSF_jjskrinHlp4fJ_i_zRXT_rA
TmEW3JdZuVp3Vl8z1jCW_UaF-ksEZNGe1ltItTFZ7pRQSHJs6xU-F_v5q8wSivVljePEEnop06Fxro2qXnDo0EkCNsbVpbb-_EWV-lMr7xz63qXEMdhxEptI
8FrXI-0hVkbwtV4B7I0vQzNnAnsIqu3Zn-UJvopWjm-VJvpJVlI_J_wGyt3RZyydpNcmnm-VJoqBGCQFpnyY2w36ZyydpWhBF7v2pye2VtAHRn_J1kW2Z5zk
N67ydKwew1y7uFPYT4gVpnzYxPTlczVqKr_wwczh9VbCrEnr6fqd1VbE_wKhx_usd-zlDCZAkxzjfdxeTDFVRVX3cymN-j3URVW3pr_-3_9cmn-a9dzeQ_p5
Xp-07_cNhu1G8IdA7veQd5AjVYfVwRvkO8sgjHFzJ9iOMu_WJzPdepsomBC7-WvkxZx-1BGHa1tkZqu7iDMIHbZD3-Kdqq4TiFXGBV8XfYSq0OmUgMdkyKxF
wWg8H-gs5SzqJbT0F59Z-zakdJR0Be9oenTghVD_zTPe0-uCj3Vw6xNEQli4CFO5Zq7Klb6fsxH_jmS7CW000023_AtlyLLt0000000000G
}

!define D365_DATAVERSE(_color)                                 SPRITE_PUT(                                  d365_Dataverse, _color)
!define D365_DATAVERSE(_color, _scale)                         SPRITE_PUT(                                  d365_Dataverse, _color, _scale)
!define D365_DATAVERSE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 DATAVERSE,         d365_Dataverse, _color, _scale)
!define D365_DATAVERSE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 DATAVERSE,         d365_Dataverse, _color, _scale, _shape)
!define D365_DATAVERSE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 DATAVERSE, _label, d365_Dataverse, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 DATAVERSE>> White
