sprite $d365_Dynamics365 [256x256/16z] {
v9R7TGKn30C5G5aE_NTh_asFwrG0Tsuw3iJq-Jzf1vH18XryFe5q053Pa0ZOKm_9mTcN-gBaB1f8J_9NhgsF5xqroq047k4FODVlOywrfZ7wdW1XHAy3aY1p
wsQ_ioUmHI0IaVrDgbTAkOwvF1R1wBS-u6V04CxUBstNzrnz8E95YkgVMDgOwmVpA89z5iJr1qlt_Xut3M4enyfXzvVh_f-uQQXeHn60V_tlZL2sCWZelxV_
lzok0hewYE6_7Fyai4MGfMZ-N-JSYPhpfWu6O2IyoVT_mHq5sVuyFy-GHNN0w9pkRTfN21a3a_K9_x4sdFPvG07oS7S_pWFDW0Q5ZlpO3DD4OABU_BWgs3SB
e11wy6CtZB1Pq8KVcw4iC0_wyUTV4-4jgGD_xXs9AVJYnmmSlI1rmp117TpNdvy73Al37lmu3zBAQEZCZpd0RiYmMT237pC0cmLD-FqIS5uUD-ANzMDsVXum
4IwER-bVK-JVaMACz_Ql1t_5E7V3n8_1ed4_wZSr1bG1724mXLlvrxy2cg4jZ-Ez_ElJWTrGKx0NGfD-hFjo_BDzhZcWqBX_VIFas2zft5yU-l8yO3n2QCUF
ca-Au2SQzAyk8USZX16E4AhqOylp2DmsrA0M_5vqd0VsdiYr-j6E2N2k0f_xXlv-h7lGUsS0ZX3gysVSxYc0AgZANqw0_pnmU4joyYFzeYA0-uOL-7NQNnUY
LU1mtz373xiPryMH0RnlUBr__Lg8mBtRw_rc_qe2i0gkkc-8VeUAzym07Y5qvSSKm1527_xyF60YN1rsuiUTqv_enuyXq0qpzmsT_MkD8N3D2axIEl7Zga1p
q9CVupmFjkZ0dzq-f_xys0oPgJi_xXN0BF3prnxO3CU1YJhpOmQq1DHF-gi-_1YQ0Ak0hlpO1RG2cl6BU7--9e2f2V_Zf6TUHCHv2jX-STr-k_WmJlEoE2TW
ZApXuP_-Fx-TTci6N8lWqGAi1zJfHtxy2Ss1fi3lemUktg-BjJZFJ6JVCE9M1BeEql4dedhzonIFlNpYHmQq5JZaGCG-l6h_YFwVq1HO5JYqm84VKQrVbf59
tR1rHHoTve4-0Y87ZThzy3rBEWrycY6i0flo7yrm4N7eW2tuZmZmXLCVbe3CKxF-G9O1aOycGAj-IZNmA85tFjacmC3j-7D548VnrGH8YdlucUDh2P0jx2Me
QVz2WV89A9S_-8aQysCMY8VnoIOeSlmsZV_Ikj-Qu2BoLENllnNmKvD-_FVh32ZICKGQ7l_y32YrF4Fh_t_tlzR7dwFEWCBZJYoW0JRhns1cRG7P5YWMCEKD
tl3pF_-Va6c1aetMrp_v5e0jCA__zITNyzDT_D0148fWjCFxpoty-0Z8rxtHeHZQU__DHzGOPidW4Itjxt_aWpMsHw3y5Ik4tCbF74j-U-hZJOZf7dxIYEEI
Z20MYDp9udtyWJZvYwMFvyfk-x-BrE9VYtGS_a_zGQCglnJyo7Vo1nxdTiOVRqDw-VNPKw6_S1dKqGy5K57zb_XEVdl_hi4lwzDy1p-yVsi2f1R_tvy9V0y_
4TaMr29Io_mlN80rlei_R7C0pkITGjxn5mTV-Sv-Qm9sJKsaJh-eVkTFdduDWfiPLVbHFwlUmiMlyKy6O2BKuHVK-_iX0NWvHUhm9xlfCRpzn6H9W1jAt_AZ
7l05l-iyW6xu7Ry8wg_qaztIIYduWX_h7lIN-6E0-vfM19VuCth0k_lB_I36DoU2o0T-h7laN-zdshiXBWlA-e_yW0VzHVxyqd0h0eso_XD_OUWlzUCyW9LH
WVw-VxFZqDSm_eDTMIrau70_vmzR38S_uIqS_Avvi4UYJOJIHONd_O7eSGAiWVRA_1hxpp285CwhN_Ep-ZVyipcus9z-3M_A6jaK_7q_AK30PywPc6O_l-DB
agNWl2m0-kRFty_uPT_crTI8FyNnWomYwCUZ-gNeD_oWwGG_HWL-Z5FD7jqGwW3QtuH-bEFGArxvRVa3CMmMB6V_VZyXxqUywXCV_EUeoWzyWYqZU2JAiVix
n1ZEmLZtPeVXVz4_ElWT5eVO3UNqG-ggZ3Zkf85wepJiry0gsFbZJ5ZqOza37_oPgDdFWU0boMe0BcTOqBdkWQuxsGN_NA4_Fm_iCOvVy8sL3qCFYhluMO5f
SF5xYh8Txmnfr8-nCTC8_z9dEbxPZz6EdzIf_YmUzMK_HZlZhy5CbAlx_zgx3oKtGXWCmAjjalF-3np6BFFROXP7kLjZ9F_JK-z3ehXoKiVX_SZ9JW-whVx8
UFvP7N2z-hNxg7vZpblyo11-RFJ0X_8VUC3T-k56oX6eU7xJpn_kfu8lUjT-qFNBvf3m7iEFqeDnWPy_qe-z3dhFVhXdWXxsw_pr07JrOwT7vNKC_E7y2lyE
FtVtJqeFV0m_z5Znulbfnax_LZztzuFFd28Iot-y-AaQFuWVxmlScQFwf_nc1H5vfn_fxgVK_Inn_JFABuquzk-7NvfnwYVu6v6KQ_pStRzbtwlO_I8oY5-k
yCizqVslXw2RduWC_l1-yUQVKgxposDY-xz--MY_NE-NU7x30CJsSx_zxur-6TulF_DBmpz0_nlz8dLY-GqZuCxF7lrVFnlybW4OPFt_-WsFVaq3uCulN_z9
0lZPx6TdVh7wsP6Vctu9u9TcdFivbD_E5vPFyY-_xfTNyUe7t-vd7twEuxVp4Pz-1Z-Y7_hNSU6tyv7QlwqZ-e7NVBj_7jPVz8RuyAFsvbJ-PKG_G_z3_zhH
VxlzdnzuU-hsx-bl3y3nsypA3lsjn3u0Q7_2_VST_BTMj1_smuyO_E3lwqptTFEtehwqkrGUlvdXDzCe65R__dxzRPwdTRVvmL_cgQU_7OWKlXMBF_7xrHyE
0yZunn7aQV6RiVYzsG_BoxJqzX5uclpuQjKFzjiZhHG_9dyil-3avy9l7m0S_2Fw7wjFvCkFj8klcZ-C7xrFaqi_SeP7yQ7tv4TgVhxm4SNlvz_1louDlMi_
eXe_wLNnFVin17dM0n_4VzI-w0kU98e_J_hIzthUU_TdVQfyjWVne_IOzPNRiH-Lp_Z43-D7xHzMF8fKVxNUQxTlF-uqnt8Vo2zIz7Xq5yEF9S-mqtloboCk
5liWVbtwoktO3tnvS4E1_D1ZnIEYE7uvyDZgbTklNp-umRoFuCTwZy8lCVmuvfJIQxTxlp2hdJwENmJd74LtwST5eAXyBZtvyjlxdYY8NvzmQxTNVxa953jz
YYF_dtylFLOyciYD_sG0S0SiNhanFBJpuS_we_8fxlqelEvx3-xw-q_kt3jPfNeQqvz_IdufTer7tnzsSkXVTwxz9pizw7xyoxPBnI-Lpttlri_RFAS1O7tX
EVh-62I7Vjp_iEQRxvzt-XKxlJ-t_Wfql0SUBrZc1F1Fznj0ofUy5xrsU_NZlk-KtFPeVFV-4dgwwfVKKSzpC00f8_JzNm
}

!define D365_DYNAMICS365(_color)                                 SPRITE_PUT(                                    d365_Dynamics365, _color)
!define D365_DYNAMICS365(_color, _scale)                         SPRITE_PUT(                                    d365_Dynamics365, _color, _scale)
!define D365_DYNAMICS365(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 DYNAMICS365,         d365_Dynamics365, _color, _scale)
!define D365_DYNAMICS365(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 DYNAMICS365,         d365_Dynamics365, _color, _scale, _shape)
!define D365_DYNAMICS365(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 DYNAMICS365, _label, d365_Dynamics365, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 DYNAMICS365>> White
