sprite $d365_Dynamics365 [256x256/16z] {
xTK9aY8v38LXxrgu_trd53bhWof9K0Us7tz47U0pgLSf88XooGcsIdhxCoe9iSAt8ymdg7hxNoCdfDhjBcq9fd9xcDI44T-yk83-_4XhE6u_fpsddHD30Z-1
EcYKDRmz6nTelqK5sM_foCX-Irj6zblIeFqMLsY_HGNPRsdFqFvZ3P7zbZHelyK5sczHmVQhQi-mVZrQS0tZy4TIiVnw7nSOlpgD0k1NltNMC1flhRI6uVh5
rZ08xqTbBx_whRY6OVX5rp0OxoTphc64VkKr3C0llOO1-ANNC42_z1fUm4ScRG6_-cspXW7ufTSm0B_q6WRebrx30FpIQnYW3udhv_rw1FK4i-2FHlwGN_ts
NiC0_D9hwE1Xfa1dZIgqtnePsc_rZEotf47xBQxGVeiAjD_g6TblKKRsMntShvon_IeLsMyrSBzMSBzKRBzANiNFlRF6nsluEIUhYKRNLl1pigpSuozWVdzE
_wcGHZPczFj76du7agVtztHNu1tqwVp-HiNVWOYium-_0x7gedwhy7juQopW3ty1iOvuOR_Ltj5RY_jJbjVnLbdQR_4L_OR-HA_YhRg-Fz6BUAjju4zygj_R
d-G4lxk_dE1tzoToz2Z-vE1X_FqblUWk_kJWpzh6Ftoyd_8s_kph_PIsyIVny7wgOnz_byifzttyvJfVnqR-TDql7T6l8ghsfsChFps7rt-I7kMN6VpZYjuQ
ONwUmT_F-V-BUfY_p-1lb_JAFSwVv_VhBqaFz2UQtAzt_17gppFxrU47-bETp-_hbKSFzgSwgLyVH2FUdp9DvVVrF4Qu_wZ9H7uLVPJG65Qytyfz7h_tspl-
gFBudF_yftVyiHNIc4Ik-dqy3ylnXrSv02-l-1_ZQVoQuvzb3KKk-q-_-tF_96iercM__zrVy4-mXY81VkUx3_R7hw5OCVu3xnRWZrv3iMByuk33_F5hA1Bb
5wPntea_kjpb11_YDxpfP_DRURZuAB_GqOn-gv2ZZ_0BatNuQPnrtH-_XcA5-3lJ_vh7xw-XI9I_j47B-8yrVAQQdYcttlkTdoRsMsN8QUK9VEsM-Q--WFa_
Mg4JVqudbMvvVfhRRrKMFph1jtxa-cbolvMRU9Mpet_FFmx_j4_GarljrgdVcjllhw7IJqSVuXz1_lWrL9NX7xtZzvhKxw-XYd9r_zbjx3SXCLCltj5lxlSh
tGBrvzRxwtvQqUyV_NK_BUmt_Dj-MjHVkWNgput6XUZd5lFdIaGKm5_INmST8VfB9olOJsluSoCBr5_90lLNCmJulMRs7qUFwi-Dd2BzDAc_abEqdoRqbq4K
xVURotySFQZ_E7fOVnv4mFvAz0a_JUAl1EtFz2a_JU4VsFvCsFu6xXyVzDC4VaBtyxDTyJElukVVvcUcqxRrM_1-XlP__L__wHjixJz2zpEw_-jdSWFmM-I6
xV_w2S2FxhUG_FmeT3-3-Bz-uaiF0EDd43-xGVW9tCzkN__3zl8J_zJsVc9iFsFxYK_Qsq_yWf_syVDvE_lvcUY-JVpyZh-kxYT-iiV-ChcVO_ZMZdxcD_rf
PJynW3z0x_lRzFu8lFy0PKc_wMFyQK4_yQlT-TjoViF7-VFyVdBq4VwUvlUpWuzuW9m-b5o8wS2pd7Vj0LfQmN-en8hrZxI6_oZUdtVqozF-alRpMq_wQqBq
ixDzS_lZ7w2cRVtMcRyaM3yJzPI0_QEaxVqoiTwIppm0jPmIXb-SdnxLFsgo8Ft7Tm_hxoLPO7vXSRvx3Bz5XaVrinqzglyuUbJ_SVIWVch9mlHppod1-aT9
QuJnpyvlgdzsw_jxIMk5SVH-64VlXt7qVXX7xuTnz7u1Hu_gvvxJyc5yztu1tpsQdrgoGFqzfvt2E7g_WAE7y7DBMuPnz7u4SVH-7UBe_RB-4BUSTe_KoOuU
e2mFyQCaaAhSwQace8euHuzI7k8SFKgbiwZov4V_xTiV
}

!define D365_DYNAMICS365(_color)                                 SPRITE_PUT(                                    d365_Dynamics365, _color)
!define D365_DYNAMICS365(_color, _scale)                         SPRITE_PUT(                                    d365_Dynamics365, _color, _scale)
!define D365_DYNAMICS365(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 DYNAMICS365,         d365_Dynamics365, _color, _scale)
!define D365_DYNAMICS365(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 DYNAMICS365,         d365_Dynamics365, _color, _scale, _shape)
!define D365_DYNAMICS365(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 DYNAMICS365, _label, d365_Dynamics365, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 DYNAMICS365>> White
