sprite $d365_OpenText [256x256/16z] {
tDU7bI0X30DGm3R1Sl_jtctEaILvVWSIWdaJDeWn4JFB4sPEASPmSRUn9PVQL1MlwArMInQc5A-OdEKsDxvtsqCMlauBaQGqnIzfAqBHV_PS5J1qkLs2tmvY
akxihtUGN1vyKvXX1AtEhWBb1hk1ORHb2ZuaQR37z2Chg0ukGkIYiDU0KKlGmj71qNzep1QqdJi2AchV6L32eIy15TYJkHreeUFILzYlU6oWF_tu7MWXn-cV
mBmta0hiZ_eRI66pcDL6G1_DCUp4pGP1fyORfrzXGtcw14_Jtrw1IjpowjiKw51f_U73fZb_0gdQNFYjci8weZRRmH-2M60hu9To32jGisKwda7_s-zlGDdL
ziV_8McEhjxzyHieQV_L7--C3o6hRVE_l3DHT1IvrJ2bsYLu_yUzDucxwzYMiNyLwE1C_cJsEVHyGhjD8R1wzCfyibwgYxDW5X-ayrs0imD-aRFPMqcHAARI
v6mJbFFhtidqN6WPei8dUq49Nuql9SpEauAfXk_5bqP7bac-1l37xmbO9ZePu7hyDwkA0CyMlsg0C_6bqZdZnUzLWN8YVekdVPWaw-yO8Fi5VaYrjPg2Nnh8
NzJrSGclDmcS9zE0hEwjS1Alm8zjFooeoaakmF4GVkIpN5yJ8jOvxWATbdbHFwlcVVpeYCja6X0_0uJcq-oc3cN7mgUuG0sN5dvfg6lBR1fmgeBPBV3n90a6
WKSHY79-iniosty0a4CH2Dq_yB4qS3m8MhWY-5i40Xz86DJag06gO_3Zzz7LRzPJ6-4epe7_osc0oI7uyJoUkaVTq3eh1PHJ0v_QEGE37Ec5yczvFmE1xvS6
W2BewlsYfzmJJGbS38W09-_76pXSzfRuU0H4SMnsSSrFnWThG3jjoXMNXN7garcmGlZ9CrlXmYTZt009INvp-GgSSd7Xap4U0Zqu9R-Uh87ldLXdLm4aBitk
1QFqN0gi5pIxFXFLL0gCSacpkxfCnXDTO7Ex9wwhLDm3sfcrZujNuEDDHkOJ7Q1TqEnwDfb61qZ7MdDtTFjaB5eHkFsNDBku64y35WU85qovxYqnxW3uxNS8
VB_96Eu1eZXFkHUrn6W90FDN3HS4FjOILu4CK8zq_WNuJlXbQI131c2Q7_pgaIdNloKkK1RCqtD_2u-1lrsBhqjHG_XxcEnzX1xmcVzyVttRC4Fufm62wc02
YXyG_244efXoARNrxcaCl29bXB_EPJyEonjTQ0ofuMCSly-0nPxy5i0OkTJMViCOFNmcKHdG-f5F1C1nOpZnHm6smWtj_N3tnuqHb34EIo9Go5GFQ7J_3XBQ
ZL4R7pD3nZAv31LxyT-gxscHbQVn6zZ7xxK0SRNmKoqbfqWKGZZxyBmfV2RKbtUcu0Bnbr5Yjp_NOkxjPenuZZ52xdPyINWilmo0q8tyGzk_DQpHMwqbftJ4
626PBL1CkKnkwhhvmVcLTesHKMFCRv5xiF2h5aW16Vb1Ov3N4rSIZQsSRe7Q73-kZTDk_Jlwg7bUflZNfggV7tyBhqx5RhtVZZtFKV_pXfS-pOzOW8CQVNtu
jxMyF1_u5XstFqelKOMnhVGHeJ_uN06B8xykJrJwJXuhf9yzmgzTCuxpM06x9_ycSVRx_r4CfI-l1lxrFW44SUBN-A68PQaTnJ3rcVav0E4Fy2FuU5RdX8U0
q5q7P-KV2Q0uyajwIEcRjLWaiFJL5UGV-ka0cYD_ddcMa2DM1UgzdzZvrpgglnT_lNVbRSfh6h2E8LvHVfqzIDpuUr3uPWC4_jptjdM2NrQc4M8k_19r8hCR
806bJ_FZlqXPKLdv2u2FD3ROmjFEVqk0TNFYvm3KSS1vY5SjVYXzcXzFJzsBFmFh5SXy-KFfc-PlUFgty_UZZnAsD_QhAZqeVj3494xy2UfXx5VGfM-UdzIr
J-FlGHKmgvXs742YMXE0_FewsOa_d_0iNTt904MrXueVBZ9bS-7dWErMWVb6NQIfmgBuSQBgmr_Hv6U_2fFg3HK_VltcmYzHvQT91z0PK7L6y_mDgyrsVWxd
F4TUz9skQcq_pzz3O1V-YktMy2hIDjNtafp1Boxy2UjyyQzSP5tw-dgOdmEvy0kuYyP_JP81gIyzpqznYXztswFy_J41D3LI7kANc5pu6z3xOPA71C2a-jvZ
_2cj7lm53Nyy0TJjeVIrzHp-xCAVyKo9NqgNlkFyUOO_mTrFMG5XNxf9QkNpnVm4DByWV_kBh4hVD_EZwHyl02Igz7qjFmUy-qElHMhbSns_WF_DuJZ_Dcof
LZx_O_ogz7q__t82VzSdartFxv3_KFueNyZlN_zKwRkMN_RarlyCYmByk4xbNySV7VfVLVhEkV_m_2Ton_zM3lEFAdrdyIU8_uQ5yekizUpv5yYdS_nHC7WH
mVd1_GUU_W6oEVv8x_b7MDlucNuIW1oAWOAKldb-2ep0twWooYzol_yKaMFX3mJJzFuJULhApd-t_nxUCwKEbBvZ--yEqCFy-l6YB4C7tJ-l7lnB0-Zj_19_
d1Qm0F2yDSbsFdzJNgNe9_b701JT7kAgTttl1j__pNBzWj3R-JcCbaMcBI04bRvv_gA66NaZ2xzavG1_DHFzKLpuqzELHL1-F0E6hYvh_WPOuCs3N-Aoa23q
Tdv9Y_hNSGFe3_fT-Ec-gn0vvVxhHyohmeSiK7Nfm_bn1slgvcFyk0E49gA5VtcQn8c_3TzIDn_Wnns0M2mke3_eT-Almxa44Col7x6ERFK0IN3fc-VFOvkp
Ul3NPIYnO2wWyPEuy0yN8mRWf_WvFXb02th-mOsVL7q6-UqEi4I30HXu_WNW1pDiTUDdUZoi5hH0Lyy_-V3NCQ8wyEjJHaA5320r00y00lpe3qGdVdtEKkgV
3S09s7Y1_5Y53Up6BqKTqocYjNUoQUJLaP_3I35U_FgaENff0VLIR8NlmD_qX3hFZxzq8-Js4bzw9dK6X2T_6NPsvEzXqOgvyN-e_w8BjnB1Dw_Y_723pGxy
oW7K-HUbjluljLfo3F2Ra75-_3Ipvi0FldD2_LDrbgqNVrk6iYE_fCMiK6Hrvy_B4B4ZVtCu0GhZnuyoxHxyUX46kKBgilhowyFyYWE_Te38BOLFPryfUYV-
yjXf2A2Y_ctZ65pbxfmVhH0hc-drkhJOJyqAtS9FB2RLHpFtaaZNEqgrO_3ubwxmGzEAYQF9d0EC7-HUo-q0nTlHgANssvq7B81zwH1tVzobXytIZ0FepC4t
YSZT0d8z6lw1RTaVlwKSdoPvbfiO68FXN-Reat9nwYZNREfbG_jpztxk8pO69t4oG2VJnaXrvOG7m1ZaMKb4-Aq312S7KETVewV63LKa0ExC5XiBlz9x1yYV
yUNGQn3ov47UoJhCXDHvHwBKoL9fZvr_ZnT_Oml0BFLnJEc2MY2R4WqElqdLtv34Yp-U0VccnyH1bNUr-tM04oDWUtuDJa5BfHRr3_JQ0BSqi2jl1zZq-q_m
SqMq2a3FhD_vrY4Bz03OsSOlwlqtvbFPa1B8JwhnULi1MI0PUkrL75y_9xIyLWNeXmkWQO3L-wUnySdXpT1wyVLn2E3NwkgTn6sVd_zS2dA08O-Nh8_YXpe0
xwh51Ku3OmzYSW2lTostPO4TWD-ealfaPrTF3b11VloLuDlCSU5QTGSU2uBu8GrKsxe9V_tSPZjL3NG0_gYM5ZmDF2x201dVVuhVViW165A5qu3O7G0B_Crw
g1xa08ogm6a0tOCC0Uy_1kYXsZzK53wG1i2MU3W0ka4x_rtBTVaWwZ2-FGs0Uv2XsVUVuvs_LcOKtvu6q4NOa0hyWwzSBSj7XIPiLo-4jCHg3uBn2zhiskT-
hSJ2cEnfG2t240C8yB9VJ6b1L05-80syN93XUv0n1d86cbsmza6YpfEgz7aoDkr1NZUxas9QC6MULTUJyH47G08VLrv0XShJQkdJP9pHCLW5Fb3p0EztYG1y
CfQ6BiBmjxpZZRz312Zr3oqnk0UfgjcLm-T8-4K0FXbZYx0MuMONztxF2C1ROc0FqXFQxEAvtwR4eEmjyVqNWh30Zu3hOvqFhiAWx6dWmnwa4bZpSDN5hD0O
axqblj-3087FPxqSs3a5u2tnlWCeao7V1iIN7luf0FYmI9G3U0I-VfZCEmNWa_7E8gpgPXSyF0KV-bsx03mD5Bq8qyqkoqshG-LtoO5uIzpk5c6xWVzN3hdF
AGVY7nRHmoACYsvsV-JG-A2AxmtGRy8dOwtGHVj7ORcJmzG3A-t2FM03DXWzhUgCLU1tUP1_whTNmSxSxyJC7Ki3MhhcFSjXwCELtzCF0HPGOQv5bHMzkEFR
3V1ACxKGUZxKe_3Z2kM9WVk-p2snhdbQJlYu0N3yRcs9TU1hUU7Z1W3mSGDm8IZmXwx4rmRu86jBh6kUrcNuUdlJ0Nv0xTu2z4YlvOQFAtV0--48OE5USwH_
AURA7-Z5k_3XdM3_B0ObylUFSYw_eFXs0tH0Z5f0O7aslRXYuuw8KRdmSroyHFLS1s07_awBdqBvTluM5a-5V4a0m8-3bCLRgPt8pwVoRv8MVr7z_GhW4FeE
CN0f_pQUWVHNQj_7psdvFL7vDlv6osygf7OfFzxn-gV1w_dLOlK25xYEd_DoZQXyG_slj5ocMA_k_tfQhbJ8xSh-dqjOBXRbTXM_8AxlBohkypz0VwLYKRVV
crzKpRlO0fxPNnpe7IpWS_irlrI0_ffCo4Dk_i-5bYzLIBKRyN5-TKZiDoh4qlpI7zSObcyNfTez-AKvtFfBCu61Nhf3rBl6GVxe1IYzSCiUVkyV2ANrm_nS
VTtUtmtwD7vtkF5NsA2qRkNdNl_hsVLntm0zSsybHrh-UGeKKowrjQUG4FwtRYUXfqXX-OVhTkPhoaCfHQ9m2VV_0m
}

!define D365_OPENTEXT(_color)                                 SPRITE_PUT(                                 d365_OpenText, _color)
!define D365_OPENTEXT(_color, _scale)                         SPRITE_PUT(                                 d365_OpenText, _color, _scale)
!define D365_OPENTEXT(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 OPENTEXT,         d365_OpenText, _color, _scale)
!define D365_OPENTEXT(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 OPENTEXT,         d365_OpenText, _color, _scale, _shape)
!define D365_OPENTEXT(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 OPENTEXT, _label, d365_OpenText, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 OPENTEXT>> White
