sprite $d365_PowerVirtualAgents [256x256/16z] {
xDE5WHqn303H5HX3_NSR_p23jG6TPpfuWbSx4H4HNRd3Zpz8b-jDagax_M_acYmHkSl_mDlAysHcgY8t-VMDlIJgpGXK9Ev_mr_uTBc_6K04htg9FFWbPUwg
4bn-NlxAJJNgLylhBsuMztl9wtSF-zrBui9-yv8w_FZnuyUF7pz-_FZnuyUF7pz-_FZnuyUF7pz-_FZnuyT_uSUlLextryp5_A9Uw-7-bhgelvpjnzzM_K2_
YBptzvFz_7-cyEF7Zny_VlpuyL_laj_jagVXZxJyxM2_Y6NtBuJAxwMVvFdzrmDavXkLKkjJy2_8Rplw-xBx5t_f-_ZTvgEHVG0Yvj_IprzhZEH-NVo-k5iz
cpEx_mr_3x_Axo-rZRbPUl-R-j7-tiVH_X7Wv_VZtt3ZnuyVFtxy-F7ti_sv2_7npp5EzZ-ROsS0u_yfx4yOVlpuyUF77-0VviUF7pz-_FZnFyEF7p_-XE77
Zny_VlpxVFpuyK_yISEFl_U0F_y0Ucid-tkhDU1FFu1UYy_u0FAklvX6-Si_PqvzNNo9-v_DLJPyNtnV_2lW3qvWtkpvlMfvmx_5lvhRtO5ljPRVojti3N_N
Fv_TrEloxaCtRXW80YZ5pgK1___VXhm8arwafJ17xA07BMzsv6wVo09-YaDpBSVCa_wF_yc2Dv_rdFALEEJpoVl_TmCwFhPy8mh_bNpyfHHT0JN7SNiV2FVN
PSq2Qad3xuRfyrw4LS2Q1PJvxBkPhVo8je0o-Dv5jzlzaVkF09v-FmBFDdv4iu2QppTy6_ix5d3FxqX-TW7mEufV-iAW08gVtm0ACEj70IRzQ434j1y56F0h
FWvW-_aBuFlv1V3tBvtu2Eplro-0x-SjWE-N1_memC3RF_q2-FSdB83h1nnwHW5ylppdHm7lVV_U2GNG_LqrVNq1VB_8ytuKy7v-XB00hX_B9nN0zolkhtW4
c7xzwVK5iFquFRC0_lqxmOy2QFxUCNrY0Kp_sGAt08uVRfeV1R3k_pO52DFFB-0Xlm9EBk3v-x-D7u_0Uhy2JoXWlVy6dU770jRxzsW01IpsA-oC1Iptg_3y
Hs3z_JSgGAGLxS-_AU3a0cIcHBqVsQI0BlZ_wlqAFCUF1de__Kxb1tsZ0X0RVXI0dFyq_C6Q7rdZRmt-xGheydh_FtFRNskJlca1NMhoJkVFfMxx0FHMejOV
KscocnvFVmfQlm-fDjcmWTwbvk2zyla_VCW_lmHito5o_khZoASYRXIGxhm2D5rVKiJn5VvPGCpbyglohAb0HFNN6zm2_omWn3IJBsG-D2kkc6ybnGY-sZ_Z
BsKMbjK5I3j_UTk7Q_4Znw7o8-xCSIslXwQ9RlebpIlUYLFJuR-LOzuigGfeDG-zX-Lou6VSVzvDLO2ytdtD9adtrxVcOwxjflxaQn5SVuYvYURws_h70gFp
FgGg2Zxy6-Rhkw1OxlZRlkD7ZXduBOqVVkUEK4J1XzwE7toRVl3D-VdZv_l1j-a7tvoVFtw-7tnpVlxr-NxmRVh1D-VdZv_l1z-c7tnpVlxu-NxmpVdvr-Vx
mRVf1z-Sdpz-lXzyctxmpVdvu-VxmJVdvr-VxmVVfXzyStx--Fb-y2tuBOuV_bZamlXD-C6tvETVd-_dNv__zWzyEtxc-Fd-tCJK-949dFugziOFl_EfDB4r
VlWn0Dxu-NuVSnLvwPkDwyEF0afjClG5V1j-591A7Ic9ywQF_oOWvLBdzSE6u_y2
}

!define D365_POWERVIRTUALAGENTS(_color)                                 SPRITE_PUT(                                           d365_PowerVirtualAgents, _color)
!define D365_POWERVIRTUALAGENTS(_color, _scale)                         SPRITE_PUT(                                           d365_PowerVirtualAgents, _color, _scale)
!define D365_POWERVIRTUALAGENTS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERVIRTUALAGENTS,         d365_PowerVirtualAgents, _color, _scale)
!define D365_POWERVIRTUALAGENTS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERVIRTUALAGENTS,         d365_PowerVirtualAgents, _color, _scale, _shape)
!define D365_POWERVIRTUALAGENTS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERVIRTUALAGENTS, _label, d365_PowerVirtualAgents, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERVIRTUALAGENTS>> White
