sprite $d365_PowerAutomate [96x96/16z] {
xTG7UkGW44HXSbSZxd_TpLcVA51jigrtWB_j6Mh2d-pfwIdUB_2IUR-RjyJuxCVz7COEGE7Dw85-d-ym65gS-hVryOata0FGU3EWpWualySVC7ojJXzGLtcW
a0CY3viUA7sRTyDFMGwJQfTuVg3jw6CuJf6TsGxVWTq34IfFTXOXyVn0yZN-m4LyPohF3t3UCKtOsM0yFr09FoYFbiZEHBwMI7PsgOyEbjLIfWUYgJmxWBE-
oPSSsCxE-ZWMUNwW3uNd1t8VF-bh3n-jbCK3vHW_uH_Qv4kPpg3-PAy-_Aq3AbyB6V97T-TbdWwG8U_ovyZETlXp_82lF_ohoCxMUDJhoCxMTbKdiPs9F7cb
HUFv9mIMLS7F9l3yyqawN_C_usFJ-H857atWGttHVD7vcXJU53v3v_EhtPM1nNSLf5szxjbMmZ-xUgMpTP2QiYl2oxiYl6kxQkw45tT5U75Nb3ULzrdgR7sU
-F3X96lQhaZIhaBxito0paV15tR5FX-Tvz-l4RpL54YfcVQJoOjNXV-vfwUdzm
}

!define D365_POWERAUTOMATE(_color)                                 SPRITE_PUT(                                      d365_PowerAutomate, _color)
!define D365_POWERAUTOMATE(_color, _scale)                         SPRITE_PUT(                                      d365_PowerAutomate, _color, _scale)
!define D365_POWERAUTOMATE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERAUTOMATE,         d365_PowerAutomate, _color, _scale)
!define D365_POWERAUTOMATE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERAUTOMATE,         d365_PowerAutomate, _color, _scale, _shape)
!define D365_POWERAUTOMATE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERAUTOMATE, _label, d365_PowerAutomate, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERAUTOMATE>> White
