sprite $d365_PowerAutomate [256x256/16z] {
xPpfbhCu34IHRBOqv_Jxl-qqPEvip9B4vM1DNF-_vPQCLKZTVFylrTNLrTNLrTNLrTNLrTNLrTNLrTNLDVmgQrd3WFJyeQJdx_oSVczMDP-00zvJok_G-99o
JkvMZTyivN6QvwLPpTEOtQmEltaQfsLPR-rgNQOn9wjo17Ry-Kx_rQPs_datmAq2_uw_mjuc__h3Fy_JY05I2_AEtoWv_CSTC4-S02d_D2yHy0y3ncIcvjzl
lkRnz-Oq7oT0_WIihUElT_p3XRqBYFcvznl6NtPyxW1r4_WAKNtuvp6xVGJ_TiO_3W06V03_xNO__8Wcu6RczYC5VykvZ-gV310SWQRl_ssZyy5VxH6OM-p_
u9z53fAz3OuJ-RV5wf_nIS8g_fIdvNPh4H_zWm7m2zx_sZ9Wu-h_DmDayv1Z-BFS6gBVY7t_PW3Z005_IhcTAs3ZzF-xQ0A3MQ45xdOVWOJ0ruy4XnzPAmPi
Fte4dnmauXyyZSI0vgkFCE2kCdxpD5rkmFOKFYT0mZ-Oxp4WmE5Nvg2p0RSerSS0mJnekFe4W4_ZVzO0K_1ZG13yqq1CO86HWwx3lwqlRGP5_9V5WEqG-AyR
KBG3lom7WV_rB3wl0adr29240-6JWpJy5-IWxMLyL9Y3K44JqE33Ns20AWS5mKVa847z3GC2uPE3RF2XQ2bWPaSJm83wz8yr_iTV1U0lQm9vUiSTk0cgZnY8
MMdzFHavw3tuv1w10SvMeF0HCCyOK9kUpbSkzc8IVd9G17oasekvkvddcZbea-Dp0WGZKTlbD84tL5_0hyn1xZuCxeaOK94UVBa1Lde9a8DgyjFuXHBCWsg-
2e2FDDK_vw1YVWoW2LIy-iMIZaJfWWrV_VhLCFmO8AMlZKyG74IF07knAFWq0TL8-30W3Bx-2XWygPh0zYPyKW3Ip8FqrQzMVdvNHBaNYuN_mvzCinJ000ax
gei_ZJddvARTYsdmANzL_35ZW8RVd1mK1Xy313cWC0TjL-1ZW7OlrYm-0Xy3NCLljk_5siRdwaSOWDx-CWpyUplVdwJCGVSWk3MDV-8Nv20pSsSUz28yUZC-
1Y31NgnX_EcCpvS39FpinRRNyM_lnHVa86J6Nkm1-8RmCK2t5pi8Ny7_kW8V0tHxiTj3_DVa7gJiWiWFvIC7RG-GNzdvz8y0Uy6Kf_csipvfm7Nu623Wpobv
8WUTmPl3Fpy2ghtOJlmK_kqw_74a1odtOZXmuhy-zvo50TAzs9cplQkV4o2S1s70YV-gtFCGFmOezsBNLn_y1_YLyo0CQ0X__4z9fm5t0ox4v-f_Y3_dKVq8
C0wvkl4_SFonfyeyw6hyHntW4L3lnIxDFS_pPtaEkhBpFIVz8t3CWwwx-fyMILZ2R-p5mk1ZW8cs0iI0QzxuNvHsBuO10V3bESW6Cpkwu1MTJsL0SHFO9u9X
y7KnWAM0fv4J40CV0-3Np8C2uHC39Fp3u0a3tZRl4HaWulUKQGBlQ_ogHy2-o-JEzuD2u9zZG36_cQNCD836tpO-1hWf-DEVcq3jWOVG0FYBP8SmeFhLBpO0
ViLFoj_2u6E0kwduFUqlmxKxdrOvkKlu6OUibGSUSlwauSU0EKxr6GQ08Ra2fgMMm6-QFqznyE7NmCC_1xZwnVmXyVNtdtaiVFgVWfv1K82hNvr_Ok7hyo_u
AGu-ahp_W5-jzLV4L_2RsHr_ZeJFwOU_U0GSx-fd_YNWJpaclcR-7RRwalsFkKUjleJVKuxP-U0lt7zI_Gfw2_vGLFsGkKVu8o2U0-GU_VfxE1GuzmmA_g2T
Jt3u0-8ZtU6tuDKlVkFDiQilcFQ5VEENy8VDFQhJ7ppr3e9XPyyzKV4l67R6ppq3OjWPh_C1ByWz0KVzy7_GbXFrt2Cu_Jtt1CNdcz1MnXy_znIE-kFYQxv_
53VtQFZp6FoLj-pxPoaWldBOcOFYIpgVV_2y9-oUAxjf-3qaVafMVlhxlETJSq-VzvZLFlpLogyUTgwnyAM7_nDpJzzpxR8-xmc5hzzpXUnysc7d6c_KNrZy
lkUgZpyrlUS2Nt_wr-hu4du3V_tCUS-nvHJZyzUrcNgHxG9_2Oe_b7xdFLFzM7kkGSCF_ggjVkN6xufHVp8ZzuZvQ-CdaupwsNCTzAkAVLTbV9SEE-7N6H1X
tcDcL1zqOVMN47kkSUBPb_A7o3tWQ_dVMlq2UdBF2h_wy4-jLv_63xwAlpQ-QDIVCjKNrh_wrU-csdE1hrJzngyTTah1rtTS_SfXvrf1OVPSL5-h27kk-FX3
4Vv0xf6hwNaF_EGUjUetVWa_dswBrVbqdp6t5Adne-o5etxupIFY5-OU17xGgzzA-SFddkyoqVZZNVqQ_bGHl-NgepnE8Qi_YFYdcBbdKF7FiQv-y6NyIxpE
voRaZuUVm9Vmhv5VUGLQAk47UFXv_Z-oyw4P0pwiyw5fdfTG-6B-SPoMzl6dILrzb7Zx4zvzTmCcgTJLHwpyGiI-2lnckm6QMt1v4_wtKFnYzzpoJtRcB3_y
Y8_OofxI6ah9rNqVyHtN7-LIfHzv5Pc1h-S_PEqAzahyiVIjLkT7Lgv6-Bkwkhgwkhgwkhgwkhgwkhgwkhgwkhf-0G
}

!define D365_POWERAUTOMATE(_color)                                 SPRITE_PUT(                                      d365_PowerAutomate, _color)
!define D365_POWERAUTOMATE(_color, _scale)                         SPRITE_PUT(                                      d365_PowerAutomate, _color, _scale)
!define D365_POWERAUTOMATE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERAUTOMATE,         d365_PowerAutomate, _color, _scale)
!define D365_POWERAUTOMATE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERAUTOMATE,         d365_PowerAutomate, _color, _scale, _shape)
!define D365_POWERAUTOMATE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERAUTOMATE, _label, d365_PowerAutomate, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERAUTOMATE>> White
