sprite $d365_PowerPlatform [96x96/16z] {
xTW70Xen34HHIPObs-7-rqrFXc8GO2jrtm66Jzj6Vm1-5hsZcBkt6tsYMHLwaSx6nhKFFunMw1KohxtT1nU2I6tFziCe6_En3qEJyl4EKlAXSqe-M4e-37ar
7yBvBsmfFtw1mN7-6nyFb9Hyg67-qlx9rlBZ_RnyxCVvMVjrvUE9lr_n83_SBxdvWwFyBzwRZuyFkfmlAmVcEDyfw5-PZuy-RFrwFXwFyu6hjojzvix1kMox
B9JgLoznGluUOWFZfnFojv7sVVlh-bZ9vodnx_tZYo2VYwhMhyp0pxKhVK2GNrGnRPFDwBXHmlc5_IXVz6BVW_rNyrcF_2j7_f5_v1_vNLRouttBpM-ScjzB
QdvNIib7VMQ-otDNFCY7SBvx8Ghp9-aDvjTKlJSt5OgmMaFFX3EjF58jRJpKXLPmkplyrJ1QKljZRJK_sA-qHCFyp8-d8N_dVWEXDJeR1kGlVB_jBXTQLMVp
o5ycBIKVQae-I4u-r9Hy44_9Xnhavxm1PwAiD-2VAL7A6_3laB_l3JWeRIIESUHlLB6E_8t4FICVD2KVsCyPqswQaW-Sam-QaWziAVcWo4_1XlmKYlmKRCXF
8UPkGdcu5DGVFW4
}

!define D365_POWERPLATFORM(_color)                                 SPRITE_PUT(                                      d365_PowerPlatform, _color)
!define D365_POWERPLATFORM(_color, _scale)                         SPRITE_PUT(                                      d365_PowerPlatform, _color, _scale)
!define D365_POWERPLATFORM(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERPLATFORM,         d365_PowerPlatform, _color, _scale)
!define D365_POWERPLATFORM(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERPLATFORM,         d365_PowerPlatform, _color, _scale, _shape)
!define D365_POWERPLATFORM(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERPLATFORM, _label, d365_PowerPlatform, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERPLATFORM>> White
