sprite $d365_PowerApps [256x256/16z] {
xPq9Kkj04WLxgUfLzx_kh1K4yVMXFCATRZJE6sI2_OfLOIblthnvyoPboIbyJynP9ESOxaOiVVoRNhz944KDkLc1tCS79Nn1ra_aS2DaVAOv-bG0NjzeZlxD
0gJn9oMSI7eYXLiGnnbrzEyKe8-_87yqqhyIRwXl94V_BW7Q-8BewDyZG1bV4ZxGRmY_6XrVquCXUjS0ChwZFQAlSfVXFrDD_wO1ul1GqxzdW3vS9Ei3vBlg
Zwfwrm3jgluzBk4oV9hgNGFeDVsx788oVBhgNGEa2_et2X2lwFlSQldq0ZVIBte1kSNmc_vT0vGB-ZSAe8lqZNo3uQ-gTmsG5kW30S3Xdqr_I0hRqW5zrVYB
zRlgRGCqG7_Z08NGDtxfyAlUDe2il7lsFmGJeBznW0ZexnoWa_f6_bNwLHK8iEtmc_uj0nJWwjtuIm45z3S-10Ku-pOEa03zZGD4MF_CzikdYzd-xhblW0Re
Rtm95q1_um0Aw6ySGB2ZtoVlEFoZAqRUyLlzHJdIVilNbIJkfZ-RtZP06pwpAaiaXzzd5eNXXdzFVsM7t__yn-66tsSsnH5i-7tcq3i668yoPxbXWFu_-7VM
_D-ePchuVV_PK7iZKyFl-y-AsXk96dxVVnPKtqZKyFl-iw3wHWI6tsLI0UHCf8RV3p0AgczGm-_xpm7e0m7wLVyvM7q36tu_G4VrZGmClyDS7q2O03ekCOsZ
BTD70iYunbmSG0G9aCPLvWTrYJuI8Fv0VsK0yKdOyFC1H9W0VJmfG47rZKWDl-y_2wflH63u-G3oEDZm-_wZeFe6DVn-W6Em-WOv_7u0tb-muVS3T5JVoD3m
-_xpQAY-aO7XfmA8C07QME8_ZmhgNmzGnzWnW5mbKSFl1vWLrJSIDln-W8Bg6n4QVj__c0NLDo8t_7u0LD_0XjyFC0ggRt33xmTWzGra-7r_2y3x2pRyVe2E
wXiP6tu_GCFr_G0oneu1H9W0QK3-5W3LzmF4WVhFevBw_YKy5dFodvNJzmFqmGSegBuHBmy_7q1M42yEFnz0rd1b-Fa0HMKLpl2J0KRvktmfgh8CP_ZH07gc
cFuwdE4dpu1-jlytfWy460viW8BeItQ6dmjm7EraR_f4W3fWvjS12g9l96Vvo01LpTuG0kUzZ_At0EKJAWGvX51Uxsztq6U48JeVVZB083_yHWvv6_-ZyluI
ojWcG2yV24Ne-_XF_iCliOzz0l3-aiP6_dK3VunDFlx_xv__RH__MJuGYbZ6DW5Uidzv7_-Nt3zn6__-alitb5tyosU48OGGD_6lvJLV_mRTIzyGWdZw_XU6
emz-_ok4_dB_LauWt_yqTj3d0uGFue0vBnyV87mY3HP7tr10tv3NwO_o9Ghe6xg1FXWWXZ-ffB-lRoYWRxIzFle6eK-U0UUZ7_y4q1J-3gzVYy-gi-zCt56_
AA1l95Q_bS87oE4RP2zzGm5zGrbzFa1mgEJHpmS8BWsmDtq-G7Y0lbhUxXuwWAhfUp3wR03z5nB3GqH2dmoWQleFaW1zBC2LVv0lY-oDMgW0Ln-HeGliNNsV
Q_9dVP-wnjxqWG0_VK9CMwNVoW_GH-KzVPyEw2y9yApd0ssexmTuud_5ZmlqUoaB0ppveG1f8tq_m89d8iYJzKTv2kh8E_h86R16tz27tFshrwSo-jS3g2xI
DngWVpa0yLIi3fnzbm9GpyNRJT-Wz4FSJT_07WkPWBFl2XVqYJE0qY-0lg6RwHlSex3gZ_HxMOIhpp__0j8t07sZNzOVPI60lZ4UWjCtdAltUSJTz0tiMR1f
-A3wXg-FdG74sNS6UnYsElAulh5UtwWNZdu2x5dmxSBPHx1Ut-WNXfzCK2IivS9FEKaaB2PUM7uE3Sj9Z_gtk-aRGau_h--Zk_h7m53tz8-1ektuzXy3Ht_e
PvqeAP2SxCyCM1ybElBstqmmSe19ZZtx2I01HyPqE1gepwFJuwZWtSDJNV-ZWleypGqmAwZFq_q0f3xFU7s065v8d7u0K9ydkVx70FLvvAK1KdWvwleV7TJd
gIyBaCCMD3z00_Lv-ai2IDY6uGUed3vFd7W03JkHVV-ZSleyuWUOpmmGTgCy400y-tYgwtzCK9-d-G46gC_JeG0fx4aSVe3EwVF42GJ8OL_o-W0vx8pu_aVZ
hbwUiY00e8-U0KVbhbwUjY00e8-U0RC2H__EPy04phwjpu39wVDat_yOd3wF-Fx7uAvUdl90WCxfyzJd1iZXjz4k103qEVe30HfszVB4uGTGmVHvekjVGb3i
wkN9Je0M_eK2-dkU0Js4Hm841FuC6E6_HE3is_4CYC68WFv-Pq0A7qH0VxSp88TF9E3gtMi59GGd0AZF1oYdgGIktdtEW1fEPEpiuv7py9yHJ9z7VVqG1DFd
aN7wv3yZc3vFB5QWvV0bIOkXCToE92hPovH5LJ9W_-RDcpTl_Wa
}

!define D365_POWERAPPS(_color)                                 SPRITE_PUT(                                  d365_PowerApps, _color)
!define D365_POWERAPPS(_color, _scale)                         SPRITE_PUT(                                  d365_PowerApps, _color, _scale)
!define D365_POWERAPPS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERAPPS,         d365_PowerApps, _color, _scale)
!define D365_POWERAPPS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERAPPS,         d365_PowerApps, _color, _scale, _shape)
!define D365_POWERAPPS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERAPPS, _label, d365_PowerApps, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERAPPS>> White
