sprite $d365_PowerApps [256x256/16z] {
x9S7TWCn24IrI0BIxt_RUFRX1JVI2tx-wJr_61M_5A0qxPJyMvoRVt5k_ii6xV2FpielnXL5OEwz3z0xqKN_DI9y1uK4giiJhVgJMNRm7Eidy1BjmHOIKWeL
gEtVO3-cYEhTdQhmG0MQ-_lmOJzt806lG6r_6xxedQ6eG5W11_hJE0YWyl0R_0VhtVsUEvMvoba5WluCX01AdtlmWhw31kpNj_kxVWZW6kPFWyNqOmDi_d6B
SBm1zaq5sMhDUcV-eG43RiRY-YS1s7VLRV-OulenW4v-xfd-cG2eflzgXLTzYfh-QGFMsSUT_-8Ig1Q13JRgNrW2cRwV0ZNzSV17_SYTJ6j0eZz7nLEW6Nxm
dm-0Exb-6a2j17Bzs81EP7jV4W1HiKCWwiC_2M3q7lNp1bIR_XJO9oZFWVBdZ71NA3Hzs_epL7Zc-3MWc3_qa_8d_jafY5Sb_FtWJxWB_ZcL7WrZk_wyVl5x
416r1NiwVvk-1z2C_-s_OEV_d7xz1i2VwBMzCr5I70U2w1Wi7qt___Skml22tW3IuKYdF4VjVSwyr9KgbMHJwrlo8Vbynxalg_3X_rE6G5S5w6gkruz__At0
bVqwz-5xxFZqW8DAWEtpuyD_v27GTUpu1Vuiy7_3hG1vp5wtFbF_XX3dGgqxlyNtQ04Eo-_4rm8S1vvK_sZ0zoq2-Ht_R9twjG27e6V77sXz120EbUeFu2F0
iVZFlS7t68T0FjKVmqU0zlm1_4FlXi7Vm_Lg0QYYQN_8RNQzEXxdGaqLw6gmy6VmwG2jpuKUnOhWcrS-lHkkwjz4QCL_h-sRliBuxUjZuEyplaVNn-I7_bAv
arhvz6uupn_3rmAqcVgRuBVtGTIjbII-xW5vtnF4Rzy3WA-Qi-LjYey0Dn7o5HvHqwytW_dYFkrwWm8ajxn1twC5o9mAm1zO-VpdGlbKVm0_L286FFY1PAyX
8vXAzUVvypxebqZrH_dpIN7urwJwBu7Xdnu20b_mHmLebko5Fz3_WqE07I_uSVxsG-1K0tpDFmVuCqE0qiQpg6xBJ03v-XZuyJqh-B_ykxzyXHX3_zoJwbyd
m2Kw0_IFC1S7m5zj3xvd7Jy21F4v5dBpKzgvbXy1elW_1N3UupzHtBUE7m6I-0X0x5NSf_aH88RF5E0S0jpZ1tyzFwjW2jy_12Zk0tybFmACuv355w-7s5Bz
cfyUaCNlNVcW6xhOyIi1y451V7f0_MtNLB_clv083UBt50SO-C5lBu36XvyXOCZtYBbFyEyWm23mgm1Y4hGLzsb-lm3WhnF0d-_92w3ntzk0NLFzcXy10lok
8S3K3xv1W20-Dg3Rpi_27n30WUzqmkIw9sZQ2g3nJKwOV1U-ny2F005yuOHDz_ZN2-3Q2WpN07zjg9IeliTl4C2o6HpWXyq_1E0NfPtX7W2_m1S2RBZ7xnQW
se1X2xh0tp84z3r-2x_31u4F_qv3W7lyu1luXG0QNWn-6UkJugB2Omk_540tlC0t-g2k4pl-j035WFz30CCz_em0musz6F3rkP1EzUS560Y1Rne2y8CV4q0h
i07__R78fnql-3lo8u0UyfRMr-T2yBFoDHMWW2rQt-Q3AExhmT-9Nsy6cVIy-0YmnClMPyU_gm0SYmmVLpinzLjxW2Zksqk0prRt3Rv7W7UfVi7X6m9C0J_1
XqBNz-BZX0cHwe_CWSEBdk_j_7eheF3z_Eo6DJ_uVW64xyai0WiYhD0BV8S0prj-KlrD183VtVhwN8Xx_0Nyi03mYtoFKm2-Ay0zVl1p_0XmTpoWk_3rkP2u
nnyJe1GMVR7dCm-1npr-y5i9GEixyNLvYBZ7lpS_0WZytGGGz_X30bHWDVZzSm3t-C4FyoF0EC8TmAS7YEA-M0TW3iZX8q37mj-8dytWS-oDZn4KTTt1EJ26
3t-zDyxKtrw0PEzd11HSVv1V2G3-_W8CuzIO7m5Qy9ycy9loamzQy5Fyv_Cymzzw1C0FVa00y1lpVoypG9m_1ApRFyjFVBK9qVv_FF_VtVwNu_3Fyo4Q7mUK
d__d1lnVRzO_-4kAVvgQyRytm47_W_zjmj_U_xRP_tp9_K_9y7U7tFyEkVrlpN-qvWS_s07Ama_-Ane2Fo00ZuMG_sp33pxy2G5A8Vz9_hivVb00yCNvHmX_
XZvm_bEkmH6WEFyAjJw3VtS1uES8cFFFkH4-XpyX0Gg3_yR_EFyUngaHFgs_Zm1G4zoC5VKFBV7zSo3up7tmrz70O-OPU8sF0Cwc1_yHF-gVzXP0u0i1BFZu
7b7_5hHzEmlmglNRr3yAVAS0KB_k_8Rwrmm-0fWK0Fy5F_VT0nbFNAzT0E0r_Y_nte6vyJM-z07RmP_mrVs7EOHFx_VsWF8sA7fwpTzn_oM0p-3t2L14Y7km
p87ue02-JO0YySKLG77_hJ6-5a3oVsnzlmy2te2F089QTlxrzry3rNuU0NhZqy3SVoxZ5AXqCWWWg5TtVW8RC3dGVVW88D2bxrd__i4E_E0R1DY23xz-_u8v
CDlwcb-7Dltw_HEUElUtFlm60Qoj3p-F8AJnTRXQNxz_n5LWP-UdzsS4mFPjVV_AoS_2dr50-nxz_jd6AK3Wf_Yrxz7ltyq6T1C-iG5_-_k7iuCVV4_uV8z-
_tAQ3V3WcsBdpW__mmTTjk8Ju7jYjzONAU7M-8JHz-ZtZzT-yYQ0Jwp4Txn_FKxp5KtX2zCFVqY0pHy1s7GeiEWJmITMjFwMzdzxA73PRFfdyAsnplMQldS9
ly0NcVwG04zF73Y-Vo4smyBqq_hs4Bt_LttbmlJzasckY89U-1v_ID_Z_DxnHtvngM6l4FY-xn-LAa25Z6xvTFXShpuK4Fm2Fy8FlhdzMGGkk1tD3tvA0V09
u_Vl-hi0YzLfZayeq-_f0fG8mjy0Noi0lfd_N4vBdVW2kn8V_eW0V0hVpKy-h2u2y5yC1pss42kVYVz-CgpQ7_nmxFe5PBv__8AtFJ_ukt__Udm8W0plRF-V
rFhFByIo2Xwi-S7VaHy1HEJvIo-IdGv-1CZpQ_mhVO3_5vlXp-CV_jJWjtP-_KaytG7ISvyLNXyAw06Gn7UQVdqkY0rG0o3V-Wd-xemDo7I0lE_Hgs1w1EHz
ZpuKk0IEV9jrVdqeeAU0SNVyQll2_AUk4uj0B0LGxhwdwpI_Vn5eBq0HttdUaP_DS2C1CFrfVbAYvp8s503VawSd9Lg6gSKg23v7_6tuMGNZ0j3wBTgVV5XT
11hv81R-vH9tFdWt82y0-3H-6_vQP74-bu-hu3S2-F6vnDyaE1SRiWA0dsnySLyE_eG0u3VdHu1FYy1t5S2x5IW5_CRyb0X-6W7q02j-StwT4aQ0Rpxo4Ctq
HxC1gWVWX0EfxZ1_9th0zpNO2lZms_FpRe1Q1Hy2U5olWJztA00_FI2GwexpOmEK0C5aPpWVL1m2v7sFiKHmd7SK0Fo3yhC8x2D0-ywllvlV6mGmjdv-20WR
80KuVklhTmCC0fXSRpuPi1mANAG0uxW9lsiEhzyD43Q0tN34zETJeam1SYiGoFVa-Ui8gASY7_WH853SbGpU3Q0760I8c7v_dVHa4C3bUlC-g5jh0yRr-0R-
P3vecBva3u1VuWUE-CFPW8M_KUSFbGWA_ddacyVjwrlyTUBrKE0zV_L0G-dxlgZMxqthVZuVn1puWh_YzzKjzILVtzB-K631NsxLvUjRsXyAVCr3Vxxl5qha
Y3_FZmzwXJ_sV7sbB-_n7RVuyt7ZUgo2h_7BULdI6G9lN6_WY3zQ9mx-YNcYxfW2Mxvil3aK09yrdJaWuNlo-P0pc-7dYo6Lh4C110WaEtC1slzyq3oMPUh_
q0FQ9plDxmRyh_LF9_XV2G2-dp-V4kKXpTkbuNcy-Hvcz6S1Gfq_NoJQ3rS5vYlyFDtHVl0ZGBdJW__xyr-x-c9nnccg-_sbQg_-lP_yYqxFRnW4-5D3eABr
l4frYnVxXVgltGBJ5w1Fy2yQrEY8PtuK87xz0QqF7q68VoK4_u__7_-_-0y
}

!define D365_POWERAPPS(_color)                                 SPRITE_PUT(                                  d365_PowerApps, _color)
!define D365_POWERAPPS(_color, _scale)                         SPRITE_PUT(                                  d365_PowerApps, _color, _scale)
!define D365_POWERAPPS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERAPPS,         d365_PowerApps, _color, _scale)
!define D365_POWERAPPS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERAPPS,         d365_PowerApps, _color, _scale, _shape)
!define D365_POWERAPPS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERAPPS, _label, d365_PowerApps, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERAPPS>> White
