sprite $d365_PowerPlatform [256x256/16z] {
x9VLUYH124ORAKfYx_-sE_yONpQU33GhP-Is-q0LyXJ1VxRVeGGsfvP_Fl_pNq0UqfmB7H0LfZtZS95d4TMNj5jZe05LF79N_wFvyKyKhzO_PdoF-Pnne7T4
GeKH0D8dsa2sFo0MRVQks_mQwsCG1SIWAKA0Kx2JF_HVsjzMrhaxyIm8rfhkwGzzDmyLVmc2CAm94yWDml61n0hz6P7sZ_N1cgERIdubf2FIFFlP-VT3CAmb
5u4D4BDQnis_-u0r-YK08C__PVhpym_MxAPCsVwYrlVMzmYe-6ISuryY_Hw09fJbJu3LQlXx03Z3VmFqulQFtFxt4Zy1qVw0HQsElb-18nd-sdeTVI-233AQ
NvtYxqnhQ0D453pwKfNY_t8I2lL7ybLEnN-KyqS036zd4bK4joFLYhzpB04R2FAlDlgzF02QuL-g-3ltXm2W0e3OlR-i_-oALoHAsFkh-OFZ0I1cBhdt1-k3
QSf19S2BVs7_rPk4-iitRpy8rqS5C8tqBtpxuNz_DqTp_v2zlwY_7m1lWMNsVh3Y0m0MMY0TIDZxY_gpjy38lH_CGkVVHm06uNi_AAOFXgc0cBq_AVlV3i0z
Hg0Z8Nj_JlP_jNSkoehoG126P38JhFF-pxidThbJHok2qbYCqF_zklinIMSwYOZwlyjlvQeFvFvTybzCIr7LBN9_57u5Fp_tH-2lMcHeukV-tUE3NnARVsIQ
__Rye_EpSp_V_FdZFs_0lsBsy-a_pvz53yeVmFm9yv-G-_V3N-3_dyhzVFzRor-62u6VaFi9-8J-Dq3kv_8t1SZzV7paFn7mytF_w_ZJH_5n19BbL-JS7y3z
eLhoLTJS7y3z-Fj_dljZk9_l_pR5oFtywMyPH-3qtCytVpvzf_jdvNvej_W_hVoyyx_Kz6Z-bO_lMiVFlGAKhofABZ-Vdt_-3_Up8OkK8AsVt_yOMVn8FXO7
_r8BxV3J5_y8-FpxNnvz0k1tjhv8zP_eriVdn-mlPFwKfJZ_j5lhzzRV-Kdhd_l_ZetFpT_DZzR_sCvT7vCVvk_cH-n_wNEVZm_pH-j3l_5vMmAcJQV0vRA2
dcl-q9_N7FHURa2V6U_W_s3sPthz_G6eTLJNgFEOti37liyWR7uS_kOiLvMjf3VPrMqNFu8VqEFYh-_xKEj_LVg0ygy4asswBCL7zQTQVD-7gi--u2YroLQA
MfqT0p_GrX_z6JwezW2oI1i6U0JFuHr_ikByiUilcl37edW0NNh7R-NtrZUq_DLIY1wNv_30dynpVtJzcGh5fiiTk-j6Vvcg2j7yjfxaJSzdLVkR_u-UBZFq
r_8pMxzX9qBh1HTek7_0dHwpFop_sDFD1TH7WClXKNutFoRzo-RD5mP03nxywYUUF7xdoVEITrNczDWANUuqrKBhV0Ud1_YIdwikaIrHBoHTdcZo-xxSnGVm
Yr3VutAjYCuTyoUzr_8vEvrwERwhUkvd5d-MVWqxWTlBJylzFlCx8vz4Npdim9yqS-zx0B_3Jte0jF8JSxyRVvP7Vjqd_yJB_NVuM_9JPp-PFsL2-UqpxaVD
_Nih_xJK_9dd_S0FDVj7dlcDdFBNJvP_Z6P-bJhxkVmfclddF8OnVpw_d_UJp3y7C7zoxWTyIZ2_KFWcYJdu0yp-0EPldpJ_n3M_SArV6ig1pPzrv7NTQu_K
-l5pF_2FdFlJcViZcJylzuSq_thc_ZFtdxa_WlcVkV_C_MVkhmVF_VN8kV_C_VMWkV_C_MVkFtD_3P3xpzmVm_pJmNF_UEJSV-R-D1xP_2Mdu-R-gIfvqtCC
Plvjz4VB_PLP_l6mkH_cT-3SZwkEXytzEF8OXnpB_2iFtx_VDq3kPvU_Qf6SZfhxfydyfQO7RFsg4GP_tDPl8hpKC6xkdwglV4Eet5-f-CobFuxv0t-0ZfNx
GQ-IHn_yXphlzx7l_CVvaDVKYb-aF_Nv7_BYFO1Lw4wVS-Bn8_Sx_Yo_pOWs-lkrRt9-dlclfw_pcXRhHWtLQgf5c8i--EzcF-l3tQn70NHhbPUSKgVo9FDx
u5wDQ_EQ_p-ebY8vt-37OTo0N-IAJfd4NhWYZoglIQIn9vWUj_gU-tEZluA_vCWBLcg2nfle_Dxw5LMhTGLlzqRkWyQNDBYScpxw2vlUToS9sfW_PL4glDz7
J-17ASdrfxxF7VHC_Cc_T8Oigli1l_BnSJIpOtxtFaBrfp_2vZJvvPERJduGl4hS5oubHU0NjONXynNj_UMZRdx5waINluI4BNRhbtKBVBG-EpV_fYHRbB_w
fQJzAZKry-VBLFRFdvj4Dof_sZs_D6t1N_rSVlVyXSzVCVlH-XwHt_m--fvLIc7prredNCiu3d-zbnL91-6lBfVvBlMtpl_wHDPv-MZyzQykaMcdzGlS_zGN
XDmRXF_Q_rOIEwIIW_2dbCRKoJ_rJQ7p3J3-FVzfhHN819bA0FE3_9kyA-Wf_DVH7uW_YHgDtyq_2ly01wmCmVnZyUFBH4WobHoAFnVi_zFAdocv__FdFppp
zoEVK4i0GTPf_K8i0QJPFuRapyL8ipycFmO0OVQ7ulSccE40HlWyHcG7WFatHUF74g1hyM7-KVcbs6hp3ydFMG8iJExlxmFO2lnExe_23mUmMBcNVm-6qFh5
vSS0UBlyAJf_acByt1zh7y3UCpz2xW-y3s3zt1zj7q3jPNOt_r_5vd_D0GowblzB-BEeBKLtmVpZyyC2NwN7x0_Ex_i0QilP8Uta_gXDe2rbX_gvF-W-W2r5
zza_V0D_VmcmPofk_k7v7vS0cvFsSt_CVO3i3c2pwkJ-w4sWWNrUdTmVUmaekfo_IFesVZZ0ul9_6pzoyFBoVnL_5co56hJG_9Fpnry2bW-0cTmVV0cOL_pS
tzy7q4NuygNyMHRnIqvVoTzn04Bk3-60yqk0v_wk-SLl0kVmGxT-y-VXu2Va_gXDe1BCFov_4YMOVrWBd1i06Z_tpr-98kJ-s4i0pVoZNedgY73U7Na9GFc_
cJ_vFa1lzi_b_lZx0DqSh8MG--FcO9tB_V7b3j0f_q7ufH1Qlz3x0DhPzFngVZWWhaJfFJuXzuUw5Ac4rYzo4wXtvIVatc3duVUp_q3yzps04im_t9KerV_q
MZ8XzmThWfoVO7uXS-2lKFr8vaVyNfG2jRb_A7v_0aqv0VzW_FXMo5-1_XZya3-0Xf_6uFGd_wbJfqxz0m
}

!define D365_POWERPLATFORM(_color)                                 SPRITE_PUT(                                      d365_PowerPlatform, _color)
!define D365_POWERPLATFORM(_color, _scale)                         SPRITE_PUT(                                      d365_PowerPlatform, _color, _scale)
!define D365_POWERPLATFORM(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERPLATFORM,         d365_PowerPlatform, _color, _scale)
!define D365_POWERPLATFORM(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERPLATFORM,         d365_PowerPlatform, _color, _scale, _shape)
!define D365_POWERPLATFORM(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERPLATFORM, _label, d365_PowerPlatform, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERPLATFORM>> White
