sprite $d365_PowerFx [96x96/16z] {
xPZNaZCh30PXK422zt_Uiu4wuxBHPspgtzptssBK4xQSVYz_v4Tup5nOrCpNCItBSbBpzZ1UrknixJbiPKU4x1W_qZqERUqV-eirmFP-oDiEz6_rDM4Aqk_V
deUrBIHXjBL_6PTQ-vTnixL_6fVRFusR_t5SsetxRsyUJfZikt4nPJikXhVZOcGxBgRkniLasuoxT_lubFQEqwRVXUQejnTCvmZbfVqubGXkhNaDaRpILqgC
jcOrXbRkJmP-Sgy0MNc-k034p5RyfOLeGIWQG0itK7Sg0Ahn0CqBx-VUQtboGoMTKEnl_Dm5oD8RelTk1S4M33YMtj3z1Ia0qla0Jcdr0d1YhlP277T0iHyd
9h79WBBy3UX1OlgVUZj0rlzzxYyO0Js9lHF57KZixuByf5S3Z1_vYlLPOhg4RJ3qcjCC1XTGWPv8BmVO92vCt6yIqnLSxO99N9YutoIcQyHEHjmP4lkx5efX
E-4KaYqUu8m6g0r6t0065r3f12o84W1TG6EAuNeU7o4T55ZnSu8Ki22Z0Tz2wlZc6MIF_OrZFuy0DITC1GkI-tv9Tz3xVfw2ruy3ztSK-lrB-1NuqNvaqLzZ
VuD-zvM-sNju_CROxmltPscntmZuzVtyTjpBsoDzL-IlmyzFhyUP1lEyll00CrYF4lBx2tVVpmSyFlBNeSSNe3sa2PrCrpFynkZc2J52VXthmRTGNJm-pOv_
3j0uRaWb0WEgN_gDedipnFdQBmDcOJdr8B7s69qaFR4hl_6ZSPc1N_tqXubnNEYtMxy-5fSP3AX-uOyI7p3kd7CxDtwl-O6uq6zjEe1tuWxEuzzCS3isuWx6
yUVeUbmme3OFC5gC2n3rq7-HM61SX3MFuRNj0ueWl-xwAMTRyKj_Bk-H4gti9zjJ5r3I2-8HUZx2MIpyXTc20JGU85ARKJcd2p8WtG7yqG_dZ_y
}

!define D365_POWERFX(_color)                                 SPRITE_PUT(                                d365_PowerFx, _color)
!define D365_POWERFX(_color, _scale)                         SPRITE_PUT(                                d365_PowerFx, _color, _scale)
!define D365_POWERFX(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERFX,         d365_PowerFx, _color, _scale)
!define D365_POWERFX(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERFX,         d365_PowerFx, _color, _scale, _shape)
!define D365_POWERFX(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERFX, _label, d365_PowerFx, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERFX>> White
