sprite $d365_PowerApps [96x96/16z] {
vPW9RjWm30HDYwHaEV__RWv3Q1OLd8nJ5LVc0JCzbaQKxJTWqLhODh3YNcobllPtwb2QnpjkI_KZCFHh0za7AVfrWUXT0Xv_y2LwF_edKK8e2_H5zRr6A6Mz
VcrWRvD-PS1Ktrl4pBvW-A9V6iX9lpGGgZ_Y5bim_2DZSQ1WVRWjrFC07tx6D_W_3Rz6h0rO9VgV7t82FGZGuIyEU5TQK7QyJE7a_jYfNlr7S7OwV0tKOFWx
1eUl_bwnteknuQkV1Tn98FliHm5t4WWLQo21Vb3GyDN_VS2L0fV90-uWeFhPVnw9_Rw3uTD0Ybu2OFWee7eDWE6h_w8brS-1x1q4Y7vWjyFdWSnm9m7ldGKg
rcl03-e_Az1BG8RF0ydqNao6JmEz3lkadoaoVEOVNueSUX2GuUC0zdkHPUB0CVG4Qy_zPmtiBzokVm7iz__jRp_mL-ulySZ__F_NwbDzp-Jx7FV5K7r6E3lW
_NYahqa3KKo-RroF0lhgywVwEJ3BzL4Pp_KQcEK-z18Wms_v5t4Zl_HAGlqScEKV-8v_Fb7zJ4noqGlMxkrojZFnAVUl7ahxWVGp4Ixo-wTgEQX-3ZXv2JlJ
pz27TjpgUtu9VSVddRuc3hXj843q2jDlLa_n8_s0wAypE95-XkYlCpX5FyuM0Ny1KKQWop8f-mRmVdx8vQj3AHiYhe1S5jP3yh8FEjTZwYcqHFZ6CHvGFSSQ
2t3zV0P2pMy8snvIvF_uvQnKpt4Dz4hrdA21sBbKoPC59ZsbYl-bSprVgGOESBPB0bpFps0ES3q_WqRFbkDJ0EavqSMVlb0_dq7TBF3PFZ-3Qfi4e9wlj5r2
2z6l3BHzR3RWHuTZsLhQDZ3FTDj-1sy
}

!define D365_POWERAPPS(_color)                                 SPRITE_PUT(                                  d365_PowerApps, _color)
!define D365_POWERAPPS(_color, _scale)                         SPRITE_PUT(                                  d365_PowerApps, _color, _scale)
!define D365_POWERAPPS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERAPPS,         d365_PowerApps, _color, _scale)
!define D365_POWERAPPS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERAPPS,         d365_PowerApps, _color, _scale, _shape)
!define D365_POWERAPPS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERAPPS, _label, d365_PowerApps, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERAPPS>> White
