sprite $d365_PowerVirtualAgents [96x96/16z] {
xTY5SGKn40HHqGbMbt-wPhQwockFMHt0cuz7uMUsYxbyk1oPBuUWWWFva5J8BuUcxM_Vs_Qthz7PhqqJ-UrjRN_xSL6I-QdsiQYB_DHjqJILtsoPp1_skQ_V
tkTlNnJuS_JN3On37_e3_lRdp_QtlttJy8tyAU5xGd-Q6tjLJG7ybvrtyMhByMNXAlPXn82FOPdH06xCfP-3mEU17iaN3CXy7c1VC23mOK3Wqu38vm7Hzyi3
3fzrzi_fybdd0PVFEWyuVDJPVnnW7tJd0FkWEmVO1zqvm3xetW4Z7tI7VqwpYRvBv_Co-isZyK0BK1eAtbAWKbjSqJ5egnhpo-TBkPDUKrmKlCM-vaiGbGru
KT60b_d0otpWPJxmCXzucG-yp0TUvWClyu6N-S3BVE3bFl027tYH3xog0Rog0b-jhDAxWhy4
}

!define D365_POWERVIRTUALAGENTS(_color)                                 SPRITE_PUT(                                           d365_PowerVirtualAgents, _color)
!define D365_POWERVIRTUALAGENTS(_color, _scale)                         SPRITE_PUT(                                           d365_PowerVirtualAgents, _color, _scale)
!define D365_POWERVIRTUALAGENTS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERVIRTUALAGENTS,         d365_PowerVirtualAgents, _color, _scale)
!define D365_POWERVIRTUALAGENTS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERVIRTUALAGENTS,         d365_PowerVirtualAgents, _color, _scale, _shape)
!define D365_POWERVIRTUALAGENTS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERVIRTUALAGENTS, _label, d365_PowerVirtualAgents, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERVIRTUALAGENTS>> White
