sprite $d365_PowerFx [256x256/16z] {
xDg5ZG0n30LHPnt-_VTxOekFiv76huFGBDhNf9HIIYcbb59AAJrUsvXhRPstrt1xJV6-zBvkR_2XM-nYXzMbgpnsa4_TPjinJJUQTaGPkbIn0xgkrS_kV5u1
dgshsV-Q4dZyBf77FqGUVzcwtqJk_V0GhtfX8uz-SE9bBqpsy5NOms_iuUy3wUF5hqda-Bb4Zb-HqF7RGiTl21q_5pj-OiTlikFdOiTFxFWrSlmoVeCTlmAF
NrSWllA5nw-nusVi-9cpusUB7R_2ZfzLTlniAGJEtqxi-9ahl_RouXVOyRF2ZfyvCdvX8ECNDZ9-0Hc_K93n2myoVi6HyGiD6R_GaV4B4_dEBona_C96nY_e
SilOu_zWnqoGvTHX02Yml4Wczp_kNwbDvGmFQFD89Ns3baJFmF9B-NlDwJ9QMe-qUnHTdlGlwIvn0hNTPdsgVwxfFZde0vHdVlyyc003y8PG7_d_eucXXFK3
v0V-_zP4OI5-0Clyzv-4eM7z07Nw-wybZhhj-Xopltzi9O64-06aoT-_jfn0oWQll-daFq2R9XBRkfarZZpt3z0MzWyai9dP4_wLyIy9fJRxZ-dFloJ6loMM
PZkp_m0iZ7zFBDdG0T1lWFm34AcaVwBV0EOVW98781z8Y3vVWC8DO9LFGFwR9XRClyX77FAtQGaqzFeZolZp2MoClyfd5kO1c9b0GzSVCSB_jGbSvOX4-CzD
e1aPlmZcx_CIQE3rHmgWFpk1Pc3y8iJ-PoVGmFL7Ak0_Eu5cNFmY2-0_Fu5e_FW3c9z0C-pw8uJ__0GQ5hz81lpd9z2CMZz_0DCJk0F5Bv8WVpw1Uj6_o2aC
6u1V5GsC4sZGzKSMxW3AJVr8kp80bPCKBe6mlzg50SXf0FsTnkfhI20KlqZY1g0tz943A781m_mTzizd1o1NMBW3AAY-QhC84Rz8mGRG5TLNjGYxVZw1i7-r
4LZyTXBclsLKN_M4Vv7B6ERlhBxchmz0hhDm1r1OVsqs0elVJi7ykvxG9mz0Ri4TG0Fq3nC8nezFu0b_B855RcAK_kQilfQl-CjTbeuDe9pGXmv0vJO5y-_A
-XUt0ve0S0VGK7rLEs8LW8JvR_dG7ps0AW0F9b2LFG1XM03zdQ8erUq3AX056q1NbEnq_CPm1MYAqXoEtnZ5_BUi9CNf-8rnR02cA3_tNmHaXGzW_WEG1SKn
Vt_c0LW49Rtq0BAxZIW2m_cRafZJwn-JkG4yy1Ue2St2-TVv0KY2uzW0V7u0XEBz3u0vVVxyXw0p3q0-IHlugqo0yxSxtf7gFge_JyC6q4d_Cl2N6IXt0AJ_
881DPh22Nu87-g1_bYc00PphdsGAtFwDz3TtD7z__EU_0vF-BVgRpA5X_XtsTt_2l_RB_Dx-sw-__p_-V_pRR-xlcB-J_lQKVyVyRQx_8bD0x7b_Z_wsljs_
plLFCeELyo-ulyz__rNENq7_4lodVVzec7-Vx6yoWuxv6-bV1_wBy2oSVrLm06tWhyAJmSUVzFU1VnCUn_mTzU-Z0Rpx_4d_Cj8t5Pe2dZ_ftuR-xTNr9mTW
8t_-5o1n_XdrxsF_-jhwcPB-rVs90rZ1zQF-xMV-vQNhRwha07pWpn-0SkjNrB-CzFa2SFg5zRU1F_yLf03kuQyVCu3IF_YRG2oO_fPP__hHNuN1CF-cdxbU
FxTf1v2uzIlhN_l07qzWn_oBiWFmi7yuWNpyMF_IZ_mDYD-6aPKTW0_yyGJQHj6KzQ_Tepz_06d3K6K7u0D_F85zeoYa_tZzV0BBHk6gw01A_vg_lIL-i7_x
ehxfs-CNEV_Rnny07xyR_YKGudVaNryVl-C3A87QFM169_3v-0NT3_IFwu-y8Nxv3EM0rlsCV_xk-EMpd5s_sqU-EtwmltS_vr-_DtuvemEe1-i74eZ6Br_X
rFMx7V6TyOFzsmLzow-FN-J4-i43uEENON-_f6_rzV6B7CJlx0JMrySlSd3z9_tjU-87-xSJwm_arySlWgxVx3lY1_jxy3yrWFeDyMC7K0_qWGIoyOFz-pr_
Upn-x03QJNtBhuzV15s_sRFn0pY87_ala8yVEu0Qrd-9zS7umVw4ljjpyOC8yRjBVYn-4DZwTvwA7qQ8trtgG_7Z2F6Rby0AnW_sv_JT7eaVEu06-hi-i7wK
uVhv0zWmQcOnrD-NwUVFiYRMNsN4-bP_5MdTGShq7t-KHMHnal9BxJ_9FsG7oRFxLpA8_8U3fDd__XePl_tfdDv_qGs3ZDzESues_-z_1UEtmoLmVU3rZupV
ZlBrZ-IDefFNlrEmwvy_W1yEwrC_WbK-iXWrWAq0wG-ipUzXIOvOSkl807xqUcC4ceQPMhJPLVSM1ehnTtjmG0000880wF_hPbGA70O0000C
}

!define D365_POWERFX(_color)                                 SPRITE_PUT(                                d365_PowerFx, _color)
!define D365_POWERFX(_color, _scale)                         SPRITE_PUT(                                d365_PowerFx, _color, _scale)
!define D365_POWERFX(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERFX,         d365_PowerFx, _color, _scale)
!define D365_POWERFX(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERFX,         d365_PowerFx, _color, _scale, _shape)
!define D365_POWERFX(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERFX, _label, d365_PowerFx, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERFX>> White
