sprite $d365_PowerVirtualAgents [256x256/16z] {
xDI9WKCX2431_IeviFz-juRS8SphO1JukoT9aYJfADMJyMD5iTPyujUlgDXu4dz4qTQp-9qVu8Z2ZSVzAohN-_iZvgF-MTk_Ue__umiGnUFdv-Vdv-Vdv-Vd
v-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-VdFnUlWv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv__kAVn6_vroNlQU_-2Vrup6_iZixD_PMl_oDx-Is__oDx-QEw_DFTVc_kJ_tv-
Epy_Fpy_Fpy_F_-rUFpty_lv-Vdv-VdvTpy_Fpy_Fp__xkBdv-Vdv-Vdv-Vdvz-j_Vpsdv_V_SlQ_7DpV_oJJ-VeiUD048IBtLmHkFzrPzw-UUg45CIdDEdz
KM3gPsx_4llRrEUlzfa3d9NxOLx-KXNmPty1HzMG-zEPyVZF6kM73ks5ZUJisnksFfUgWNxehuqn-7Mf5zV20F_EAB3LwmluhsvqW6S5o--VTyZuQub-Fy1U
ahz1lZp0elaRumfOvw-CxmTubdt_V4c09VLF7g0Kln_0z_i1V3-u0VpxZoqW-DF9By3tkm5yln10y0i17ByVuBFxk-pt0qpb1xm0lX-401Fy_vc_2_vWGe09
_5c0UVo05i3tmplv-nH-y0BuVa0BuFi1BO3l1xG0lXy-nD_lwGUq0BuVq0BuVa0BuFlXm_tzFdv02-3x0Is0xmUy0BeVL7zt_O0TGFG3-04qFzmZWEE7k_Yx
u0Tk7Q32HNe_GAjmaTuFG8LBz7w0rYjSe1Vy_mReiJ_GMm7Qx-ld_a2l1U0xd_ukVcwv_lT-VXZkXodyFqU5knAzNw1Lk2FH-m7E2hScUh_0Mka2lS-dugq1
No-mLRuZqCiDpXgnSrR-LMDsm7m9w4UDslDajlNhMGEtFDStRDilXktSjpTlVIubxzaWt_MeQRSHBz7xUv2j_L_-N10n40G04Cip-FTRheYRZOCOtDBkixVx
nFlsTj_SxXFlY_V5--9zyRvuNxmltXVlY_V5--9zyRvuNxmltXVlY_V5--9zyRvuNxmltXVlY_V5--9zyRvuNxmltXVlY_V5--9zyRwxtNUs-zPsdwlTDxVx
pFU_VsdQx_V-tcJDop8RqXC
}

!define D365_POWERVIRTUALAGENTS(_color)                                 SPRITE_PUT(                                           d365_PowerVirtualAgents, _color)
!define D365_POWERVIRTUALAGENTS(_color, _scale)                         SPRITE_PUT(                                           d365_PowerVirtualAgents, _color, _scale)
!define D365_POWERVIRTUALAGENTS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERVIRTUALAGENTS,         d365_PowerVirtualAgents, _color, _scale)
!define D365_POWERVIRTUALAGENTS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERVIRTUALAGENTS,         d365_PowerVirtualAgents, _color, _scale, _shape)
!define D365_POWERVIRTUALAGENTS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERVIRTUALAGENTS, _label, d365_PowerVirtualAgents, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERVIRTUALAGENTS>> White
