sprite $d365_PowerFx [256x256/16z] {
xCz10G0G00Gmfu3-RLNm0MmDraO1002KS_WlNYUrasykHeY6C10cJnxst-z9vd0iOF6_dTi6z2F99a5KQqFQbZoe_V6jbNuRTL5pDotPOz8jUO1VDd-4kqT4
ljMVK4Qu7VxVSAkhlAM5NznZZFcKHiyu1_2pl7_BFRxGrtEQeuUhRFqe_XNtFiONz-inrGcacvhPzSXlgVccdm1gb5OTG7s_k_pw5nv03-MVFLrkyU_-Af_C
xsDE03ly00x_pNbdnnu3Zw-0UnPuy96nn_E7YgZgdKcdN2y741xFRwgN-3-5ZwF76q3Uuw_KnmOVpt_YVoNwqV7q-FoN6_mYved7n_DZ_RyTYK4g_tx_Lsbu
Vj6D3wV7XxyxTlvbAVqJ_a3ojwF21z3VhtvtMntCBsf9WJ_JTGkU_3aeyE-OVoN_gqHWVbieVjbYgFtIx658VbNnfYpuDVf1-KMaYJaB_koENNrbwumz3EPd
0cxz8cf9WLzNdzfAEFxoliAdC3-1ytDutzbxaVnbVkei-BE3Hn_TiXYBWd_sHEwz8ZBIp7coFyEj8Vch-7EmPB_R5hBpDx4SFEOd8gh0hKUepEyKFxRr3vRM
VqOVABydZVcvuVcDoFmKV-kZpjFxJ4f0zs-YGHJ-LWAEVgAMSx7jFI2PcPftal2dANplK_DAVvehNmlqtfkJm_o-HX_mti-sz_o7pN_rS7Dt5FndzGCqVzB7
BhAbCIZmUq2B_pH_CGx-WTrxFirVZSBzPxhX-RSy9ycLhpR7yljMzCLXVlYdhh6LOv6OtnRwXQyNFudvuVcR5Z_1KnU1yxDSVPJvNUEFugVvlGlFFoR7bUyr
_aNmpizd0aP_nkMlp0__FxUp_FthLtyByCYRclyFUsUYiqOE167mRJFl_xohAOMq-A5PFFv68afgRrtBrswNtRv6v_pMvVBpziyl-PxAJ-EFmtAdFiTraS8b
NAykFyhUUs-7TBzI_SIVKmmB-Xq5bnzTeQvbGLMNJXxZMKl9nvLIZE6gTQFJ-VLZSqx7bKjv3C3elTKL5QMFK1M2C_rlRtm5_B2IxbcFXuHQanwBYFPKWZF-
SUlpgqfP0R3cNvKQnGxBylnMfG3u3-VGnkYDKCssU7JM_7VeFGP2IHwmGSqlbLz3o8drpzYZpEZU0mR6hymCjPi5uFNliEOdUe3rVaGbQnBzahyY_DRxaHum
iDulLUFdrxzuVbs_71taBtxxbqRoOnROnTzFvh-ch-JNMpjTulbDUHVBpmU0v-VtlxRRg93_spJG0i3wFx__kMsQ_KPGoHAW4ysVefK0zFwt-3kT0600QeuI
VVx1-1M0JFAdpF6N5FHE27x-nVYrJWydG8C2K9tDS-pyqtPFWBCiiA_XPtidZYq1ZH-pGDu1Iaxl-NFh13-V04NyqehvEUyaSkS_DqcBjOcrG200zmLqulop
pt-w1VQbgP_u-VFlnY_XFQ3KnG38_6pcuzz_0FZFj43fyDgV-B7xBtu0y3985cWwblqXNABny_UVZ9-tG9K1fYFDVvNWKn1-06hXBT2qjExby-y9WF3B0la4
CCrclzsN8k-_-lnQ2EOjq3HlVjBPzv-taotGD6T-roT-__uxbW0veVnrEW1MzzZMznj-O1rqim3qLkW4E1I0ghhd4_vUu_8wuCPOOFeXSu3f4AWLQlRudzV1
I0jC0BqKqy40LETnMCS2P85G3nWrfyJWItcMlxSsyKWCCmdQJB903DyIu57l-Tswn-TViy1jrGAJhrpRL02wp6-ENu__GVooG0ZVJu3-VqSUN7w_3eO2e1w0
uMiC_3W0lJjr3_q4cC-_QHQO87m_0Rh3B_Eprf-pG2G0Gprm0fyAW9cVDFyE3i0_FGb8X_dx4xtLFVFye0LEzO241K3_xTGz9q-2DkCt2wJmhGvy6GBxUtVt
kqn-7HHIEHo0xL6wjvGmV4i0FmVwBjllEiA_L0SPlDL13Bu5m5VhahFVHTu7z_adB13dbsH-OTV1zn2q6Bx0Fss1AP41iFsku--1B4m2jcaBJ1Fy-GF-Eb7t
dB0VwbXWUeDF9a2p9L_-FQXvViS2J-GlQUsxa64NR87f7ION01lwGmZ0UtZR4hxLGII_EO1lVZRq7RO0MU069K26-6qI-Dxy9Fn9i7b-MmfoH7S0bRq8VuZO
940MoCXMmlpc1_ZZsdxOzge79DW1_UQ_NcCwoc_xOI6LraaBF9-_DR_kcQ-3j1-6y2i1EFvSgiDl-rtOkr1W8GpoDtVgiujy5mroW5uonkzD0Qpk0zy5f09G
Cva0xVNKp-e-y5t8ZHe2IFxsslnjtiyz3RDnGm0x0lXrB_aq5CR_VmcGi_sRhvHT_f82pAyoKFZ045ZpUsxxvtlT-KT_LCqelqs22VvjT9T_KZA0-iJVgjNz
vBlW3BySS1rV4dypVaj_YNqNtlZdnFER77xuVSphBas1c0Je9LFuPe0F_DSB_rq4Em-0ZO0ylur-ABz6G6mTR93yvGK__3weFGu1JG5hoH2-Pi1Z_B0_dbzJ
O8X_6-rC_deU__XoVflyI_phaDkshSAVpv_Zr_FNJE0RlqNWNFuRmV-Fl-Fy__Z_vVy_VkbFyF-2yu_J-LFjVmP_IMVntxwFlnZ_gVD_rN_YNyQ_eVprYR_I
_DUhyI_HM_rx9hzz7mHU_n0Fm6_3FyqlDNpzOrUa-6yaVp5-P_sBMlzCTK3yenMIlm_9MVz4rx-tR-Etz1_E-ZUv_o6S5NX9hwEToAyPq3dxNm2_i_y5yoUS
FrUAlx_U00VvMydXXFrlYhzY_C8NlxC4Hfv_k07yvduSl-YT9N3o_8k0aC7_V7xxI1Ht_ab0-DpVj33wFmV0pZzXvz-s3MZ_qIl9NvlnE-VVgFEF6zVxAVxY
yMiHm9vw0yw_ZXl0hmFG97zrqbyEOFp0-UTVdN-D_-OrluIblzJi_3Dp_drRaqtzN57fRvDWxFu3G6zJ7ufV-1w_B13Xjzw_A6L_JbG0YiCFxOFR_ISCNysF
y1k-pwz9a5dWolqtXjyAd_FvpG8r2rgy_xXHvWVo2z_ZDmiCulXwyvCMcjz90Ai3ZzTzkFdvEeRly_-sm8EBdhZvKVp5vwVgmBYBDZyg08RlyzjIQ8mBTGzc
VYX__Oo_wyhvuVS_2cf-ENqQWF9EpzdluolhmW7-NG4sludsVyzl-1w_oPx0cAzxMFFBK_tRLoup_3eESVpzgmqplonuWj_mt_DR0XpYZxJvPIO0ml-KV_uy
ZDKzgFd1_EDp_bOdTuFiEm3Sn7zQi_W-l-q7pzGzCLVG_73-gG1K__rBl-wXpMzMC_W-loq5pV4drlmEw9tvJU6FcVl0DlKPOFF3_6EIly_S1zT-5sz-yvh0
T_ZdzyD22B_VFzy8oVp00DHvVgk3Mlxe_VkGDFHZ4t-ItyKVtG_164uTv7N-Waxy3si2VuT_n-yyWUvz_mB2b_dH_Bvy_hi5NYIqxk77FjCS_j30wF3B0Z_Y
ZwpvWVor6V_a43XqAEWJ_f1GyrlJY-Q_6QyNX9TvyNGktZ_dIvhVcfpidqq2yQiGbhp6ppM4oCxyLZNFFrxLnkBlLTy_qua0j_EdqaZpMvQR_VFgJO-2xM8N
VVnL3vA_zJvkI_ncWTwY3sn-W1wQVubV5kXFWi8kUCcNK37yLVNU_Ey0wVD26JK_H5RtgFMNPES2_VqkqFmOGTalEUS2yRh7p0yAWB9_5T-lWq88TiuFCZ-I
lpByxb9GZ14tFqnOzYi0Bv-6JBl89T-QGOdVy04BJ2dzdFfmvgUwZ-Nl6B_UNh3LOEF7JZhfVZFAdy7srr9Ol3ppXzo-OEhdlN98yjSSNlEFx-IFCMly-plv
qpuofVBtyWVTlshzRFxlz3yzvQdzo8xvd_4_-Zyv_g7uEetH8FvgfsADlrzoBcJnLr1-hKftRlmFRVpYj-8NNFfIa45ydKPZUa1lESRmimGE4hduWmGW9U7V
FyiF1C2v572LOjOy0zhuAiJ8Btxx96zVYi3zQlJrLVsl46kYeTjhoy_yjxeOWRGdl_3lFI1f1yXYq2Ub3q4hf0v_26bfeUrsrn3_3f7JHtfYJoaAt_YlQf_Q
589vjPrUimdZV-u2GRFj0sgFghMe1HSK3DzI8ELSZafsQid_p2-546C2j0Fi21ygFEWgNNxe_lDM8lgEt_utb2wyLdzDk0JZVzG55CQE_pX__nTkcJ-E_x_s
u4060000O92_zJs-QWm000W
}

!define D365_POWERFX(_color)                                 SPRITE_PUT(                                d365_PowerFx, _color)
!define D365_POWERFX(_color, _scale)                         SPRITE_PUT(                                d365_PowerFx, _color, _scale)
!define D365_POWERFX(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERFX,         d365_PowerFx, _color, _scale)
!define D365_POWERFX(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERFX,         d365_PowerFx, _color, _scale, _shape)
!define D365_POWERFX(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERFX, _label, d365_PowerFx, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERFX>> White
