sprite $d365_PowerPages [256x256/16z] {
v9E5OGHG2CKA7_OVkNekgN728niyI5uQ88hv1XkxVku5_8IvpzzWa-UlTtog-sk3Jtp-Ei1jsFnrYhu2C7x00Gp6Rp3z-GjGLe36wn_0QBn-0qRhzHMWyVe7
C9gltu2jF-3wxZC-m7t6zDrdNDzznWUupvY--uphky_u0FSPqtUVSNtt6H_WFcEzt8ztfYgmOiV00rWSCQq1ZrD6AH0Rv0_0xcitmEwFLI00_GDO0FeDU03v
ZhO2l3t53s0yVeDi0nwyNLm162zw07O_2RK6dBRhAm3ZuG1rF8tx2QWsu3HUlm7Qhj-0qNZz1foswpT0w_KRiCWAeca3de1k0-o-VWFildu3xBv-0-o-VWFi
ldu3xBv-0v6tOnNImFrM3R3x-Wsm-_eDiFlw3R3x-WU8l1_FTm3B3UqKg7A_wm6yqlsE3LYH-rqLy0BtMn-WoFss3HIutre1-_lybTd_05RWVkS6hC3zpWfO
WVkT3r3WVki62jplh80NkD_v05RWVkC6lC3zpWeKkD_v05RWVkCBM3VtcRZnVCzdfwHzTbz50U_gFXC3t6TkulxAFaIX-niyEn5rxc_8PXIu3_QtL83TPx8V
0UwhrCyKkByXiYLHuluxR-MOrsuhMGm4poGEIUl_ltSTUkC03ke336fTzzf-RgfAwS0HRnoxwxxWRHU7wRv0ZfS2blk2kLq7SDmNlF6N1eR3pjf-LM0T5Yjs
l0umJA3RHJzYU6p8xUBnUBpayC2EZtnT_qglms75RHVzEl-3mpi0RBnuUPilqZi0RRlS5tu32skyt1TJ6jWXsw_kWni8ORZFRI24vJwqWH2k-yW6Ganm_qel
DpHWR3VSnpKGOexxh0P2p7AVr41Cehyvlzq6RXhlko-wpGPksUwxB_gL-nk8gVIFvh_zlhE1CB3Trv_R6eZfvEFxy_znXHiQ20VVVT6tl1SACPjlFFZtlnSA
0y_z-zyBXOFl_hsV1yB0S__-1iB0TF_-1iB0S__-1iB0S__-1a80t9_VG0Y0-zCR285mVtu38IZkpsy0vlxy1W3kanlmtUStqCvyVWF6Ua03dlly1dpt-Gtu
xj_Vm0Pm7z20uxxFxZN0Sd_-ay26TTytG0r0tVUV0yIETL-SmsF3kYyMzm1KzyLX1j05TL_aS8YgRgRxeftd_wmtEf7k2oFz4bs--xmdmCWiqGrqNpph_fcl
L8bEmtrW_rj-K4ytyBZC1pt_7vcN0_I9SbySJxj_FK2It1VBy-xdjG6E--8qt7-o0RbFVVZF5Cys8FUPzQyfBWSGNGJtHVZkYn9g0E7-os4yxtzsW4Iu_xBP
xbyFe0O0xjSqzqLzte3SnwOlzxzxWFoVkQ_vdrAVD71gFT1zpV_f0VvvWRF1xkk9_-SNU3tq-Kg-ZeUwBuxyDYLqWOTWkY_Mp2SFKAtn0FUDX_zJ1GJHVN6c
SO1w4JptnPA2ha0Ot_LP5m2xh_tc2PhgllRp3n33sUzJGFV5aZEevhalpfn2uzmNHywXQEwBDGMnWHe-aRDebljYoMaKotsnvJmQvRvOSnw5Sbyi9-u0svXA
i1geCPkDr40CmM_0Tv_VWEy-y8NGTv_VWEy-lm7VVNu3llly1dpt-GtuxlCRyDttMN8UDTbzN0CrGO5QXY0tuBkFRi1t7zs0xpww0TjzUWEk-_m6JFVv3PZk
ynjmtUStOBhFRy1qdz-0wpw_0TDzVWEc-_m6NFVv3LZkynkeDjtdD-2ups-Wgjfmdzr0VT26-zW6wfyOxYCRgB-uAf23mZPdk-XtQXyS5dFxbLm7YfWqNfo3
nZPbkzW7ZyKORxXFQQ24uJwtWHA6-zW6IXZkOnieORZFRQ24uJwsWHA6-roYXE4-cgrCz_aDUExp2SzzFhlhFhy1ptq-uRdFPtVTvpVWkSydFFVvxAxx_0Oy
z_c4vpwVtNMVty1Kz_aDnFXjR5b_aTluXMoHzKh6DduhoxACU_a3
}

!define D365_POWERPAGES(_color)                                 SPRITE_PUT(                                   d365_PowerPages, _color)
!define D365_POWERPAGES(_color, _scale)                         SPRITE_PUT(                                   d365_PowerPages, _color, _scale)
!define D365_POWERPAGES(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERPAGES,         d365_PowerPages, _color, _scale)
!define D365_POWERPAGES(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERPAGES,         d365_PowerPages, _color, _scale, _shape)
!define D365_POWERPAGES(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERPAGES, _label, d365_PowerPages, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERPAGES>> White
