sprite $d365_PowerAutomate [256x256/16z] {
xPW7UZCh40HXbp1QpVsl-tBWpxQtHz2cwmOr2jJNwNCYX112226444888OGGGWWXyhh4kxVhkJHsf43gzLoSrbjEKVJd-lf_S6ohttkFEq1XqUyzfm2krVMj
HnwWhAx_w0C9ZYskV_MHbj1S1FgH1s3uxnkf6_dxi_LlADlukxV-7Sw4vABIntTGNrU_VqbC1fnS-lW3sABwrd_2P_y7S1-oB_W0UK5xl_hFQGd7iPx-izil
g0d7oQMFFq1TIz-RlO6IS3GM_H5a2FQ5zBkz4MG86f--GJleiOY-TPjpW6i5UtzqUmVG3heMqB-wlOlsQKBGVNZuvnpWvDB7Tr2Pg--_q8_leCgbZ--WngRF
tq7kW_xy0ppcsBlTWRI3HlrkDu1sq0Jz8Vi83e3NlxhTX78GS_UVT0zp2CRhymzY3dZvU0Sn1-Zp3c8EqEVe8Bm-VmUv0xAFTn1p1tGFRmUv0xg7zm3k3dZu
MJl80Vh4WvYF0FG91Z6SFdy7uVNZ1p4-_LhoaY7e0nP7AwMis44-y8ZLBsMv3F2HgqVghtS0zrVfz_8FPy9nOFMVmVhu0vn8VG_KhoNc09L5VmIP0Or0tmPz
-04wdtvPe8Dy8BvxlcH-1_aK_P44v9vyVFP57o3ViO_ldlW377VauxjdP6O7-UlrQtdD0Sexz2TqJ_m16a0__k6Fx20kVNm6687-l13qWMdTCoi4VM1Qzypg
8FynLx3-_0FumEJiUtq8-i3qxdbr2FelcQiVEOZvo9elNzmWviwaZp-0aUdZEyW75koU-0uYqySFOZwmOFR5Tv0xBllmBrzy1n5qJsm7JTA_1NGGcv9zTPq3
j0aF_ssWWnYB_aYE2i5u_LOHn7QGhQvVImxie4UaFeYO3ehldhha0GWU_j03d2pwyHr4eO_FWFg2XnzDIK0wbJx-2v2CJh-U2SaLt3ruIeB2fO_tv_Zh7zbS
loGWZKaV__zNcVJnxrzXUldmN_-JKByUU-kV2SLXOJI2Rt_UMpzHwcUcxi6JD-uUwHy4sKVnyXLA_Rsxf-pPFUeUwQjxjjLNzwXx3dMFkcTj_QRiK_TexbBt
I7_9Xx_jsJsQkvHzwXugVNMFzDKzqjVSfUnJzgbxzj5Nzgbx4WnJzqXVtQFkqTorXxwwHzsZxidxTO-oJzcdxf6-iW-DvYvbdxAlQ-vIzqXVtQFkKVTCrbVt
g7iqTsdkKlOf-pHtxTqzzH45HVSKAdtytBMt_c5X_XJP5wTFCNTrHlsSK1nxwwSMfH_QFJXiR_t4s3r8DjTFVDs3nTYw1qmZwnuq9zd33yUsriT_0On1VwIo
_FKVAOR6fO-d685-Jd7aOclhboD5amy0EORqDeGGGWWXX112226444888OJu7G
}

!define D365_POWERAUTOMATE(_color)                                 SPRITE_PUT(                                      d365_PowerAutomate, _color)
!define D365_POWERAUTOMATE(_color, _scale)                         SPRITE_PUT(                                      d365_PowerAutomate, _color, _scale)
!define D365_POWERAUTOMATE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERAUTOMATE,         d365_PowerAutomate, _color, _scale)
!define D365_POWERAUTOMATE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERAUTOMATE,         d365_PowerAutomate, _color, _scale, _shape)
!define D365_POWERAUTOMATE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERAUTOMATE, _label, d365_PowerAutomate, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERAUTOMATE>> White
