sprite $d365_PowerBI [256x256/16z] {
xTH7WkWm20HHXmRc_XV-EKV6OMIxgtPQFaamNQrvbM9lqZBTibbnLEiD-KiSsNn3llC5p75qz_BhSF_g-Vk_v_ty4SkD_752ilRZ3_mt2Jz-_FZnuyUF7pz-
_FZnuyUF7pz-_FZnuyUF7pz-_FZnuyUF7pz-_FZnuyUF7pz-_6djptJsPzxOdr_wUjYWlvi__zq6_QFycH7PrT_Itwc5Vx0_6_f7-xEh7--Vby-jkz9lghu-
SwI-mUyL7N_cfVmDVJ_zrvzvBNz3l_a26lhH_eP--mMqzEFzww7ze6pW1_iR-XqVeA4VxL-FxxkfeH_hdzSJ-gxzhZVsPvhvzQC_qzcVQUrFJt_Tnh_WFohy
-F7Znn-6VlpuyUF7Znz_FS-F7pz-_FZnuyUF7pz-_FZnuyUF7pz-_FZnuozFFtxy-F7ZhpVsuyUF7p_--LFBpdRxQuX_RkYRtT7_NJ_k1gHX_Xw-toRzEFzN
_JY_DD3VnlVReBVrIuFzombjq8_opmFzahDVSlPBr_0lG_oIirzozalMVbdx9MU_vEoNdFrIor_rIB_ax9US_PApNtBsIw_srtFyahDVSlPBpdx9sVzQFdxy
-F7Znu-_y7yDFtxy-F7ZnuyVFtxy-F7Znu-_ojbVvUolSlPN6VkhojXVzKp_IyjVvUolSlPNEVkhdFrLplugOtzL6VkhdFrLplugPt-Lapz_yLSv-wkS_LNE
_ggB-l7ZnuyVFtxy-F7ZnuyVFtxy-F7Znu__hqRy-F7ZnuyVFtxy-F7Znn_Xx8_uw7ynzKSu-oES_H7E_WXdVuIpFyBP7-7iZt3sHpZx8vpz4OVwyrx-Y8Fz
iTS_lwK_3lUlqnK_G5U_tpzFL_m0JVr-lwRzlOa_uWn_JaTqlZ_Y7Fyy7TB9_kYLh-LdWpzc1pJq-zzV3TYW6sZezxr_nZhtOEy1
}

!define D365_POWERBI(_color)                                 SPRITE_PUT(                                d365_PowerBI, _color)
!define D365_POWERBI(_color, _scale)                         SPRITE_PUT(                                d365_PowerBI, _color, _scale)
!define D365_POWERBI(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERBI,         d365_PowerBI, _color, _scale)
!define D365_POWERBI(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERBI,         d365_PowerBI, _color, _scale, _shape)
!define D365_POWERBI(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERBI, _label, d365_PowerBI, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERBI>> White
