sprite $d365_PowerBI [96x96/16z] {
xSw7WSCm34DHomJ4_IU-6gR7HHPI-GTumD1ICTuCPTXQ0QaSC4vcMtrC-n3x_5m__VJJvmO__QhrgyWFd1ty-cUnNjDh3_-eStsxN-9wB1pf3NuPpxC8_sJe
JNver-CV67g3NsmonFzMVvpp8url3_NJnplxwQTlp-sdxw_j-rFvvQ9nNmS_jEjTqR7G3tww2rtf0qeVKFh0b5-t-Q67xtrzGEa3IXyG-kcFB-YdVpxWpJwU
mNUfxoxrNUG7tjrd-A6BV7Ubxoxr_VtzzDEtddxwwPCK-gJI9vK-gVJ9DhyiyiaP7yEj5lZad5_Bq3PWWK_wFEM_0G
}

!define D365_POWERBI(_color)                                 SPRITE_PUT(                                d365_PowerBI, _color)
!define D365_POWERBI(_color, _scale)                         SPRITE_PUT(                                d365_PowerBI, _color, _scale)
!define D365_POWERBI(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERBI,         d365_PowerBI, _color, _scale)
!define D365_POWERBI(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERBI,         d365_PowerBI, _color, _scale, _shape)
!define D365_POWERBI(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERBI, _label, d365_PowerBI, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERBI>> White
