sprite $d365_PowerPages [256x256/16z] {
vPtfTjiw38IZNTPjc_T_ssiwSvGpF-YI4z4UiBZxsdx0O2589v-lje_JXc4OxtR_myTfdpqRw1aV3ZYjVtwcXmV-CNxGd_RjWAx96N-2aGHwzGBJ0vyzq35_
FlYmpkiWuOEUhUzEc0j-FWVwWy_ZmuGY4B7fJspzIo0V_ESIwAxkWxxC0R0E-5dxbHxejkdtBu4AxRFfVS2_xWiIw3dutOu2CZvCs0hODtrT0i6RlcPH-q0E
Nyu1M5TDNni5uWU_zpuWuyVl0nnzqlvr4WYxvz4jq31O8NrH0Z62Bz377mM8VhvREmTOrptG2nu8smdff0jwya3dVO23pzOc1rn77j2tae1Z2fpqqFvoD_nX
MGGFHDiBKV29Frcx731h-YXyG5vE1onjSW1c57pW8-JWRoO1cCrH5_IduSzREW1ciT-UY9wiIHaqua_qUVps4l1e-ilVh6KElBNk5-3tDmeKQf-jcr6WGlja
lVI1avxnTG_u7mavyjk37zglizWIuAO_4RqW0PS-e1_s10iw2d3Nv-3RvC2Bei_u1ZdmKdxIlfS46iFhse_V1mJj2pdWzrG0w1djcqgW3JytVJy9jE9l47nO
gxL80tZW4xrp3dWq_VYZGEQiQok1I_a5xHlbGDkcxvy3bw0BsZV80TXrb_gW3oQ1woxrbzRMn06NxFU9FaOEK17mgVjw3kWEi6pwUGyuf82WVIC9S1VG-Qdk
nvE0n8_0xwJzQ0xW2Y3MFTP-j1o00nA6os5Fbu3EdqmyweC-i0DqVj9-L0_e_AHzTmVe_7hm_SkWpi_u_XBG-HbTqBwP1FJ-n_jzq8TpW3x_28SzjnpGvr_M
FkZZIs2ivIVjXvO0dt_bkk_l07t_eUzv_7C0-7hmutkWLFn2y0qTeE-_USyJrG7w3P2WVNiFr5o24tvO1-ZlO0W_h0Vq9n2yw8dlWDftS8GVrW7wfSzT_L7m
rtNDUs0MR_vJ-9Se_EbtMGdWm5F9FyRWNqyx7J1VykubJFQJ0o01gUwpuS3h3iv63Y3jn-TdSiBFI43z8b7-yLyH_YSIeBeVdnzHNmiC3j2UF3A_Vz3p4i3C
e_BRjRyLyIztW53t7Vi_k6jjcST1WBUS_whvjstVLZX0vEVvtn-RwM-tsvuSC7nahlgCptyWr_7t_NOSnzq1owHA0EV_YE7V4lr_TpjksrSHaE9F3d2FEsi_
qSC1znmOCtNGSl-tKfUNj9_mOOySc2UH7oimWoPVgtqOSc1INltJOozpQjO-6uh08F4Z1vnx7GUVySySc4y9Y0_URB4P7_Hinx6d7AYT1FZjWpaxj4_yx81v
X0J4ptbuHn_QpzZtBEJmwBEYs6br7yP58EL0xIX02f0ae9_ZzRgVTy0yYVoGW56pOtmA_jCSg9y4A0SCH5zH-DZuGFJnXZuWC-hQPmKeIm4n1tHmVTuloe77
Ngpv-s_zFAThlo87r56WsW4hXVyjscS5f3Eni1IW8Y04tGCV4dWi1Uhg07_ugwB5ssYV6-4yQVn_Nmk1V34CFWmv88u2-HpGaDlN_NmVqFZH21DlnWcUscS7
d7iXlGy0DuDjftts09R3wYWmGWB91Fe6Prsb22WIu1mG-1liUUGSe550AGBCxgzzzi0FbmAGW8VszL7Wfqk1ODhdOL2x7-03qOkr_-j21qZt0zm710UqMFBf
EN1L7_3NVgFx0UI0VzrlSZ-0yu2_zflT3w0HMipxkWJqKG1zmE6mfqj0kn_W8c2YVNqK0BzyKTvA-nSq_Rhx0VKyOADzVIyayP-BCQDvNzoD3k1N9M1GzrKx
5sFWroGGKFjy9WP_XJNe0nkq_s8xzYsbWCgF70YcVNP0gW4Q_va33lE-FWikq_YZR_u4_Wkq_-iT3hYjyzI0tp_ui3GAwzy19Xs6xWHRJ7nKW4NddnB-lhC7
_Ei-ju1Lva_5RxyJ90y433xU36zo_v-NBU730I9-H7wqFk330PlOz7z5ua-ViGN-iWB_z80O_4ZvZxP7-883pdd_rzlvrxKo_j1-Gc07m0FbsZUmOrkMohmV
4dwYXsKa85pkkCv_p8-klsSSi1NGM-0dm_nVM_S9FrC5tBMFwbzu_gCJNugWu03Mla7qiG2fl0HUWV_40Pkvzla3S-LDFqsyX4yE80aOQv_nmLyMVAH-WGCs
U-sVzu1b_9XvAFfP1q02cSEU0pwUX1Nm3x2HjPzt0ES0QzyezUSK_B6KVwJKBtF0HlG9tqFxTKz2WRzyGHGw01v8bluxiyAthwNlW39jhr02yC2s8_WEqiVL
Ns7mUUWfTm3i_6khu4Fx5Vp0htC0m0yJThxsX9MTTxyE-ue3JlfVBjglUmIAueVarnpW5VofwkLFUYSqZZZlgXwmmhyBkex_SScnrvcV1F3qh_RDopHDT_u5
uGyg0U0_wdujVpBY3ra5e7s25_Z3IW3pliG_4d_8Ad2Sypxn2_LFDKZ0Q-GJ-fzixvE0yj4Vdd_07qu2_EJ_CyClpB-YlK42z94FzPqB113B0RpZrFcJuSBh
AWyOx7dg-B7_Y2K1x3WHV9cVhllT9Q1_FS2yaGB2IE3x8xywFAy0q_xRm07oKL_d_penPou098C3cgO-zliPVg48kkM0NlVb5z-JTmxmVlyoVhZ0D0Vq_JvC
UFzW807fiAVp6-Q0lj_NNG05M0w3q3xjznlm3vVdW47Jh-0tB0Aytn_QyFCeu5G4UCSfe6jzmEj09EptDQCoQE00VR-lysCSDia1rdvxVcqfeEz6zVr--o9W
885BHZxnG-06EO3z_klv3-J0sno0aK_Oxnlq0Q48YFlzzbNWKWSS3VRxxJpmpXp0tPP0xze7887AzpnlvOS7Nky0uKlxjfJ0YoU1un3s-mtvhyi1l1Ofglik
_4F37D3t-o-U11eqmhRx_JRBuOlu8O7s-_thxmT-mWrsE22FBy9xxuLkY3sCSu3VSNxuyQCAY0u0UkRHOAlzVhFx0KdqCFP0nNxVWb_f0qyT01TGqpVcvoAW
WxC7pelDp7xVoWdVZqLkJyc1N-A0mw3f2qk1n9ZZXnCARUSltkrhr0Zre3Fylgt-mGS_tv4zQ3dg2lxIxAJV_du03jX1NisVWYyqVPjX4DZ4BMcVwVtvqGU8
NzB-E0xn-7zn3eZqExG__1RuZVe0W2BNVRqFR1h_RjZqzVi1iUuBzAPze5xxkDgAomzJSk21Fr3N3om1B0Ngj4zxdjZybJa0xHkANxyVm7AuXFxKlc_yzVk1
qhglTVtuVK2e-_R6o-4YxVl3wuy6dsj_KaQ-M4k1v_X1chv-Fq0vGDgFrlJr-u5SyAE9NxyVo9rrU-I7SGxajV_PgMNBeB3aYou1-XHLapsF__t0kZrinS3x
x_3pTmz2vlVE3oC74FvRwFy7
}

!define D365_POWERPAGES(_color)                                 SPRITE_PUT(                                   d365_PowerPages, _color)
!define D365_POWERPAGES(_color, _scale)                         SPRITE_PUT(                                   d365_PowerPages, _color, _scale)
!define D365_POWERPAGES(_color, _scale, _alias)                 SPRITE_ENT(  _alias, D365 POWERPAGES,         d365_PowerPages, _color, _scale)
!define D365_POWERPAGES(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, D365 POWERPAGES,         d365_PowerPages, _color, _scale, _shape)
!define D365_POWERPAGES(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, D365 POWERPAGES, _label, d365_PowerPages, _color, _scale, _shape)
skinparam folderBackgroundColor<<D365 POWERPAGES>> White
