sprite $devops_caddy_server [256x184/16z] {
t9Zf_fim30JZn93h_T-tLHXgzcSXUYF_zrllpcWjm9V_b6AvVi_DKllSBFORYkKoV6By108Iq7zj0yeElD9FqwG6LC7u3XHUm3LT2t3m1UYLVOgY3Z0mFhrF
7biG0qEFteMFKqTM03xmCVsn0WmCII_il-jWE0Dhy_VXvxqu1aRhW2oz8_9xYqWOrG3uFhqFJbI3Ps080Rlq3ll3YQzWimP667uCh-nFoUh0DK05yWzVyRtI
T_Il9KYW1gAW7OAXXj-XU-D_QSm1BHYZ0k3l3l_kfJVmNh8eS0na5l1pmvz9fq5RS6nW07peuGw21ooeWK44-FXAF_dHtxj8S0na5b1A2Ua1g67MFsKEn41N
0GICWR-5lnraqJ3Fgu7tcmfuPw2KlFWp-3Fq6_Ph41nCavM03b21j0BqwElmLtW7FPJmKM0bi0wOWQG2c7w03tt4MpGuM0myd_PE80986W7WEqV_aBxi1GDK
86a3V7pu6Nv0Ny9iAl2oP6q0-DN5vvirhdvS0GH43KY8FzDzw0zpA80T07yI0Qn-7t-Ura-LlJLFTZLSCR0AUBe2x4_bmOT_YrzyxhgDc5015G6V0YGJOFZU
xWlmGHTNUiTduOzr0dWHT5w5Kwr-y8kbVxNXBL-21XIqo0wG5Q0FWGJuy8DVmU_WOT-vzsIfUG8M_Zm2ZAt7DpYZeFn5wEqty8NhX8jFMj09a08aM05o-FNq
Ws_PG5IZvuh33GxM5mVzeyjhm3F72Q3zmVWxVEY5tNM0WLQ1sre02_od2b1yV_obyUlBF7USFJa_po7det5zNb80Ny0P9y3ugzj--DsFEPcqv8S4Iau522jm
dzy4P1Z_NSSFVnLwbfr6ze8Pe0A43M0hq3u3ffDFW86v-1u_-Bhad73poGU_26ZFm3S5y4v0Xl7VMVv4yOqUUFyIdFte23ZY_pW_RVpmt-5ty8L-9atSacP0
1N00xbOErYCvPmNw-C9_QVo23_paf1bm6b3Z0l32UKxxbPz9mC_tgmLw3ruLT09uSpxYHy0PuwV-y1TYdcnlw_rD717muQ_hD-CCFmV04t3Y-9N_8kCFy2C1
5A32tpu2u3_d6LXACFxxL9SU6h_Xpm5-961x0ghXwolGDtRkG-jH5Gh3S9IUS__NEuMyo_dmo1yq0J9bhvxAizaWLZUd0E3N_Vw7Vr5_eCaH_fa4u2UU-yqe
FtoDd_myCAd2NVV3Rmil1pmq0UKIUCucOAdFVl707-99lYQWyBC2c3m0A7_NvgV5r_nGlNDj0u1ZRXCsVhHuyz_mKx72lrG05V-40g3x6_t6IlUxSm7riGPm
ZNuAOF3iHtitlvP_VCMVZlri5kOKm0zLnH-hVih_wW3m_iXVBu0ftV_JdtxwxI-_plxkYX_hIVyopP_KlwuC_zVyT_Nxc9BuXou1uDVzQUSt-DCLlzlMW76R
09WLwtuAOF36l-xVXlyLlx_Yxre0g9xxAHJt5d-g-KSF05JjVbdzlDcVfldDb_uKlIlyzmb-4j3DNszjuJVs3VxxvZSL_yW2oELVywVEVcFjN7z6JV5dVhkV
18psP-e7-4rFF_p-VdVDxthwr-V-W7_jwRz_vRT_ej-Syg-z_ARHl-1Fh_ZzX_cNitu_oSy0wEDtv_p_lUoFd-ItJVxbVVxxx-et4_mae9T_7UmF2N-Uqunf
zwz_cD_i_N6yV_ddDqt-zTr-zrCqk_xnksQ_TQ_xKyqV_Jz_mmPmg3zju_-VVyt--5VwLwO__2yT_yQVvt-BNrBwgNvQAzUh-Ttd6oBird-P_tb-xQoKylLl
y0F-N01d8mJyANB-hxmiI18mtU_rSWrdkSy9FnT-deuOKtcor_-wDbQUYZ7VxpCVVugUr-GopXJF1tnD7oyzNgEc9llH1_XKPYvU-Ygtzbh8_I0vU8dNoC1a
lrwrJWA8bF3dLy_I2R24l2HFY1hgj__NHwo46l1V3xvzhpqZYmJCySDNlRPL_7r24b3wrn5--EXdX3mRPun_BVnC-sFrvVJ0scA2Vme_IPG9cE4l-KTpUEeQ
PGBwtmzTFko1iR_3nnnTsV4Hce3IR_1tcW1hVBcFFxuKJVn8xUcz5Ug_zVV7A7pesuvEQ8pJQIW-eGMW_gMxNxgVHc5lsS5jpaNLhmcW04RvuIaVlJpZpnr5
KovQ_QmxjG1q-k_yj1k_kwKNlJsAvta86ct-e7iTe_tCVYLV7_BtTGPQ-EZhVas03W1hkleDVkb--E3XDzfF57_Tpm3GuT_r0WZyDRx0AtAYQc_tnvGE_RTn
VcfF-HLnnH-Vnw5V2q3zQqV_YZ_WJtdvANpI0_0WlCGHNfcQe6V-u3E_kpyByM_b_oWx-EekVNh01d-bqX7gKu4R_QQdVpdqq_sPd_NrBjLT5JvQ6UKFl1vX
FFH7yVUT_YY0Gx-rmaTyg19-bbNy4SzHfkf-oh-pt-pyGVnL4Rj8B1C8VkSWc5FAJvxmtmRxj-vN_br2FgfHIG0r9I6__BszSrzl93RXwBVVPcxnZFF-RrkB
dmwBp52FUszT_jfDi3n780H8Tah-VzpoXrOIVi82AFZx4Kt6HnKgMwfCMEOdf9WY4t2PdqSkK2wYfwydlSQVyJE_HJJ-MV7h4nye1isIFvaVyYUII_2aSV5F
pt2ngU3_UitlpERXMjWvNlX4eJZngff_FUKN2IXESkcSPqOOcAyqKfZByGyRrVn2xaVbOZnp09ySUnFEVw_oO-6uNI6lyyDWODQRTYqDpP0d_4nB5VxWjrin
-zxkDKm5lx7O_O7RVjC4lE3dATZzG653vfNIAYT0U7gcz8ryTh0VlzAAtxpYvoVBBAe7_d7i_BVYdwPbQuesKs_nEtt-qa4Rkve0NhFQkVt-H-p4dHbm_fZ-
4SnF_7_0CgV-te_x_O5bb7-TlodUjdQdm3Q0jSx_mbVkOiZ-b964prEVJa2dD_Sy7d8tEPhO53033rPvY3rhnG_zs_nhmIz7FkDdRFZv-14e3m6bJS6wd4w0
NYFll2D8Us5RYEqjS81O-oV_1nwF9QZL_A0HyJF_yipFTeFv0t-5qXRKPXEGyIqsxT7malww6xTxM5dqlNBwXuH7xHQQviW_mH_rX0__OVoQNZ6dsdZurbok
7ohE31oOyblNjCxmxIN2tMycyg3mEkxYnUzivcSZFmLlrFpA_4902yM1N_x5TGlu4NT1UnBnz-WvWC3sM0BjSzfZw8luMl1uiXRHtHp0Lex1Xk-W9ooA9j8x
4idfERyXHBt4hzQhJO7i3dcOMYP0mS_CR_GiH5yE1Z8wW2qOnz-vOcNJJHY1VymFzPxP0IXsqJFyP_wlpXCKDQ7mu__aSMD_1NZm-xE8VxifudFzJXp7_SSy
UIO2uFq3_fQ_TS664h-If0Z68pC1H4QW2dwAWL4nstzslZW1l47WjpSHVqkpsBYf8DgS6A4vm90dwxamFZcTfftjNl4FV1fzB0FzJEiPutDSXA545VcbWEA4
eX8byJDJNZp23xv-9-aBG5iqYPk2beOabBMBoj7ymfVnIVQQ-Cec0_8KsVUZ-2WiQE3eXp4ZyyWVskK-e0mxsqOfVlDVcHjLmXvlOhy3dzHNZMa7qUQZ2B3E
FG0G_CpPp3LMliDoA0TbFpaN2tsiRIbkUJJMpd1ElPW9uFUEEGCoceMTM-VVLlklpohy3Ox486P0R86Q3mTHZ9ELnHzNF-Rl-BdngS65Ju6W43Eii-333Ger
qzbMYoJmyxaU2agDzr1qpNldLwAdzy0114oPQ4iMVD5AefVBpB9ov6zHYOMHyHdDFQiPaGf1wR7Yx2pgXs3yneIEo8GFVomdsdWe1irT_BfAJ0i17_DhzWeI
u1Sz7ujo8p_cno_O6PCmd2clFAoBycCzdGIee28vHlvOSuoAcYZupJKstpJ89nz4MvlZnb_qVZF_kFvxy7VpPto4dMBhM7W0-qQR0DRqxFbtc2Nf_lpymD-_
9KsA9vg1_o03OTTaF_dUzy9laUJ_5l_H9lfX_d8AKHOOIzyiHrwf2ebA2YWCgfdwSVxc_cFQcHLjMfV5-8MfjKNqixSv02eb-Zdx7pzlFyOjC7yzIE_Wt49U
gUSdGJJ-6Nmoq6_bqQ9o-vDtYLv3Vjk01ugMZ2rhKshlu5c3ej_SNctj5Cp_mdHxj_CVJZR_C2srT8SbmIMn584RbUJDVgPaS27_ZFpcaI7lwefzGFWj3-S9
5t5_UP5a-C5mzPDZPzJJyezfOHq02ByXvO6XpMlFSczCIUpWRam0-r_8ky86eW43_pIPdViCXspOijQZhRpfeldTpWF_hVCpBRNeK_3yRJlQGPPOCp2vEpKp
-xmYNU1_o8pYs5zIyWT_Iu_91hS-7YCI5r-jMvcvct-Z_etyBFzBXs1wXfXNzW0oKUH3rQ2afuaoBF9VvLtYCdefganeAu3VJ0iEe2QCZxVti8WzQtmDCMpo
y5yEV-H23Hv-dWCFmlp-JfwHzObn_gbDNCoxKCHMuf-dfxw99fHvFrJFNy1txs_cp_pi_k-TZh40uBVIBRoJe5WwfXZuoKSsmq_rgF5Re1pQ0KrJIER-hvvR
MHlucFzz-yS927UTR65JFioJ-7CwuNKc-T_S0jqGa7AiXXy7C5ZuYNu1gCR79Zw1Rw__V0zeJZlWjlGQD_aJgOOqTrMrwvRsunoKIHGiUdLd9stPNvi_h1J3
z-RV-_6VuVo4JCB67lYJLNal-ntypIYuV-QNmVGxvQxxdr4fMb_dVgRPyIdlqNvl_mVVJyYGXf_vpzgCeXZvJ-8tTCvFYyQI5p9dZtvDuIN-lU6Vr0cCd0nM
uwjO3_ZE_ztury3FQ3oBCgCp_b4HVuTVxXuRmXUY7siVvq_uBChB6u26s-Xy84_ytvbVKlEdYG8NVbQ4WDaHsVmkuoS3v_hl1Nx3urmKQKo5_S_2sll-_o31
8yW8Y-Zt7dwk_r_i99I_gjQuuMSF9luO_yxMVuv_gNnXfupyn8v3TVOycvV5pUzz_BVxFr8r0rAkrVjVCasE_xaUpJQ9_4J0ziuhvcSxUt_jlzN_auGQQgFd
YyNXd-AsnhD5gvB_pEG_U4gAIO6VdraKfvDghsJgYdt_LbW_FLOv0PRmgEpqymiA5bfupg_yB-ydk7_CV-UYyOAj0__e08evvlw5KKrVrbU5M5Y_xl-F2S-a
dZv7ACoJ5WLH3NxlCz2M8NWegANydtM7fY-pdyYldtAckvFxd9aVzMXMtY3Aw_CVpZlw2GvciJeKZT-Z_UK0mPjycgQp-XS7e50E5VLFv6VtY2rL5awzzcNL
s1z7elPu_dVwjmUjZqMh9zhVwr_bVoqYK0_plZIwzUhJ_WUD4leQAC8VDqK9dOmQdpd4g21nJ-3i_5VX9PvVzhCP1NoFzBULzT-RqEI__L3YrW_Qui7GAdpu
JTENEV7Kmgcg_v4_R86MR9K9Aq3C8JQTYqz9b-V_YyuaTJfXW_ImYsMj5ObPnJ_tlkJGrRHGpuaU_DBixygk9aMTVGtyK07L9e2-Lv6ceHc0a7csUu1Z25oh
-nzgy8lVRAZ7LK2OULpuEUOFasad6DgmdllV2gX94KXgmxWjygiYzsCzkwB6XeSRKwFZA8XNzt-yaxtGn6LE7Gn-Qm3JRh6HEFXZ9FYdBpyfODQ3OXimyHEd
X4M2VPgcBhHQJHCSH7SPVgKBK8PItF_I0fqqIv7BhnR1Jxz9l9oKnU4wFoaAVfSLd_c30wHoBLUFy4E3xEo7L-x_YLvJzaKNkm-3o6B4ur_f0XxlAysmuSS3
m44JHI1ZgYh3QeoANru5_YYn2LZV_yGaPcbRxRPWzRnWSrhT2s8zB9kzwHq81QDf-lpJJq0p7fNhpBSvodDTu97npFrn4qRCiXTt0FbpjUNzNoxMDXKaVYc9
pohVWBZvKAPeyKAA_TcvKJ0e4WZzE_MVo0v220WveUqzcX36HY2pPjdQ6-z_Gn_ok7XRPGrNCKKLnaAFR-f8VoakARfc7p8ckDu6AgCVRg97TCaVHc3OF0En
kwdxID2dZmZuFJSkWx6h9ZrkgQBvm4UpfzXnH38cXeoMlT2iukf_BGmRfVxKn6_e0naSVkN1X1eZ3sLwIc-bE6gYo8WeyjwfBuRvh_rv_kj_9o9_QaQrK5OP
FXraP3ng7WezTHB8lyyKuyaYbqj_8MHMOL-i6Me1wVhdlx86AZmSKWp5CAMYD56CcWn0hK4JZ1Ly9dfX9I3LKYCXwRULNDBB8sPV-wtRRfYVVU4YH2BwBn62
cMJPUZ-hd-9zWFpIVYjHwgcEyU_FuEy9eicjuvE-Ve3uZRC_nGDvziVmhrma1H_pVmG_bpmbPltFmQSpyntAA7hPdo5SEE3hW5M8Vmm--tyeepu9d_gGWcoY
5FqS8GMEvU27IIoZeFyq-MTKBl-Nlm
}

!define DEVOPS_CADDY_SERVER(_color)                                 SPRITE_PUT(                                       devops_caddy_server, _color)
!define DEVOPS_CADDY_SERVER(_color, _scale)                         SPRITE_PUT(                                       devops_caddy_server, _color, _scale)
!define DEVOPS_CADDY_SERVER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS CADDY_SERVER,         devops_caddy_server, _color, _scale)
!define DEVOPS_CADDY_SERVER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS CADDY_SERVER,         devops_caddy_server, _color, _scale, _shape)
!define DEVOPS_CADDY_SERVER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS CADDY_SERVER, _label, devops_caddy_server, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS CADDY_SERVER>> White
