sprite $devops_caddy_server [256x184/16z] {
r9Y7ck8y40GnoAHBx_-sXrOkq7ngzqOBqN-yJDMqnlB-sogxc2bdVyiX9xKvvEnlcN9sz_nxhS3zONmlWF-Ib-JtzDx0g_F33doad-UvCO02wU3LUX_X0tYC
QC7-fGmO-i0-kmG767X5_aYloRq5OM1uVZrw2U-JX89NuGSVU4N_SGKO4FpZqplsZny43CICoq_pr-6FQn46GWV6vuSUV4z-UaH8i0Q6ujRLD-md7JGe0mW8
6Or_bLwmdqMqWceDZCpFy3ryPB-4u635m7XRG0u_uglID_JN4YHGWs20Gp0elnu-w35d0Zt10Yruhm93lUUj3l-aqXhuLL8K20Fo30p2_x7XSn8Q3MqBl86n
-3K-g73h80CBqS3x0eQTVg278aJyt2916T02o9Ft_kJeWKys_Ahi81X00470AFmUluO_s71hEXunyEjNgO0w0qz-3dfypZMZhzZt9WUU7xa4T80AE07z-UtH
P_Z02tGheIWudxE1_3Gq0fxEp_GrVg6tv5FCug0Ok5podK08c4q3-l8NV7Nq7JtaEiK05HYo0Iluy3FyTVh9fgh0DUS33UXB7l6Jn4y9Uk_0Lm01lW6a4x_7
FzBz_SVohe2o0-1N0lhpi_er_d7cLSKywt9MDR074N2H0lg_3njy-6lyINEdEi54590Ga0lW1VJdt-lTP_0NzE0Ab8G3MjC8u29ehiATwFtgB_XJZhZQb5j-
oA811IJiWB02IFURiC47h6n-y2Cyx2jVzsIf2G65tmZeoy_XdzlnPuhSIlYXVuFd3RTDaS2TgH4W2g1NmARazl1p-Wi-_42aJ5_OhpAB0ouEyPUMQy15du3E
_BJVZB_5X_xgmjjkVN4yK80S-9zm3pJuxVYdaXgVzxctjEHyVpdaoqiZpqiA80Lm0dhp9zb--ENBN9LBo5r2wK2nI5Y1hW3xJln-_2V67_XJe6VPXLHx0GEP
Yx01RdhE-OIv4z3ftYln1J_uSSc950TNNlYZ09w1loY0E06xEhrlFl2p_E6F-7Tu-KLmzcCGy37-jFqjo8s_y9_Wr_ZG0mz5fG03GG07u9JBiQn7qgn0iWKt
qVY1V_VW3_WB_2poC20Qa4m14D2Bd_Ph_Z89-0zf1Xzw0HyLD08A_-puDxm5kl77-iC_aPkd-i7DvtO90jxu4--CH_Yp5ocW1xyVF_oxC7w3RmHGW0G_Bm7m
YsTW5tup_jESIWypVyO_6dmde3u1AUF7Az2i2x0nF_Yc_ZV-gUO_NJZx4jyBW3zzZFy0VvKj-0N-dF4pvBoqi1c_m3S2bijU512lmFeHi34_ptuvCy5_Ebjy
Bo3mSmFuu04Wsso_-MFyVEAly8Dwp6Js010su8yQq0y_-Odl_Bk5dyOQ_0yMGFFx0f0Esq_pvwkV-RmsZmAS_hDpfmkAWq0GW3T0W7RV_tdtm58BXrOmwU0S
zNDElqv3BX8qG8U_tG3Miny-xzNFxP-t-ANjnsv1Qm1Zl_EAFwj-jF-h0o36bbzh05E_lld_--M_FzpyFFklh_XX7VGlq_p2VkSm_BVvJ-oFMKJnem1sVl1r
lzpvFVm2_rYknu0P4m3Mn3ppUsVenyw_styP_g_uuoj-D82bFppter7MNVpIvKSi_L3r--dePsU_JFFxXtx9SQtyfmb-5C3Cht_Qok_33lxJrUyR_hu6sFcw
f-ONOxyFOQw_eARu2x_VZm8SxI_KD_1xIp_uzlvrr8-mdxE7tptt9_YTfV_qo1--ejyF-PsLttVw5_XbYp--cNyPzST9VWm06_ywvl-zsP_VoH-w_Cj-_jDd
zVi9VXJ0okyEzgUBlynftlVxtHVp-tj_Fjw__FXzbz_jxL__YsRtF_nhjp-is_sY-NFyyO_j0EtzSXt_FtvN_FbR-XscF_WtNV-6lyp_0NugwRlwyMbflLgy
-_cEfBlZly9_FpzlB96o_Wty17zfWD6a1BzatF-hbmLH0QRx8o_NM0EUSu8V2p-7axFKDtlZRMqilHLZlZyMFloI8xv6opWbZmTyBX--TFuQUcgo7_eB7vrP
cXVRgdpQrqBFWvJWI_WQAZ3PpwlMKG141FxorL4w0Yn2Nw8tH1tg3n_ri5v21lWtvFBRsZkoK80vVl1Ppv-L_3QX0jH-P-ndFlHJKhyRnzxlAZ-cVJbMNC85
ICd6ZoZ-ANoXr0MOuQ_vhJbSJDCkG83VwlfVkF4J-0JD9QRiV0uNeFPx8pycG8rFp_7dJUdYP_GUFrl1_b_s_fo93_hrH2TrPhWCrKzm0x1_CVVJvh_fwsSQ
zNJNGlTp0RW1xFtWCHzwUiVVsafNBNhzEEv40rH-P-N710W_Fz8BVMZbUHqIfy-V-ApZQ3zclvhFB_bxN84UFlIwdml00o1uKx-7dpO_-C23tsdlRtxTpmC0
mtz_Fmh0VerFS4MEgFP-VnPf-S7dVFJiv4VlCLyHA_xyF4q_Dm3xdQ7VmP_WbtBuINoK1y168gM5PoONw9a_5NyOyiFP4vu0uAVsFxST-EokVNp1Xlto8H3o
Mu4x_Hx-tWpvbvQVDdy8HQzlKZvLmOyge_oCvokCJNzk-1SJFngWwG-1-10tLSGlCiMVuMbLIlUZ_Otz_iwVoA-AS8hqjxnptLASnw7eOa42WL2y_ziErl5s
dtAi3fcPxrhwqvSI9jkIPKas56b22EDiXPWorDpd1_zFvCVyZdytCLMNuGJWKoQClCz_FioVqrQn_s419FmweXdWemfLJTI4jUKdf8GY4x3Fdoz_K8v4EXDU
kyzl-3b_H3J-cl7h4nyeccREtviVxexa8tZIEF_LCrniIlWl-_oDEJnS2tiGBvWe52TUbVFVXlmYEVSaE_XrZICCp6Ggp6tZ7pRA-OLSZyh5E7A0DZdn9fp_
VigFXNsxGjBy4743izwqQsbeXXpmCorP-8C_RiMiQxdNC2NymHBt1nxhGnEmnz-ICF5ZI3PaNYcjT0A4fsVglv5Fjr3yAwtuoHu__tETHVN6VpvN_fdnJzDr
AOenKuVuGHbywM2CdKq0hxd5kVtwI-B4dHbm_iKShzlDZDwmmgdlw_FhwuqLbB_dBugFvSt_Vi-WJVC_-yfT35cVqaduFFLm0YfzkEVpBLyXpo8n1Sp0crKU
GgQIy4D_aF-MyCkHH_oC3JyVFm85bWAobXlrmmdGQ-ITNxsK5vQ5MDu21_3QV-F_mEEn1BMS7pGY_fR_sl6JRM1-vyzGoe9QHXF01zPNDxoalkx1xHvM5dsl
RVg7sADM2qspyq_mkvxmuN-ANzChvhusnWVRByiCbi1t3hZMkwvfZV3Z9S9T7o7o87iTT_6wxsos_0UXu7NDIyyF0bfDqVdbNrotW1zfBXXF8luQFJiGiRsN
W3wdxQ7FyRNWyMGjeZV_epgEO4D8Ai8fHEFq3OdaTCmV2AwtuLVhDQP0TeVSffO9KF0BymSz2x4jXrL3Edyic8Q_SiLAqwqm0d-N7-ezjmv0iOjUuFVybyfZ
YfhGZlz27lUzlm8y-FLPnByy5F6vVYUEvzShF7c-E3yE0_wo_TQ564hyIf8SZ4UsB9M5_3j-Ye5UiRV_tFXy0dW3uuyt4Nz9ixHnUmNnM8Cm7E1RdgpdmlZa
T9fsjdl5F_1fzB4Cz7_iKXYVPfV-9IhdbmAA4ufAbCJFJBNY4NxmzJD9NG3QeadS5BGq9A5igW40ymjVnYVPAz9MDXbGIv7RVkIFme86ZduOCp8RVymn10o8
vyonKOe__5VcHfMmnvl4py0dzLLZke5eyr44kCqr013ymjd2DMwoCeaayOxYeMr__VSLKzpgqNZIxfpw6YQ0ltNC6P3H8kmyAlzoYt-sMOM_m94OM0OaKS0y
Gq9IiCZApg_j0lDN_6rLfC65tme4fSU-pio72nHgeRD4Qht2p-TwA2WrtbknQNvLVYLwUWySGC2KYR5amHUKnBrSPfQLdRz49HR65f_HccSL8r8XA3rMd9r5
_HQCNvZG4PdmuVToeeo7ecckujTLObe8-5YxPgyW0VwcvmC3dF0pByqls1dJRbWettZO9igFzNGIe5obpfZpMytHAsgYu0_NMDgcGJxv9bhA71V-dTul_Ftw
hy6_cN-0pnJKdMAfM7Y0N4UL1MjwRlctpP9qNwyN_FLRqgGuq3J-9na8koRxoNrTCxz5Ul-F-8ysqG_pfrF8MX4OIpyiHrwf2ebA2YWCgfbwDVxY_fPs3XLZ
Mg_Nu1UcrXRHBzxc2L0kxkTIH_iKkGzkSTcRnDh1ULXUgUSdGGp-6NmoqBloQ54r-vDtYLv3tcF09ugHZ5rlZrKfUCiQ5Frc-UAwN2-x_4g-gfr_SRRD_vDP
h0vBWajYAO9cL9At-3ybWrVoJ-SFZxIygohM0U6FF9mdl8hxqegam9VXTioFdL7lbp_kdun352NyMie3GvdNckK-c1Blu8QfZVziUPTj81hG-ASfx5ndsBBX
o5gVPULD7vc_jpFyZye_Htw_5qKk4x_RZdPG9DOCJEvEpSm-hqXd_6-PKUpwI_6ay9Vqc6nmgUCn8d5nRztApDNy2_MlyRFyz_YL3kePFA-i0MIYo8UgG4bF
4nLOvB_Ak-3Y5wRLCg6i07uoNN40DM7QU6iDYzWpnwz3iCaxF-5lbvzSI2MlSu4nroB7gSZ8wiGq_gbCdETTA68hySzJrpVHX3BlYhld3_3nVjeVxq5Upd-7
_yZf60i0_YZTx9sKWh9qGj7uoKUMmD_Key4VWV9xE-3KMXRiYhdvoV31_vRZlOxQdmcmkqwni2aVvadybatsTIRvtrm2dGUaGQo67mS8MFY9VWQKusCJ9X3P
N__vFI29xu3BjTQu6tyYrP3cgghsjcpsusrG9b68w5MTdRHbtJU_hPJ03-zFtkgpzMydP25ixCRVhDfZnS_WBqR1_Nj5sPk7Kkwwjb4fMZ_8_KApubFUetri
_mU_dP0X1N_BFsep1aN7FuZVq3L-MZIHl90vj-XN57Rnlmg-rmd7yp_mLQmRVkE_5_wRyPywB6L6d_4_Z5_kxWtXZwBVoQs_Wezsb_ztG-MpkT3vG3h--vZ_
T8GVNFXP4G9cHsJp-nZV0t9I_-NmX987vw98OTgtlo1I_p_b_bygRpo2Z329VeVmFG2u8N9-obzLQzpmYmSJlyU_yVhluz-cV3cnKne_iUEfElijgdmjo1p6
Fzp_aMeOa78jt__CD5dy7zMZp3C_StuYu7Ah_L6IkGDhtnGEzVyaLaCjz7onEFoJRsl-R5XL_35pv3_NDF-1dpWLKPnEQhmoSV-sM1j-ObeUAvs0I7XKThRp
2meMMdYDN_dVTZ_1_Jt_dPF6IxEryxi3AEQ4-u-DAdrPNnLYOlsy__yzuPdKq-S8XNagKklznW-MjcRliwlUs-J_svACPVPoVlqlPxehkS_8_AWtioPhV__y
X_EEUeA3MQ8EHUFytVvo0FEcDatJgFx50IYKhQ9-EJ-PghTKMJZvsfTLlJ-Ec7Pt_ZVytOFHnwBLu_PlzQ_olyjRg8TvNnhTUlMm_q6ZXBu6Yl3xfYYXav7Z
CuSO5IJk2OpEVnLU_FoodiqeuBT8_xYn_ciJclptKliozQ3D3uPkmeS_DDioR_5KPt_o4-UtBJ2IhJHX1OWvnAPp-Ydfq_Zy_wepIPrEn23wXntBdbl_h_BF
jI_fNKsTNtAYv_pH441J-ocTqge8FrH0bGb8-rvQacWQ43BF5mAJxO7P_Gyr-CKVDjJZAY3CF2xy7FFRP2wH96cWhlzDGEqKWQGsz5IT7oMv7-kvAMhiUt_7
BlWH1V7i_a_hP5zfuZAd3Gp-Q03JRecHEFXZ9FYdIpifODPDCGRi-ObJmjeasExELrgjeGaEehiCNSLHJpQo-rzQe9DcoRdQrIBuwJU9bvCo7wxoawBWTrl5
djyS82dNl7g47nfaPJ_yvFwVw3Lb5xhOTHX45YCUdpONy7XVQTg6xmU0hjaKWRGcVZKiOupvvLNWTs9DmFp-9oO9IyTgZmMhvmMRq-fQ4DFnuW8cGp6AyhRL
vfz-0ff-LAupt-8eVQtM8kF8_N4JHjpAcjm1vDVLflT_kLXRL13_Kf8sgtm3ujA62iM85r9iFMZUr1G9XEqxzVl2W102mY2XvK85OQm32cichRt-_ZVqbiVv
RPMRNSKKbOs57j_KuRyfRg3ecdL8Jt1R6oYDVhY97h79wCC8cxchTDxTr7qaw7dUCohjdXkNmTXLDthSKaNpZOzcJR5zH38cXdJBVj2iukf_BWphadzguWoz
aS7HhZo4K6FqGmKIwMsHVaGK6H55thlR01BpPx-UF_yz4UFVxWuF3o1TL-7noAM3Z4VT3eMUEWdatoD5FrdaSka9iGkKMUhlu-K24lmxd_yQhHJxiSj6yVim
gQ8qKNHD1g3Me0d62Xu9BnmBI1j-94L2HY1xYlvV-ufRNplhjbipVzAgJI0I9FYtaiAd7BcWTroHO5RbkjH-5gTu_wFa_3lcH-Kpgi_rjfedxRSIfPxg69__
GFvNavqN7jH33enN4yIG1_WaMhjuYVn3-Ft6sQ_YWJpxNypVrV9S90K_DVzn_h-dE3-NF2LXVV2Tz5ybcyxCtSeerOu_WP-SbwgqVjYJDFidyBF_Mna5_a_W
fpwa89ieHNyEFobmoFa7qCEVb57G_nn-vW3s7yd_nv3_1m
}

!define DEVOPS_CADDY_SERVER(_color)                                 SPRITE_PUT(                                       devops_caddy_server, _color)
!define DEVOPS_CADDY_SERVER(_color, _scale)                         SPRITE_PUT(                                       devops_caddy_server, _color, _scale)
!define DEVOPS_CADDY_SERVER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS CADDY_SERVER,         devops_caddy_server, _color, _scale)
!define DEVOPS_CADDY_SERVER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS CADDY_SERVER,         devops_caddy_server, _color, _scale, _shape)
!define DEVOPS_CADDY_SERVER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS CADDY_SERVER, _label, devops_caddy_server, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS CADDY_SERVER>> White
