sprite $devops_developer_evil [189x256/16z] {
xDk9agCw4eNXJh7s4ZFl_xO3IdwZECW1rPZ4xgapw_NwMQKb0V7VVpe_gla7yT_uR_mt_Xl_ZJUp7pjvMxpD-L2yVHfUspqU_ustzy5_utduO_12zroB_yOd
nQiz7hypv0fxIbjx-bWyZtq4NXhPUEm3yRRWpylZyKRU28z5isbbjT-FrwWreCF7uDFxu9MdsMtuUeBmEW0rxuud-zt6fc1_8pofu3LlXD_on9uy1-pnUFWb
KUpDbBH4x7VZqTjMRvRbxPI6No0Ze4Wu_ga3UvPthIVxpPuEXd0ygIZStZsI-JIzrN8NlWJ1Iyr4xqdcq_HcbiZjU58Wi0zpuAE_2Q-fhgZWiVC3qE_qcflm
X5w37VxIS_QMvZlfu6burUFToOruUetgFnpVf7lngB-4Hm_-rVb_nfjd7sy73Xw3yAR9-7G0N_j0QhmgtzQy0c-rC5N-5JurERDVvPgJUCfXOdDOf8xXIm3r
75NS_40x9AaerkywZT-MAU2xh-FDbbeqwzFyuVnlQZmaV-59VEORqThcE9wMS3mrTBEIsod-k8UUTGQl-Sib5dfgmAy_eCNTzppX-fFuLQ-Kghxldk3fqqxr
um2lH3tzcfL_0hyJyFkL6VAYS-GtZbFoctWxzhBbxIeyUgbj5C-HkgU3_ZDddFEWq-MRd6mtCrGln7CijMbumPl_p4VwXVxhr-zVltujFo2_kSlgxLJvQZmp
DhsNXcEEsBok9va-st_FSVw4nyw4ZFmYF2sAAt_xKxm7-cHtFFOPZvuclnRlynumf_FbyYFfxmyxyKx3n8F_YfDK6pm3SHrcgOPFB4DTd-rabaCdsO_-8ZmJ
D_u6kUlhhynusAMRgPvXJ-DVYbzSm8bsMgCmo0rVikblxJeWX7y5tefWhk29sxjbPP8PtUCBhvGPb-3B0fEKUgkknmkzOtX8_0VG_5tBnrozIKZqPhQrUvSP
-dPcMosFSJ77zUi7NOIlL_xLTdVxy_rHyXTgqilnQg_hD_PX700HUNz-BIz6VnwlRVIyvRPux9cUxLMCL1CJ7prv2Tu4BthmQeTkGX5yqNSOjQ_5grtvF2rs
MjtiATuuGaRVf9VYzoyhbtPApsCTkAY7_1UZFutVj-kpd9pImyFdU3tAxFksCNifNkqwQwY10wo3U0Qk_yLuv-lmIjO0m9uEBpTo_OAXOcQlm6FVZpKjTjvo
38--xJfwt2lmz0kXrEsF_fuEpjRQStAn8nNoEJpPnpSopHp54muq-O0OF0sVPxklT9hwe9dqr-4rD5l6iqX-2KyCVB8eV54VpckasT-sF5CE3N0TNhUBkhrl
DnNmLwOqy4sAmzDfSd52lNCSlxx1BFSRz57ujgZ6ab_7EO9ddB8avybUy1UbN9zwgaApV784lGIEp93j0zyi-ZXyQhg1Wpx__gotNJnNVcXhGzya2y3JQyQV
ux3q-ARhACugVEtkDBLhZVee6k_LE5-_y9_WeIzsPaTA7CURMG2-wOQV4pxtLFHSEAdWjTbv8KqVYRSqutzD-5JWwnVSO6DVZrruobPypkNujlUMB_jj3jSV
JF56bodiVDez-2QLCuZhzHmyh-0IhOmDfleGFClhEE4xnwy34RxE-bPSkUAwbkARC7mtu_DCkUheEqM_8DWPqmQUHUCMF4slFH-ysZEoX8FFrMaClks61Tz8
TKxNgE7N9q0-y9p02SItu1_w9DjjP5SrzPlWstZyA7Wz7oXu_KsARs_34oFwi5vIKVoGZshkwJRau6b2nVS3-BZPPdFWV6ZBdxuOV1EBPv4wXpV7Cs8ZLjXX
dF7s4lnyidw8mbi5Vww-7cFmZDWFnTFfH_3Rx7cNWEyTRo7u7zvlFX1Fls6CdS3pMJxlXgomz9jYTZjySSAUuCSn2a-_KRmM1_lXU7Z2zp5u-asjRD_VVwwF
hdZx4OPlMl1w7e_YKUbQcjcK_46CrpXySOAK64TB7C9gJPn_c9NuzN9ocwBmPdA2j04_GpZr9uVVycDv9k_Jfvot6BoSOopn0zj7a-dURl0oRVMXPucvjw6u
_5wUEMCBgUUnGQw6RsTymFbvikZvteHUxaDzREnpkTj1blLftsEFmVCNvyAEd7lopYEfs3FU-ruOtcFC4uXMlklnpsshMy2not8HXryk2AAN4qnbs4LiMtk7
FH1FZR2sFJ6sK1FPGIshDFPmFAkZdCDZVbootiTKkNxiVxSWFFpVwvWjjkaHaws0LJfNKx17urcMH6_R6XEyskbomNZTsxTVs-loNDqW5uWNlKfhTWgZOGgT
vXvygM_GxxKy-w67df4UZFyZbnHaUw9WjjrT-beC7Sn_DXhPeIXuRNRlxzY3yRF72dtcSnZYI0CcB_MTk8Fk8msE5ZGhtrCRgCswVHxxlVZodd4k8sinO1nE
-Vqy8-VZxyNhpGlhSPGLVEZzP9_l_UA4rLlXSwF2ptwvNIJVD0ZUtW9lZiytOt8Z8xKaT-eyx7yStw9_Zm7hjsDo4od7WTmckznfIijpfzVD-4nttAoNktYv
ptGO_LdkTzJRTIBPMLvi4eFdH38ZzL725ZNZam9NM3b_0_tXz0PMS4wXx-WwDzGsCnqx_GGUUVvNM6-i2iHloXhCGmuyaMloi4OVDt2roDACpxDv0VfeFCsE
IQDiJQbFeNZiz9Ul1trmNMzcItTVn-a9_HXqebKFGqVi9_YFETEyKUnwF7Ty_po7N-xMHnzpPGHxRhRpUD_Qcs9Qdkr2DFmfVLwDirusXbovzs0j8F_Nthse
Dme2KG1U1KHj-lwlkvdCASHC_6GSeilMi_UhVoWQe3BQy2CF9Lxs_NpuZbOC3gqPCK713UqVngFJpC3RzOz1FZhEH_7eD9YAmcx4F_JpB6_xgl_sXDiqvbhu
DC72_VWVnbF3OpuKg-3HSQZfFugdkBeDdoeHINpzyiMzZtGiSRhQBpZeDp9cFFYyN-GB-D8KNEg_RZE_KTN4GutmDNwcnHVeQuHQ_dQZVkD5GNChdio8SvuQ
_dPZVOMCz1tZvv5d9k856ATxJqMdoFxz_NsxznnBCf-lbDGU4-bzBgjentUuuoGLXvi9VpzKUUQj03_Js3XuZeD-dp-DtOcUIwnDE198LTf-pik0Gq2MYvc6
kUgoFfmuk2bv7N0Q4rxSVcUvhoP6wFFifr8MizcO2uUHteZ7f8dmWGB__WnhmP-5V7APHfbfbG2VhpaetWDF0_nA-E2F2vQTZVWEUBAxu-9HKw4A_XxW3zFN
nlS7XPk-HJpqXB_muMWy-dmbV3mKxu2FbV3nQ7ne73_6u7ytthU2l_0N_iBtJUDfcA74N_Yn7ZwUWh_mjA3o-_2EqYBUFKSv5_ady9voAdv0fRizQm2K1r-B
ZoVY7Up3FT0tWy_q67_qhX5yikUd8RM2Xts07Mrlm4D-21vsoA7NuSEPUDW7Ij9hyCDvU3Jy40AwVbFua2Ompvke6i2xXESAhZthsy3thUCzyEbfHmtXNPgq
ttDodnztuAcrKRMX8JpqXC-VTzvvgNHcV53ZqUifJxL3cy6_FlWk-7RmULX9ONf3UEZ3NPxjUdnt1XvwptJOMy1303xehcy7BvS-JiBxXBUadPQtuyDv-0j_
uVs5txNGwcfCHix2-xvh6E_wvl1ubyAjdD0qWkzRnSEUy4vKLg-ETrK3-qyz41i-BF7rZE-3vKqykqUFVodA27nTOKeGmUFpkUbxyblnmHTYzDRNOB_WDF91
btnbtHfkXI7WqFP8xzljoHEslw18bmuFE_RjnZXKpzg6DU19BnxrfDjZZurxs9c2QBVIRObXJbaS9JvNpYxlCu7jxtSMRTKYYNlovCUhu8-0L-6vo_0cPqho
YcoOBLqeOlEg3jyb-pHp4bHhjPt8Op5UF15-IbcHba0DbzE1zmtpwFYHekiCsz7ap1REGg5fd10VrqoSi8Lub6MWCFqDMIghnzyLT9dEktoByDJmTAhcwWOh
ZLwXfVldlC6ZoolmGvm8p_r6T7Xz_p5qcptuSLgvpEZFsU3t9L0JqWXDXqTXoOLQylLNzA09XiPbRx3oQMxno0mo4IFQljFWIU_z-Y1mEwC-KQQy4AruF8MZ
U6JjdL11rxuICQOim2EvehQS5uMKpL7ANZdP0z7LJtYNHS4HbwEP9SbizVeGn7CtTNYaUydETGHV78U8IhKwl4odJByt7MT7sOy_cdGV2UGsV7qrkl7xq9_c
2FpfMM6VBxpm_sl-0W
}

!define DEVOPS_DEVELOPER_EVIL(_color)                                 SPRITE_PUT(                                         devops_developer_evil, _color)
!define DEVOPS_DEVELOPER_EVIL(_color, _scale)                         SPRITE_PUT(                                         devops_developer_evil, _color, _scale)
!define DEVOPS_DEVELOPER_EVIL(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS DEVELOPER_EVIL,         devops_developer_evil, _color, _scale)
!define DEVOPS_DEVELOPER_EVIL(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS DEVELOPER_EVIL,         devops_developer_evil, _color, _scale, _shape)
!define DEVOPS_DEVELOPER_EVIL(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS DEVELOPER_EVIL, _label, devops_developer_evil, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS DEVELOPER_EVIL>> White
