sprite $devops_developer_evil [71x96/16z] {
vPW7WiCe34L7xKlWpFslky4sQPWif6nzqmildwxavty1VSP27x5yKFE-hbhulL3yASth5dhir6kMCxUQ6cRUmrnx8ro_Vqcq9Y9HCrKft-wyCjLixWxOEKu9
M3Mp2Bm0uxVMtgvno1kZSwDHcj-jHBnFpw66LRTmn2izwNLEs1eDRRCdPzJCj3gVGRh5iVglnAAgy8XD3xCH3LlneFwh6CvuoikIaqC7bm3nllxs0IXP42dd
dC81D55w6YAMcu4a4gG8Hv4R8bnvyEWZkj5e99UzBqIida9ey3Wldirexf3x1Hgkz6TTklXM3QatRSZ2PVHIsB8eZ8zs37ZceZkqhFOISHHsvzuEbc4BcHiH
7MNcYPD4ob1A4x_yXinqLAFPwCUWVDyVAq44DcWXP5stF8HkHzTaxJ1eT82BXjW0Kxv4CQOrwgX6FCaUm26x1LPQpsiAT7E7rSO67jVqAoXp6TDmqNH136h8
dcYeUOmk6l8iAWzgPD-0p4oFWoCHDAWXjJMEkXlNPRC59BZH-0x7TdV1OQfgmAxX8Xw5u4fRYde9CgqMXKpL5w5ruPtXVMWOBZGikJ-AYIxoEZ3pdlkh0Vmp
YTZzGSVchfEMsiwaxatrd6gMIKsiHO0mirZaKtwX4YD5d4avfVNhIXZFISGymhsshoutdh8WmYjttqvqZ3HI-26HN4SzMkBtD3a6yx0loNj4Nfo7D4Wvl4jQ
ierOA9OK_YJE2JJmT4RpAKMViwO_EjUx4N7wNLhoXUKtkwdsLGm7V5svBN4XXPi1qWtZRceZg26qhu6COiyqneE8FaqphB6lQ_G_gOalQkJCWIRDQSG0dTHu
kymCxj37F88vZGMAvqsDmeKOU3kDAykSniARVrU70JQbIIxSU02ey9iQ5jNMmeAOq5J-5aryHAFXRspDpsiWpD91Rp5FOEeKUobChGjMhWNAyKiwWdGwvShD
LUaFrBipSWAr9sZAESMr8JQiYo_97ZNiUKc-jTA2tC47M6w7MMBjoINCRHAzS3VWo27jD1dEU4k4z-f9uyvBajlZNEQbYWvmDosMFjJ23KJqym_a3m
}

!define DEVOPS_DEVELOPER_EVIL(_color)                                 SPRITE_PUT(                                         devops_developer_evil, _color)
!define DEVOPS_DEVELOPER_EVIL(_color, _scale)                         SPRITE_PUT(                                         devops_developer_evil, _color, _scale)
!define DEVOPS_DEVELOPER_EVIL(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS DEVELOPER_EVIL,         devops_developer_evil, _color, _scale)
!define DEVOPS_DEVELOPER_EVIL(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS DEVELOPER_EVIL,         devops_developer_evil, _color, _scale, _shape)
!define DEVOPS_DEVELOPER_EVIL(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS DEVELOPER_EVIL, _label, devops_developer_evil, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS DEVELOPER_EVIL>> White
