sprite $devops_developer_happy [71x96/16z] {
xPY7igiw34MlwfPiUF__kG_Zz10mStjPfuQoHjjj35_-DbZeMsZ4JRdzGoow82BdlKIAW0aJYpaYu6vyDe-QkJiomnlMgj5prP0uWDKopLC6N8MfSIwF0cvc
7dNk6ckUy-t2H6o8M7MEBBM4ysbFpsKz2ujvP2QCpri2Iiy7ycn1f73brm4W1iWfYzjMtxAwAmrhr9q_P0LarCFTied6Q2usrvsJwMFb2FRoIuQEMCX2zazZ
f1m5k9V_s5iagjnZHV90CHv6goKIyZZwmcZz5wbqh8aGQXQOtqUj8jmlRMOZWvaZsaNcocnmwWSzZCLTUXT01ZIW5gqbO41wfDKdxjITenhfGqTxAvEvzZ_S
-qe7DDxgq5u6zrQzz19tgOveuEjqfgU3z3pzPQ33RUVik0PEHneVql3XrEK1pL79EhGcEwodOjvEvw4qFZL9JMyYkZivKeujzq4g5k7AHCJgjmMHBEDg7CfE
OWx0tMtX6aGoRN0HXT7rtyWCkDuZUGKFI7hwguU85-v3cdnm3UtnY_FscHZffdlb1KBl5krBuBYdr3Hwtnrubu_25YMX_7143QwdjnGQqvGcpBJ0B1Qrzcbo
LlFVN3EZaPcbpdF5wSrVb6cgjPJQA8sw74W_4OirwZILR9ILp5PIdUOA7hQWrDeaBKudLhBKgOQCMGIbIMABN3oGGKl9-4IMgJWD9Dgrh2rKZ8R6R-nI1ff7
ivRO9qizYaK-rJpKJC47cM8k6GUKAVLp8GqhSyqZobJ0jB0XwSzFMUTwfRnII-rCKt5tCtqJiSCN46iax10hlh2nrPQ0wHNPGsyWz4q3bokyortecne-ow-c
iM-YoM-YmG_G_DFmg4P4LRvM8sA8CFdAKEg00oPVfx60iWBwjHgZjbMphvjJ5Yx4NwrHXui1-dKBXQWZmbM-GjCzvgRoarQ_Vnhy3Xev1TkRXZKJZyGcU28I
9dmpaOYXR-ntAMzamAyLaPN6XusDxu8eaAwHc6lJMaFlo03g9MwQcl1kwPvnbTuVXAc_SSz6Z_T0NDZE2EGK_D36QWk-WZTY3zlQa7OUjsVQi8w_OgTUzjDd
llo2_0y
}

!define DEVOPS_DEVELOPER_HAPPY(_color)                                 SPRITE_PUT(                                          devops_developer_happy, _color)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale)                         SPRITE_PUT(                                          devops_developer_happy, _color, _scale)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS DEVELOPER_HAPPY,         devops_developer_happy, _color, _scale)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS DEVELOPER_HAPPY,         devops_developer_happy, _color, _scale, _shape)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS DEVELOPER_HAPPY, _label, devops_developer_happy, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS DEVELOPER_HAPPY>> White
