sprite $devops_developer_happy [189x256/16z] {
xDG7aeCm38LXm1QztF-s-ooUBTYUQOfd-BUN99_hyLfFJqzDW_TlgWI_rOnVcX-g2j-YIl6GTrq7VftuBeHmuvS_fB_4Iq6p_tK_iB03g2IQ34-zqTy6VnHy
597iVykPDzILfyGeFHA1ZInyRjMkT3cp4RZZgGSn03yW-AFEgaQwI6-9fdflV356sCTn19-RvqOVIda4aLFlXQSRmIYALtrFVx1PlzFzyISyb1rDOXc1vDzQ
UTlZdNOVl6qAZKYrJoaCu3FR-wgysBFSW8e7VLxGF8ssKnHECgFT0y_hvKkmWxwksxekQVP7ufL-Ygt62y-hKRlQ4txTqBhCrCDkzy_LxeY_stbUQKThqjyl
7-ZDx8Tl2rvfcatyckYS-V8lv9lUUTl82UT5gTTyFgxBp4sJw_C870vgmPk-2oNeOH_PbDcwaJYayvSVnDe9Zjim38LXQAlH-r-uYdxvXMOzniG1PMATHVKN
cgAMpZRt3W_ZTVhmowij9Tx7U1qZ-WU0FrRcfye6FO7TJW0rzShc0BxqP3y_Yy_J3X3vP6T2cnlLJjTFVda8xxV2qDdA7zOY-FXdNPdIToV6rNZjXBMD9x23
vvkQrCpd_lle7yHt4oMnlNEP1bVuMf9sSTqFdm6qdMVmfcIWdnMnVqrpW4vSQItUbpl5hhN7uqsuavNqw_7OCOX-XTT7Vh-0rRct2-n-NI2wuhf1cUqq4sKn
Ni_Nup_0CzeCNuENORUtJrDdZc5AVbxJxvrTFUOpF5Ntdkxbg0yl6kmtddke_37XMQuMulDUC_TwnJi57IzzE5v5Sp9LR-HWwlK6u_5fJpnsnTs3y6kVLaiy
FerGuetzRjEgw5M0qNZQHEDLVuUdSFf6pHPEO9EKNM_wLfEsXTFnlN1KWx7BqzxXlyPJE1rFwkFnexzvku-ByJvIQHkfB-5u6iHOqx_7A_KzHk6CvIiGNsfp
ZVbRFEtoLJYfsmFnF8ft_7lyw54NgM_RI7tPhmBZrbRmERc3-E4QydommgU-adh-qK0yUoajhkPmoZNaJvcVPwyH6YizSpOQNoh7DmFGjLDpcvtJCs_plyLs
e-F_Rgr4betPn7QBjUzN23d_YC-vpdCtUjzmNlWSW-zOdZAHmayxtQvPridnXIiUzBxNK_GZ0l0yP1j6uNLt8xt3Exlkfqxn9GVXU_0GgWOyg16RFrVyTmBO
Y1FzwusEJi-TUSXqJQNN9ljN7Ytxk8gtBFZ2bGPzVao_GezMlstxRMTGemIFZ-_CWtWFfmUlWT0R5zx-59OAWrVYpVQuXsx1F3uDsxZNhlFtq1lyx0Ibwqi9
mgifg7NgfZ9d2RJO71FV-Fz0wOLN3oOBqNWb30PDObOs7mwyPgkA8YNfi_GQkWglSqajUX52Jln-jzTObXCnzKgzEcayVdDuCgXvrqEJqPnv-sJLCDq-9ADV
XIy717WHsjv9EbjuhFbuuTQAgvkb-Aw2Qhj63uzdstQeaie6pUBhm7TzhN6jSciMtrpNC7y697nfeivW2-tnh18r4ByPV2uY2D43kshUR_QnQbylV0l7zmS8
FmYW53ehERp_DVCHDNyecsNu4IBu07_-HyRc8pfyMO5NbY_nypDwkmyMWzXkKzhXy7r11-ygwL4yYn1unIMUCF9B_9yOF743x-CQt-Bn9Vtockm3V5w4Ro7u
Ki7dIFnsWRyH3bz2yJfinE03Zu43RtlbztvZx_WAFkpg0ppwVyITXuvZAHH4rKgFuDt__zmH75ogHsFfoUBIfRWxwPWfC3SnE-6nV1WyjY5IsWtVsC_0Awad
0V2nLNNz5S3_jsECN6Si_4K5zjVD2lQ7yF_Vu1K44ib79bfPUeVNvUin_ClW-NrJ7Bod1pnPvut5qCztiFNbfWfUYLRIY4tn-VaRMxk5CxObzeb-oE3zaAU6
pww9WLTQRYJy9BgkR3fXYIvZ6RmLabDiPSINVeAdOBFY7znUZXByqPgKAdS6VoynS5Z3FyZVlRWZXU3mxOVvFNi5FnPU9T_BhiLpuQFXavM4VCm6T3ay8gzp
TNZzde7TPGr-DhsNd3ITWpIzfhosuCqqM3uKNgxtue3NCo-VwvfblyZWXsdOHx7mk5wDpquFFWDsoSUd09-IDxxm-TQp4jk6Qwse1Wy-vXcwpzRD-G_PC1Kj
V3oy6cdjG9oiZtm36FcSQyebKyOyr6FcbmINJx_CmrqVEpvoKVKx69uiHRVrJ2_l-wGzv2jqiUkCFzHNINEI-VvkVjCwNQQmifyqCaqql2vI76zEBoPfJJxt
9QQ37Qq4FYdv0UToNATVioVOmwTZvsx8KdAQjwqTJBzXFhBh7X-f-quhZRvjM-4_XnUxvu4EmVUOAfSA_J8WbrRewjBXn3qyCyALXBL_E39qZnf7O03xINZz
jUSoy9t-yUpxTNvQPwQlx5iWLfFTDiNfx3QRUHuUUgoJDQAxXaTw5CI6f0wk-tnWyEtEZAwne8LTZ9nuw-zUFw3vOC87viSbkwYPZe3Wx4CbwpcrRfsgZOjv
PdLqZlRC1xN8v3ZyZrkdLDuv60kw4c4uhsdO3ZSTnFURGeFdVOosf2Faa_I2p40V7rCM-slutE31L_0dsUi7UiHajVP73I_R00zzytvJScLK2knyIWy7piEp
2PkHzR3AgpRwePm5BTL6tuJ5X7yUddYLmmOaPr-hll4h-4P_UdmTT1QqDXcaz86_DlphuAbpPmVT8F7AXBzoaPO_ByBuGuyYTNGyu7JYbx9aEvVJLVHdu7tP
PO31bv81pkXsza3FnZrrwhpPTIde4f_WLafITdnzOGN2p_d5Qw0lLZOjqLtPyIl9lXFmkeo9tU6UwqvFYIuUNZ68iQTl9FgAxqKVXExiPKB_chwfHCuYJ-nw
ekbRThUEquV2mxu5tV6vAaGbdsRFDCtattkdGcyJ3q6TJdZ6pRvdxKlVjADrFImldyjETkXpfqzNJBQu_PRKZ_Qo-zghC1K0Fwev_36mRyGd_N3lQTXyZ-GQ
gRswaRuqSU9iXeV-pLvXZw5dwRV3DzECKsqtkxviUqap0BwVDB37mTUojnxhRM0vXXru78bl0k1JURs2u5E7Rp7jrak2ksPSNoFWa-1P-dtmd3LNxbd6EFXI
Mpp-_OCborAskcBgVmQVzod9DrKj5Clg-HSFjAihvWLyY5XvNIxLxli5_5pQu5Pp0BwEwvdhERpGlIv0n3roy15I7egwWzSddfVSn6x_n0FpyYcF55SCVVdN
tfteHWx2O1pV8M1IzVtVTsLX_KcHcC3aAYhVtaURNn0vczZ9RlhWStZvi1dF4wgImisnI_6w09sNsxB68NYFllcEM5bKtexVvEIvRtwrhp4AeTXRAvvtuIsK
yzUibuK5v0KNjJLQozl5BPvU2h4QwKZSYP18NPI6Qrjcl5YfOIAMS65O114UnDFquUdnq9Xb9xupu9jUntYzjbC-5B2RKkgZzE6zbIzwEEfe7_doMUUdeqF_
CTuz6yDBDrx-DdxY8_W1vtnSE_6ltuENYVyi4xzA-9NuYP_uYP_uYP_uhuc_DnC_yHFlt0FuYNTtunVDQNXt2nuu6GUFV7DhV22yoNF5csM8EO-TfkjM2N6G
lSrYTlh5ehy7xmxYhQKXUFGtdCyVmpDb24t03-3l6ddlVxOeY9Bq0uoyjKSsigUZvp3ucBVJh1y4BugtZpRz27ZJHhDJE9zs2uFWrMxjICV3XuotbHa1dx1C
6-V3KNmKV-VUXdx7ZZa_35xGiwyS0yyHbeOxTDmP0Rzj9y_3ItuP0r-UcScHSvjmAvvpOl1c7m1VZ3tsGV2CVR3fZdsGfpv-N81Z7mJlAhS-1i3ZjmpziD3V
nSle-33nlPduE11-uYT-ucLml7iAF_6lH_0Jlpo0Nzwa6I-Nu9ShquCloj-3VphR_RopuhkaXazVLWh1MyBDyHQrhmoZsj_X6VXKmhQUU7OgIrbNTV08mnOF
6phr42cByLGYhn2lqVYc1r_AS-7Ixw9GwRdvQejLAbT-yfiUFFHyatIrqcZF1NlwlV8fcWw-x0cb4utAVAT9ZcPDiHrFWQVN4hMvgiiyPpwtX_zjVFJWQG51
OCQUo6LHlPfoYR-oZTct1lak9no9hoUKeHPsYQUmdLOYoGLiSDUMVJXzBxa7qObXPKmAl5EyLGw2tgvThexgz_1gPzGRwVUTvIXUh3zVYL-j0dwUw8Scp1KZ
NrJR-j7NpRPJ8Yq9JV77OaVEX6VaYzvvAQVkji_OLwKgDLPYReilEvTa_DS7wLszrfsyxYWhU2gosnb2PVpVYf7l9NwIL2oCMgZL4pCVD6sdxc0wfvd-j986
keR-LU2tUkLRgeSxsKqyAULgqNIkn3FsgdT5BQqY-uTqSjxwwKVHyh4wyjw_tlL3QxkDiBzUqXVQjwhTqj-jljg-fMcjV5D2ZYTSmXx05tdjnvqLgiaru8_d
TMxQA_dzkpm7s4_Y3mux-B-McPd_
}

!define DEVOPS_DEVELOPER_HAPPY(_color)                                 SPRITE_PUT(                                          devops_developer_happy, _color)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale)                         SPRITE_PUT(                                          devops_developer_happy, _color, _scale)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS DEVELOPER_HAPPY,         devops_developer_happy, _color, _scale)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS DEVELOPER_HAPPY,         devops_developer_happy, _color, _scale, _shape)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS DEVELOPER_HAPPY, _label, devops_developer_happy, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS DEVELOPER_HAPPY>> White
