sprite $devops_developer_happy [189x256/16z] {
xDS7TkGW48JXDQ9HllzrjsZzhDYStTWpzVo2ymSgUfWFhvbddddccMTUbBTBJoczKRxiqpIzKNwrv-pyh_mltyvG-6ncpVzbdwOlCrB79CnM53FnSK6NF2js
9HD-QfYDBxCYVwOyDzsit36FwyFPYXkpxCkoYD_AqzFdJsahoC5RZpkvqHpl-e9_Wgvqz7XyVnHfT2Es5HXVxT9ghuz0Uzzd3qYthpLQm9TiJYf9SNZHaHS2
NlHjLxPrkPlYSCWas9vnzv5TzECuZsElkx-0TxgBkyIFHgMtL_nnAiU-ePUzpPzuElZFxPnNxCfHzU0B-1IBRdRmbC9pR_nHwUny-v6EFyXLve8pA7tC-t6j
sIXDIs45GrmyVKwsI2_xGjR6zYAn9Bx8tM6KTnzVlBpsLU9v-EFmh2ly4RhZkUobLxUXdhdNm4S_0Xy_vKSEEn4kDnm7pp8A7pjqiwzUYPA2drvHVVJXzghg
h_7AbyLY1QNm0EhFem-TE5Sbvf_ifQ_0_Sw_Ve6n4rsPNvc0yDlHRiKFjaj1Otxz4brAhDxj67w53hz_0EYZx8ePz5-D_FnkpCYaCt_sx_djxjU3zlqZyMQY
B2iC0j5gihx__-4t8ROLoLr7uLBhx2TjIm2TTzjeo28-wKFPwVQxftkizi1av-_UcB6rOxkA59wU4ToJe3RIHvhcYKm18NsSSq3XoNwp4UvzQ8yeTWeFtFVV
fAS1Wp9DkN-eQPp-hzCuKUmyqlUDqqTxbGM8W2yFxeoG_8AFabxpsuExEb9fK_g42E4LdaVv4UbxdyRn5xuycfYPBeTn427yOyUOwRAfz0an3KWMc0xl9sD8
7B6doq7lxHlMKbVNpDveZY6_sTqq133qyvprXXzxAor_dRcojlzkFBLt083aSJsbbGHu2q_B6okrhtCGHFBHTvF-cd06lFZ2Lq8QzfdjpCyRPtF4izEdGjFx
qFD7sfMH3P6X_voTywaFuPEumhE0nGgbqKnViNS0ZR7HY-QRMdpXQp_gLrpPTHI_Op7MQq2rxcU7flhMN4S9o1F-_0b8FXhnLnZw_LpXHV6w3JQHNBjPCX3U
biUlEATW5W3Arjj0FzvdreXqP09NU2O5mfDT12AMm0glxnCvwR5lVZa2_XIC8euG7doJ2BcgutsaNq31ZqR1iozXxg72rhbS5Aj6qe_FxJLJyeLl1dvH4BeO
mb_1AZ-sJ1-mq4V1fnM2y4GeMoQXJP9S1sub6T-4mPDAKTUiCSB0pxADN7ogv2jyTeUlcYaN-6AoHXeXnZQ5g0oMq1jyyOLl2xmo68Dljm61f68NoRTH27Tu
_W2R2yhCOAzauUtRp181KVWS2A-1TsuoDaiCXwVA-FPZbFcx-tTyuLEvx8BVe1id_J6yRa9lRE4a_mw-4jw5dl0Ekd2tzePF3l0I15zSu5CEW6-kyCaLtg7T
YOFtwHWuTCiXyF0HtX_UGHyeUmXySO0lplTG4Bxn2knp_wqxcq1FUFbikC4IzyRtzYZuRE65PU_RHvHZnCZvF2ksz9-OCq6o6uI1Q7OZuTp_kBFGgbUaiAVY
Rv3x07-UDOrOX53R5kOvMroUv1hLy5S6dcCv_ao_MUgw4ux1STPn8RbG6LaU-W7-zwVWXmBkeHoLNPEYSXVmY1A3aZNnx-_YSeGm_cPKyDV2K_BTCFrO-FZ4
RoUgaEic7sTfHtNO1h-yYDnSNmRJzoKdkdCakjUOGOzCOvm7hNTzmnZewT-XTG7XcW5UfacvUy3HraXF5y1MQD9f4ZY7DsFWBUFE2gwdE33WopoXlhUEtkFH
XiK9V4BeXrNKO7te6G0ZEMTDvaOPCuF-hDxTTRyGzI7eGwPngj_BuPKVJjOYj7nBjAeVaC5EZi-WvtBIyQJpoOzOqPmTOXKprRupq5b8cPqlOh-Z_xcNIAP9
KOjOkPNWO2-vxDo6TBV2iBt9dWNFI7DtQyEMkBt0lgN6dJ6xcLVHNuqS4u9wrLBPcHdDtUcplDvqeIaicvr_ktdWNw6d1FvSWoFqLUDM41VOXSv7Fq4lwrXO
1_wlMmI79gb7w3MxTnt6Ny907kWFijDlq-63SugkotJQ43p8ZdsRTIe3LykPmqTabDfD7_fy7tlGUzKx1n5GbcH1JJzolAPnOOGdh1JQAnDxLTAFBH_Y1Pb0
Zy_4Oa_36yzxyCP4Bru_u14JOl-uRGGl-kgk7ljU9hcBNL_9Tk0HaJys7bRPwoTzo0neL6lTc-guhiX_dKTZq0C9zb7G1tuLFlJPxA2tWDPFTP3eXBzMfQU7
Mf65ta7AAp1AHouY_COsFZti3LqU41ry2734o5LsXJu_x1WW-4e1S4JlSe_eDN39EadiB0gQu0FkI0LPZy-4bRYBsW9zZEn8F-Pzy4LVA78bBMTW1-wI_gMd
6I9f3zApbrS4VPNleKzWztleq3T5pabXvucc6-nO9uSUzW7zFhuRTQxrdX5xkI_ZcSALFLuqhiWp1lkSsBiRK-swStdpQUpGMwDVPXpgHmFxjDXJc5fa-9YR
fhAJCzrjKKcGAmAovrHsdfTJnba37-mLzWNqYqBVAjLU1Lyc2zjp0M5-uCM-3huw2MVwnJw3VG6y78blPiCNt_SLy4oq-rufXKztJInVLy0Nu0dzr9jncxLJ
ndNmNlVgipTLt8gfVpjucoL-hi7FzWstOdR1hv4YFodLV-_qGwkQ1FWQoxDUBv3_GEr8SkCCVeKuXugwG__S-2i5QYxDg5--M1nnhQ4FTj6_jtSUkBB2C1GL
9BR3x7_1Ny2Lmn_HJ1th-RnUEK6cmpLJhk3XG-FPZG4UqPDZTyhZFCYdcyOQ4-KCUsCqtpHK7jllIdSfyE_TYmWhvh0tVHOU8Cv_fDo6Jc0wOMkSA1xlhFAr
bu8imWPa0rP4Sr4i5S-86bOOq8te91IkD-APvOaeMqWRP2EGHztOIfuCOXVoRIziay-8BtgRZ4X5kppzW3on79PltmNoR9RdloqVyW9vbpLlNbKsloFF8N-C
a2zCFoaVyY4VyY4VyY7VXVprX7p8Xtp8XtpgyIYVfdYIXtaUWBqRUPXhueqVURWJiGQVmzw1V8Axzek5_LFoxKbvj3HKUTWVb2-FogDa5CJEkv3FUTgY06MV
NSYZFJAKitRqT2ClTJcjzaxakPV7NyFUWpni1UwD9Wq9wiQ9_E2EDdtkvAdAOp39IytNicapdPKNpi_9K-tMt6hDkv5djTTrfGjvR65XZwqK_fS7-MaxUU8H
oic7_FUUsU1-L9wUauSzAWV0tOFyzxo7knjvp7j2kSFTpLqV_ns0mzs1F9WvzU567lx0zSr2VrUUlSjJo5i9UN4a7_8X7_BiNBvzIpxacrVaGpwz89zMs2tF
jyYdExb2_cNCwtbDzXSXoe0U9eFUlOO6xslyc5d62Djbv6eMfb9Axq4usRdktsWU8c8ntaFq4U8YijOoevhNuD9fIi3dShfz8AcyQCkFUNlqgK1wCABHtWFk
-7pGNmbDnnFtU5pzSwbxTvOoihJYGNocPdCjJhDSWUn7Vnlwi9zh0Q6efbZWs-ZjkmwHhhDnKoXqc6_gq1doClIDPc7FoZTD6f98Qe2DUXkcRSFsa3inbsus
PGxvDKWEKlNzjkbkUliD-TvTrNcd-dDxERqyKshcv0iIy4KOd2gOE-OyqhPc-xfXELLu3xIBV0viEKVvPZQANS2bg-qhrbLZIWqYvY0_sxcaodS7i0wFju5J
zrcKHo9xnZ3dv_-giPfl8KSOmiBcir1XFxq6oOgie3B6CklV6OPJ1bRxLqqxSYvkxdWJkOYPOQsV1Mb0Mzct3QHPhXiVBgRR4fA-sNSQONjSR4FRjyBz6Cqy
xHn7qtbcDm_QjlWwcctQQy3fWsTfBW7YRn04GV0F
}

!define DEVOPS_DEVELOPER_HAPPY(_color)                                 SPRITE_PUT(                                          devops_developer_happy, _color)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale)                         SPRITE_PUT(                                          devops_developer_happy, _color, _scale)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS DEVELOPER_HAPPY,         devops_developer_happy, _color, _scale)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS DEVELOPER_HAPPY,         devops_developer_happy, _color, _scale, _shape)
!define DEVOPS_DEVELOPER_HAPPY(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS DEVELOPER_HAPPY, _label, devops_developer_happy, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS DEVELOPER_HAPPY>> White
