sprite $devops_docker_logo [96x96/16z] {
xPc7ikCw2413X_V_7_p62YwZs1DxXBQVtNilQSS4OPJokWkAnNyDPtWzvP__dz__cFnnjdzcVSAcr0TOVI5Sv_Y9HHjCwQy5AHdLmmNO84GOqoDnWmZNa0cF
yLWTMCtDp5IOHPV8JPbOxOqE5GX8FVjSHMoBMVV-B_ARYCMP7y-NxN7-J_n0X0FraM_r8L76UVK7DZV6clh0wQCYb61I_i1B9gu4K_mvlSC5x_lZGN-YjXjl
L0WeDv8uv1ykh7Oz_u7oHXUyDn_St_F1pFVva35z-jdpuCfmOz0tc10FCV4Q8tpcb3MzN07OGQG6uZ7UGa8ut3j7hYp-N85J_VRWVH3tCMqn82K8kMQRtmXE
5rKRmaJ7cDTu2JDcGivG6RUUI-pgx0vVK64nRvWmwnwB-Xjbohk4A_L-5pmxFRQUL_astsoFmrP_R7vbmWM0I__r_4-_hJeZwFpXkj1Q3kxdhrt-cx-lJuIx
BxzC6Q7IdyIAcn9-yyTZVv8JfYZ_V7n7k3tldzw_W9V-uVxPjvUUPklz_j3Fn_dSuyh3zKd1wG8RupP_hA72n6lCHApMQ5UlCI6hPPm2ElFlkzbX82AUnx27
7_FpXP_rpxq00CUXLhmUNzBdKKH4pKxqqQglDefxTFBZJkaUmvoUMYPjSVFcKjhqp6scMXzDha9DN-uFDzNZrbAhpzrniIUr-fm8INrzmWWc-YEqIx-sFyEa
ztkfNmbwlnVwFTElzr--yx1IFxqc-iCLF_ngCQSyYPZNhIwT-DNdf9-mbFcLJZ_sy3ddRe9i5VRBpnw0BEPKFq6Dcjwdwy-jIzB72pzR5AGl2DUVnrJlMts1
vlHc0coraw67DCgthRw3flHE0gmnMFnCVyOAHpSOAcT4hwzVWVxRdk9pBBnVsz8X4P7whv1wpCe-UzIVwpNrenKQr-VtYm_8DuYt0NfoW71D_Om3H5X-2ltq
01vtx9wrUGWWgyUjqcJoJy7jALodhbrf7Zy5YxYsAnF2uFV8QkOUZSNQS7SpbRIF08Z4edc8rQsBcn3IFdg8um66ClyV
}

!define DEVOPS_DOCKER_LOGO(_color)                                 SPRITE_PUT(                                      devops_docker_logo, _color)
!define DEVOPS_DOCKER_LOGO(_color, _scale)                         SPRITE_PUT(                                      devops_docker_logo, _color, _scale)
!define DEVOPS_DOCKER_LOGO(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS DOCKER_LOGO,         devops_docker_logo, _color, _scale)
!define DEVOPS_DOCKER_LOGO(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS DOCKER_LOGO,         devops_docker_logo, _color, _scale, _shape)
!define DEVOPS_DOCKER_LOGO(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS DOCKER_LOGO, _label, devops_docker_logo, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS DOCKER_LOGO>> White
