sprite $devops_docker_logo [256x256/16z] {
xDL5eWGX34NHUA2-zFvNs-xkPUzE6Hqiaqz5Ps9HyyXIQsqEgoN3JOMPpZRfJV333p_yyCCFF_pmmmy__F333p_yyCDVUkIdDxNpmrz7xOSV_cRCVlWn_phl
fm_4B6l_igOkMl8VzzE5kk_VRS2kilIBC0tSltm0MHRDrOjsV1KUXJyoinoK6MFm4ukgkKT47hRaZy3FecO-BmvpDrDvrR-hktvHDJC_odRyOVkN6w1saYxv
e_2BdaiM_Ziyz52VylDfrvTdv9o9plCe34MLfDdU_uMdOav4SaK_5tVvY_7iSnMQOmWOCEJ_FzwjZDy8__22mJyMy5lXJmmbWy-GnpRht_w2pwmFv5FZbzxl
Rcry_-KE70RO3LdLUSu3mA_owm0k4SmnX2TZU1SzgMEMPuH3lyjjy1F1hXSZX4k6B3eUIF16_FkR_E0pWv4938YPVbCT5Rcatqn-VrJoFlwfE8Dd2fSioPlg
E61c-hkBVdyyHS0Dy1TMi21OmB_BgkE0BAkU6q03_E0B8FnhTey08Xlhdm7uaR_8F_HS_uIM7V93Jtpz6_pBr_d7aVYvFtv2iXHy6ZEeVyg_dVctj_8JaDzk
EA0hVbvfNfQPvplZ9oBL7OJu_Bgb90w8pQylPCwXi9ZyQKWvYXZxuDVtsMKE5OlVV1zrG7n-JIZX7MwKqW6_levq0Ltmv-gNPPGU-3MVB2UIMFmsxQ_mgob_
_ZKQm2hbEFb_OlvllytrPV8Oy4L-0E1VZFKlv3VnoylW00hgWbzAamRmZzh__eNsp-Ulxo8Du4FyIg3h_ohh-h_gx-MdgC_nhuK4Jl0pONd_vwuwyZzBDi1V
6ce8WZx0VpX0xBJ_Lv2JTvAA0zJytVy6_tCDm0UUBV4dGZNmTViN0tygoV_ldiwkvZylnQ5Mka2FMVlVQaS208WbcUo0kVHumg_YP-fVuD-tJ_AFC8X1ZmVA
yfWUHXQTxNy_ltQs5FTcVZF_nPSUa_1hcxzq_vzk0F0F82eTzC8ezAXbVO3V4ufe0tY9tqxWczJWI-93MTBVL1_-D8jV6u2V7ygpFSq_-FdrD_JtJNuT0dty
_7pH15y9iCUou8iC-UFVjlard7Rn6u357WxzOG-dibgInRdouy8_2hys0FYz8rmsHIoDSEXPLXt2B8kEp6_RmuFDly3lmfyV3V0Im_1F43J_yP0NbLNF3a0-
s_6uya-JP6Bf1y0JxW1lNR0hmysA_-QI_ZZ-8tloa55LJmwGpz_WlpduATSHu3lZVmm7fDz6blc1yCjCtB-UeFYKgoO9deOikix_Ie-d1bASFQ93yoJ_jbRE
ABHPNIqJpX_9_qHcRhsBKPrbVcMNhP2BrItmb0WXs4l-0HzP0NXuKVmZO8C_uQjETTRo4tM8FSKlvUa2_wlh_weV_3YlW5FDlnvzRY6KDFY5Jm0_jlvFyqTL
lPAV5dUoSvnfyEz-Vd_-wqppVmE_T4cOp3ID-c-HNnsmQf0owrdBz_Cl_xhzmx-dWVDgkA3W02dMoU_V__JpFtR0lgdXWgC933_Alx-7NwtWWPZywW5r0VE9
SGp9hmxGM8vmF3M1nhz_ASkox06QmDGDluuDdCXhbP-hH9PQVZslrZ2_101LTeI7YsF-ymFzdmH0NWVShKz-W7hdtrhbr_rFFt-J_P_kV_lnroRdVxfKuV_y
brRv-G1eglxnhogfOlsLzG_UrTy1IFpJ63_s4Z_BWnx-z-U_-lbd9__61sUiVphhV_jm_Ml-iuEVrN7hH4d-PrvEFRqZ_q0-fN_AyyXo_yMUzSVx7xB-Bo_x
4dzv_Z_TqZkMLato5XRwTkZWv-q_57JmJ_A6WavrSBaAggR73k_Y9py0_ghztycx_vluyjDYo5DPrlrVRV-xi_gB2w2SfyPqwHo6eZmTSab7na5g9418uPeU
MgWg3_yk_Eg0z996WeibE_DVKAtqK3txMX_y2BwHuJab-ok_4HLPTKD67mP3blUiMW6pyqF_Jl0RB-QMFTc3u9-DPZelBrP_AR_pL-twYYIBR7NyUaZm3reg
nQdxox5rFi0SI_WxFqfho_8ewyTdDA6uTYnd3ww2xnhxAB0X8oSmnvXLz3hqKs8xje8El6_eox4KPRPZcvSTV1dwARGLyxE3hvV4IAcDc1zVBmc2lGDwgNsi
1_RhfZ_uc9GQo1H-ouTCXJyiVY7f1tpXZycEdPE-m1V-kF0RLGyzQmZ1-K67_K8FVhQW-92lrzDLq0VdXpwHvuDhqAi5nCzRDPV5G_35ek7dlQQyQ0jzqOB1
myzs0kZ9u8tFd_0PwGKz9B-zjzCTlu4VjV-7tpZw7tlyjqz-Hun__IV_zsIXWfzbxf8VVCaKiMu2Zh7-eLS_TSYlE_jzycysF_JO5emV_EVvMVqFWTyz_xR9
_TysFmw8rVnxvf-gxh_VS43ygLzyVhdsi3D-cd_bpS_h6el_rYt_NZeaOFFZW0ZyJFtwvD_v_AlvoIACKFqq_nh-9GO_Kpy7Vt9027xmQ_d98WvU_V7vmQ_a
vq1Ut_nhy_o2NyC_1-3VtVoSI8t03tub_ssUc-UNPUywVixGXPpvsloJy8UhVgLN_eaFe6dyL_WvGnnorT_c7qVuurP_V7xmFVpS8jKmFrlUJdwvy2LazTly
I-Fyu3luyoKQCST-9LTBjmYroxzBzRlukKKgHiABdtyFaE_au-SUsNQhtyyljmWrYk_j_U2Vvl_AkmySkO4OYABEjkv_u4twm7mdGe2g9HAZ6xpgOa_l8f3_
0Ovz-PxqKu2d-Q-N_TuYFupl9KUrlFP_3005c7dy9_mp1u3ZX_-4Vk_CFkLt02D_-f_KxvrmjRxs4m3-OUtF-EVz4oJKVloVfWs07xwd_Hw0RLhx8txz4Jpk
xi_vAS0iViG_w8zW-FW_nVmgm9pX3_az00GmX1_pkm13Xd-Hdm2QymCl7_nJ2W3VxO_xUGCCuUVyBa3d0O3FkpVgzpwPRS3Tb_TJ06x0nlnK-_6x09qVWRpx
u8VzNYX40DtllhpVZy01_BpV6pNQy_D-2h1FG7z-tky2DEL_4J_lTm1D-SlzNtG5TkJ7_RslmAtYv_r-1BJX_zJih_2tVGJGVPz-xKxu-mJ0wPk_tk_DsZrk
Fl6ly5C00cZ6p_jRJW3wZulVhxwylsS0lldWb_AuNm7StNtub_afW0BeE_fvloU00ExhllZN-Nq54C0DBrwlwrZfxnQ03v_Hlyj_Im0wVBf_aRyEOBiAxyE7
N_iN1l3vkW3Gm-VmJvn-m4y0NZAwNa_tTVWt-Kd00MnNdBr_zKxuKy-0pspPfGBB1r-JVy8TyXF0-alWBptyc_sCmD8PyBLdVGi_0MW6Y22_d4u_-V0x-0c0
6GWdeDrqw7Nu0NyY0Ly2IY2d1-_gT_Ax0auWm4TVB2XhuIS0Re7zbu0E1Cv-nwE77_2dKo20FO6V9A3lWDUVY__0Vuw9ytudmEhnlpVd7d7pWKV_6NrZlnDW
_NeTml_XxtRmwC4tzpk1zmYKmLP-q95Z_y1RtzzF05--laT01ch18Vntplt3Bdr_Fmdi4QW5wa2fVnoyx8tq-8z6G0Br5Fob1o_x47zz5Ne6QZvww9ty_eu5
m0XGWDhlqszqygy
}

!define DEVOPS_DOCKER_LOGO(_color)                                 SPRITE_PUT(                                      devops_docker_logo, _color)
!define DEVOPS_DOCKER_LOGO(_color, _scale)                         SPRITE_PUT(                                      devops_docker_logo, _color, _scale)
!define DEVOPS_DOCKER_LOGO(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS DOCKER_LOGO,         devops_docker_logo, _color, _scale)
!define DEVOPS_DOCKER_LOGO(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS DOCKER_LOGO,         devops_docker_logo, _color, _scale, _shape)
!define DEVOPS_DOCKER_LOGO(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS DOCKER_LOGO, _label, devops_docker_logo, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS DOCKER_LOGO>> White
