sprite $devops_docker_logo [256x256/16z] {
xDNLWKKX34LHua3_1Szr_vrdERk3XIJbbH6BcaTjhVLphOQR2XELBmz--E677txuuOSVVlZXXnz--E677txuQre__7Z_yCFVi_dXn_l7_YDU_MEzZKtyJFxz
0FRgv6UcykF-wGD47HlKOpjVc5BuFIBggGZFu2_48chcxd5kuYVm4ukg3VavCrNX37uMKLMxf1duetyw0D5RCl9p-5cU-YFVJ7HULs4mgEpzt_-5RzHCH3gY
vSHHhagnbhDy2cMC0mQSdk6l1iJsMKx_tw-Mnw-4lxjcVSu1VJty6qF6X6WJlWp-Yj_W8-iR-H3ydls6IgR__0GE0-m5sUeqfGMWbWLS6So-X3-DvLtwve4a
JmZyKKdwrv71Ee4bXNiQidGyiAgLvh_WiuFH1WR4HF-mZegSqySg-8Vi3fuj786zF3BwgcxuIvAJlZw-ylSLyETEi22OmLzbwpWWoTPJ05J03xu0uL-IUmI8
N3h_h9_VyltyNSlZtstM83_qvDVVmJ__x_nzJ_xS83yfsRYbJzstyZyIl-JB_2JauuW3ckAdIzCyJppV63yPgMuG6k3tbL9oG0Fyxf3sK8tnRqiAJVHDyBi_
gwcDzlXJ8otmkw24FeoqqW2_kwCfe0d-DFmwHcc1t_LagP2a7VxqQmJ0GZi_ll-dDw-TIMl0_Vm6W7ykd7z9liYlpk006cg2Nwq50k2Myy_xuv_NttrH0Dp4
RmAV_rls-R_rQ_p1fkByIwQ04_n4cB__MTLW_QUjWp-tr904tS2_Eq1skFz3bZxFJnK7sEBJ_qFyDmV0ohyHsi3tzIy6_f2JjzlJAHJ-qvnTQd70dVVVjhq0
0CISF6pob7-S0i2pMt_nAmUuh_x11ZqUoClzzd3sSQx_u_oUR6zv0RfY_KkeF0Rld0n_JVzt1m3y7OYcWrwCeaVDwslRuLJ40N29lrp0DzZWwmhrNnroLky-
MedV0H3dX_9e_ypVnVdz6_xz8h-NGFX38Pwt3_YE_xm3FieYbwrQcT_fT8Y_09YTuPAUd-4isvwodUluqFGdVWK0_D4LBfaHSoiSUfAjGvXawSZwRIyFP_Xd
-4Fuqxi5NZaCVuBW-iTTdYrRJmv0Fjh-kFc7GPLOVW5u8fpWBJFsoZ2Myhyffx_F_wYUt6LKwPi3zFeN-CS0F-q64lnW_e_XWETl8sj_07zX9txzFersRIhm
BCZIlV_BFBu5IDezIbSub_ct2J1yeUGTUYASxgd_n7iSdyeOpZo_sNKLycBd3dXoX10auI23Zsm07fwDdpBsrV2zTORpB3zPX-oV-DMU3_YldlzRt_bnNWRd
B3-lr6gPLBB0Bpu1tdR-J_YZMZ_9JyGTx9Xd5lZ_ulpn-jTf3__h_9gICEqq2-DV8xyTiCpEOVIjvGtyymtn7-7_uyECe-62Z0FKR8m_VlyPvt_d03oG_qw5
4EY-arzocD-MyS1lyji3TW7xYRx_INuxmBaSwVWp12f__zLMoP87286X6Nwl3NoHLoa_PU_JV9RVtwjLpAy4u9JjwU4SsFzymVod12ZgWDNQv0UeTVv7lVnC
09Vvgvp_VFyTnr-gtF_vg2B--i-rylC2A5IlhdyEAZ_mBUSVz3K-0IZ_gOmVkyJFyM24_uRwrp3_5EEduF1T_dzr_1ytZx_hdmFyd8wNlYX9VwRZr4CV-GFv
KFwfvv6FbqV8wE_lFtJ-hyvUui_l_uTnTYTURlWOuatOTV3JzHyAElX9HgS1ed6x_aogosExY_ok3u3_rFtl4Bp_tVZIqpBa8I_x_jVn_nSS_jm1A1MkjbG1
0KD67dOvfoFZ81i546hSvQ6PeGhmkqHOhLA4KIXmASd1-XVKKdceltqzd_m8_tE59oFxgRuH5TbwGKRlkeAiVfuw0IlNXtukyEjVB2HRjNwYF98mdUQBmv-h
x_nMSmdco59yXjyV2NwWPL22UhoTiiuBc7A9-EH7QtLPMcNZ-AmcD5UFfUh1HVYXjOy6Ap9g0bEEUOhUIpyjrcCBwC37bhwKIz5cFVQ8ieElfPz6wx08kqTV
YQzQhSJY-BFoVjWReDVeOosmlrxwWu-frHyomp_IHwRY_rdyJD4F-EB_JNRiMFG5VhB_o3iBAubY60OkRzn_mSTpJCfXnh-3UI5_9vB0by8Z7e2UjQ_c1_sM
_Iaz-7nIV5w-FbLNGM_dPywVw3s-RGyhnEUgXdxyk-aQBlmdTqqqRTyrHpOUV5mcFUaQRhhmetm277GjVsh_ukT_6z-__rS5qd_1-HyhlxNrRwxyXxzKnS_f
s9Q_AX3-2_iVM3zruG-Td_py8-KVAlxSzeBklmA_FVyOgVytrp-kwT-PVn_p3n4_mz-HFx0zDFBNZEdN-UpYFxJbhodJFzvH2VZvzUl9Nop_b1y_Ai7mJtXU
dXJyyz4djyz83VpWf_m8aht3x-UVD_r7aDUQ_xm-VuuF_r70NzFy1_IytKf_-0_7uxhyNmyzGd9SpVvy-VRmznp-3IgwQbVxm8_VZQBh7t-uY9Lr-FtyyyEF
YzJQ_2Fk-WSkKfhX3msl_QNVSnCDqTcVPaYlor_1y0Sfae87Bpb_ETuxvVpuo7Of_G8NeKNmcVwJ_0GfhLlvRhybqrTM-kGfyelXFmyvci-qfGag67xX0iXT
lFpyQMPs4FfaEFhz_2youRvU0fJXw9SsGNuqv7sr1H0Klja2ADdipvi0hhq_hu45-DwVuESkNfVbdOUDH3481QNDz5_m9SJji3aPlo_SmGmFZ28WaDq1zPkV
3P04wECt2m2RVn0_10ZZe_oT0c03qWz-x03Ty7dwnVHdt-hJ-BmdOxrcNmu09c2FsSS0O0bKtVl6uFEW40Gqc7rbIw0-FdS0wuNF07W7TCHd04JnLy1l8Y3Z
3-TVOGJguhSPWLQ9dvS06VnzGU-hBG7CVk3Ny4E0GlLhyVDbROt91_p204100toT3Y3zt-37rjT602SVyElu8M1sze5V6G08wDFwkGCWO4xsf-1p1410zSRB
SnsT1B3uRFrw_Ya2Kl61Frc0rS2p-9FmUGwrLe05VXGV-BC4uCXe2Rrd7yMV-h80AwZz_L-lFW6R_uFdunkVdQyYOFmGEASFV8KM6Da3ZBuMFGMm1ym67QUB
gGzy5G7H0vyrWDjqJYzN_3m4OE1Zz05_5dt12D30vwwKdHqeanGGKy1_0cJWpTexVD03NrA06zYx0Rwxl7mv-04FUd43kntkCFCzmkqlu6FeaLxVW9zVloFX
EdYSP8pW0tuv1hOxEh1hZ-n17koRDUWN962r_b4G3d8AxiF7HSO_Tj0lne0hY1J0m3twO-713lgbAJYV15VmIH_m1Uobez11x-8N_FJL2z4M0RZEZ-fBuNy3
}

!define DEVOPS_DOCKER_LOGO(_color)                                 SPRITE_PUT(                                      devops_docker_logo, _color)
!define DEVOPS_DOCKER_LOGO(_color, _scale)                         SPRITE_PUT(                                      devops_docker_logo, _color, _scale)
!define DEVOPS_DOCKER_LOGO(_color, _scale, _alias)                 SPRITE_ENT(  _alias, DEVOPS DOCKER_LOGO,         devops_docker_logo, _color, _scale)
!define DEVOPS_DOCKER_LOGO(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, DEVOPS DOCKER_LOGO,         devops_docker_logo, _color, _scale, _shape)
!define DEVOPS_DOCKER_LOGO(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, DEVOPS DOCKER_LOGO, _label, devops_docker_logo, _color, _scale, _shape)
skinparam folderBackgroundColor<<DEVOPS DOCKER_LOGO>> White
